REPOSITORY-GUIDELINES.md

fixes https://github.com/knative/docs/issues/1278
/assign @rgregg

add missing frontmatter to enable site build

---

STEERING-COMMITTEE.md

Follow-up from the May 10 2019 steering committee meeting.

Elaborate on how to raise issues to the steering committee

---

WORKING-GROUPS.md

Forgot to add the top of page link to the operations WG

Add operations WG header link and update VC URL

---

REPOSITORY-GUIDELINES.md

Per the June 7 2019 steering committee meeting.

Add guidelines for donated repositories

---

WORKING-GROUPS.md

Link to full mission.
Re: https://github.com/knative/eventing/issues/785

Add knative/eventing working group charter/mission statement.

---

SLACK-GUIDELINES.md

* inactivate -> deactivate
* small tweaks to make section headers sentence case vs title case

inactivate -> deactivate, small tweaks

---

STEERING-COMMITTEE.md

This PR removes @mchmarny from the list of steering committee members table

removes @mchmarny from list of steering committee members

---

WORKING-GROUPS.md

As far as meeting the lead criteria, here are the stats for Chao:
*Recognized as having expertise in the group's subject matter.* **Yes**
*Approver for some part of the codebase for at least 3 months.* https://github.com/knative/test-infra/blob/master/OWNERS_ALIASES#L4
*Member for at least 1 year or 50% of project lifetime, whichever is shorter.* https://github.com/knative/test-infra/search?o=asc&q=author%3Achaodaig&s=author-date&type=Commits (first PR dated 12/11/2018)
*Reviewed or merged at least 50 PRs.* https://github.com/knative/test-infra/search?o=asc&q=author%3Achaodaig&s=author-date&type=Commits (191 as of 12/9/2019)
*Primary reviewer for 20 substantial PRs.* https://github.com/knative/test-infra/pull/1459 https://github.com/knative/test-infra/pull/463 …

Update leads for Productivity WG

---

WORKING-GROUPS.md

Adding Channels WG charter and alphabetrically ordering

---

ROLES.md

Remove unused roles

---

TEAM-VALUES.md
VALUES.md

This PR captures the output of a December 2019 steering F2F wrt project values.

Add new VALUES.md for project values

---

ROLES.md

Add / update roles

---

TECH-OVERSIGHT-COMMITTEE.md

Update Evan's employer on TOC page

---

WORKING-GROUPS.md

update web conf link for api-core

---

STEERING-COMMITTEE.md

Updating the steering committee membership to reflect recent changes on the Google side.

Update Google steering members

---

TECH-OVERSIGHT-COMMITTEE.md

Fix casing of VMware

---

WORKING-GROUPS.md

Add rhuss as WG lead for client

---

WORKING-GROUPS.md

Adding lionelvillard as Eventing working group lead.
[Requirements](https://knative.dev/contributing/roles/#working-group-technical-lead):
[X] Recognized as having expertise in the group’s subject matter.
Design and implementation of the apiserversource
Design and implementation of the delivery feature
Design and implementation of the parallel feature
Numerous stability and reliability improvements 
[X] Approver for some part of the codebase for at least 3 months (approver for part of the codebase since Sep 24 (4mo+))
[X] Member for at least 6 months (joined in May 2019)
[X] Primary reviewer for 20 substantial PRs ([35](https://github.com/knative/eventing/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Amerged+-author%3Alionelvillard+commenter%3Alionelvillard+-label%3Asize%2FS+-label%3Asize%2FXS+-label …

Add lionelvillard as Eventing working group lead

---

ROLES.md

While steering determines explicit criteria / procedure

Add note about interim role removal

---

ROLES.md

Adds notes on desired norms for communicating long leaves and related procedures

Add notes on roles

---

TECH-OVERSIGHT-COMMITTEE.md
mechanics/TOC.md

Defines:
- Eligibility criteria for TOC candidacy
- Voting eligibility criteria
- Election process
Thanks a lot to @bsnchan for driving much of the way to make this PR :) :100: 
Closes out #59

Add TOC election mechanics and eligibility criteria

---

working-groups/WORKING-GROUPS.md

[Requirements](https://knative.dev/community/contributing/roles/#working-group-leadership-roles):
-  Core maintainer of the CI/CD system that lives in [knative/test-infra](github.com/knative/test-infra)
-  Main contributor of several tools and scripts used in Knative CI/CD flows
-  Many other improvements and fixes
- Approver for [knative/test-infra](github.com/knative/test-infra) since [Dec 12, 2019](https://github.com/knative/test-infra/pull/1590)
- Joined Knative in February 2019
- [19 L, XL, XXL in knative/test-infra](https://github.com/knative/test-infra/pulls?q=is%3Apr+is%3Amerged+-author%3Achizhg+reviewed-by%3Achizhg+-label%3Asize%2FS+-label%3Asize%2FXS+-label%3Asize%2FM+)
- [3 L, XL, XXL in knative/pkg](https://github.com/knative/pkg/pulls?q=is%3Apr+is%3Amerged+-author%3Achizhg+rev …

Add Chi Zhang as Productivity WG technical lead.

---

mechanics/README.md

Added a feature track link to the process/guidelines page.
Fixes https://github.com/knative/docs/issues/2370

Added Feature Tracks link to process/guidelines

---

working-groups/WORKING-GROUPS.md

Add directions for importing calendar to WORKING-GROUPS.md

---

CONTRIBUTING.md
README.md
SLACK-GUIDELINES.md
STEERING-COMMITTEE.md
WORKING-GROUPS.md
docs/DOCS-CONTRIBUTING.md
docs/README.md
mechanics/WORKING-GROUP-PROCESSES.md

This contains the commit from #123 and then a run of:
`prettier --prose-wrap=always --write`

Run prettier after #123

---

mechanics/WORKING-GROUP-PROCESSES.md

Make it clear that community consensus should be clear before writing a charter.
Include example charters for reference.
/assign @mikehelmick 
/assign @mattmoor 
/assign @vaikas 
PTAL and suggest further refinements to the process.

Update the process for creating a new working group.

---

working-groups/WORKING-GROUPS.md

renaming the channels wg to 'Event Delivery'

---

elections/README.md

No changes to the voter guide or the current 2020 election.
- Fix the email address group that we're using.
- Add additional details for how to create the poll.

Clarify parts of the election mechanics

---

mechanics/RELEASE-VERSIONING-PRINCIPLES.md

Fixes https://github.com/knative/eventing/issues/3006

update eventing release matrix.

---

TECH-OVERSIGHT-COMMITTEE.md

As per title. Sorted ascending by name.

Reconcile the members of the ToC after election.

---

OWNERS_ALIASES

Reconcile ToC members in OWNER_ALIASES.

---

STEERING-COMMITTEE.md

Update steering committee membership with new Google representatives.

New Google representatives in steering

---

peribolos/knative-sandbox.yaml

I'm already a Knative member.
PRs authored:
- [knative/eventing (4)](https://github.com/knative/eventing/pulls?q=is%3Apr+author%3ApierDipi+is%3Aclosed+is%3Amerged+)
- [knative/eventing-contrib (14)](https://github.com/knative/eventing-contrib/pulls?q=is%3Apr+author%3ApierDipi+is%3Aclosed+is%3Amerged+)
PRs reviewed:
- [knative/eventing (4)](https://github.com/knative/eventing/pulls?q=is%3Apr+reviewed-by%3ApierDipi+is%3Amerged+-author%3ApierDipi+) 
- [knative/eventing-contrib (7)](https://github.com/knative/eventing-contrib/pulls?q=is%3Apr+reviewed-by%3ApierDipi+is%3Amerged+-author%3ApierDipi)
related: https://github.com/knative/community/issues/143, https://github.com/knative-sandbox/eventing-kafka-broker/pull/2
Signed-off-by: Pierangelo Di Pilato <pierangelodipilato@gmail.com>

Add pierDipi to knative-sandbox members

---

peribolos/knative-sandbox.yaml

Signed-off-by: Pierangelo Di Pilato <pierangelodipilato@gmail.com>
related: https://github.com/knative/community/issues/143

Add eventing-kafka-broker to knative-sandbox peribolos repos

---

peribolos/knative-sandbox.yaml
peribolos/knative.yaml

Remove knative-prow-robot from non-admin org users since they were made admin in #159

Fix Peribolos error

---

peribolos/knative-sandbox.yaml
peribolos/knative.yaml

Related: knative/community#153
/hold
/assign @tcnghia @chaodaiG

Move sample-source to knative-sandbox

---

peribolos/knative-sandbox.yaml
peribolos/knative.yaml

Change `Abd4llA` to `devguyio` since I've renamed my GitHub username.

Rename Abd4llA to devguyio

---

mechanics/WORKING-GROUP-PROCESSES.md

Update working group processes to match actual behavior.

---

peribolos/knative-sandbox.yaml

Creating repo for request at https://github.com/knative/eventing/issues/3167

Add discovery repo to peribolos

---

working-groups/WORKING-GROUPS.md

Signed-off-by: Matthias Wessendorf <mwessend@redhat.com>
/assign @Harwayne

updating to the new schedule

---

peribolos/knative.yaml

Please approve this PR to add me to the knative github organization. I'm a googler working on knative.

Add arenault to knative member list

---

peribolos/knative-sandbox.yaml
peribolos/knative.yaml

Part of knative/community#153
/hold

Reflect the net-http01 migration in Peribolos

---

working-groups/WORKING-GROUPS.md

Fix links in WORKING-GROUPS.md

---

peribolos/knative-sandbox.yaml
peribolos/knative.yaml

Part of https://github.com/knative/community/issues/153
/hold

Move net-{certmanager,contour} to knative-sandbox.

---

peribolos/knative-sandbox.yaml
peribolos/knative.yaml

Part of #153 
/hold
/assign @mattmoor

Move remaining net-* repos to knative-sandbox.

---

working-groups/WORKING-GROUPS.md

Completed Dec' 2019
https://www.vmware.com/company/news/releases/vmw-newsfeed.VMware-Completes-Acquisition-of-Pivotal.3b73174e-4485-4ff9-8c5d-56c54de6db86.html

update company information

---

peribolos/knative.yaml

This pull request is to add zhongduo@google.com to the members list.

Add zhongduo to members list

---

peribolos/knative.yaml

I'm working at Google in KNative and I want to add myself to the KNative community member list.

Add danyinggu to the member list

---

peribolos/knative.yaml

Signed-off-by: rickr <cr22rc@users.noreply.github.com>

Add cr22rc to members list

---

mechanics/RELEASE-VERSIONING-PRINCIPLES.md

Fixes: #167 
/assign @pmorie @mattmoor

Clarify the K8s minimum version principle

---

peribolos/knative.yaml

Signed-off-by: Francesco Guardiani <francescoguard@gmail.com>

Added myself to eventing triage

---

peribolos/knative-sandbox.yaml
peribolos/knative.yaml
working-groups/WORKING-GROUPS.md

Fixes: https://github.com/knative/community/issues/166

Retire the Observability Working Group

---

peribolos/knative-sandbox.yaml
peribolos/knative.yaml

I am not sure what permissions are needed, so start with admin.

Add permissions for Knative Release Leads

---

peribolos/knative.yaml

Per: https://github.com/knative/eventing/blob/master/support/COMMUNITY_CONTACTS.md

adding myself to Eventing Triage

---

peribolos/knative-sandbox.yaml
peribolos/knative.yaml
working-groups/WORKING-GROUPS.md

True up community with serving#9057, serving #9058, and mdemirhan stepping down

---

peribolos/knative-sandbox.yaml
peribolos/knative.yaml

Related issue https://github.com/knative/community/issues/243

Add myself into member list

---

peribolos/knative-sandbox.yaml
peribolos/knative.yaml

add myself as a member to knative & knative-sandbox.

add myself as member

---

peribolos/knative.yaml

Signed-off-by: Ansu Varghese <avarghese@us.ibm.com>

Add aavarghese to members list

---

peribolos/knative.yaml

New member of the eventing team at Google.

Add AlexandraRoatis to the members list

---

ROLES.md

Fix `</td` tag close in ROLES.md

---

peribolos/knative-sandbox.yaml
peribolos/knative.yaml

Hi 👋 I am from GSoC 2020.
I've been working on Sources stuff. I would like to keep it.
Thanks!

add tom24d to members

---

peribolos/knative.yaml

Adding myself to the milestone maintainers list specially to look into Eventing milestones.

Add devguyio to Milestone Maintiners and sort the list

---

peribolos/knative-sandbox.yaml

Relates to https://github.com/knative/community/issues/252

Adding reconciler-test to repo config for sandbox

---

elections/2020/README.md

Remove unnecessary whitelist terminology.

---

OWNERS_ALIASES

Since she's on the Steering Committee. In the spirit of #269 ; I'll resolve the merge conflict.
/hold

Add April to OWNERS_ALIASES

---

ROLES.md

Part of https://github.com/knative/serving/issues/8005 .

Document oncall rotation participation.

---

peribolos/knative-sandbox.yaml
peribolos/knative.yaml

Per schedule: https://github.com/knative/pkg/blob/master/RELEASE-LEADS.md#schedule

Setting Zhimin and Scott for 0.18 release leads.

---

peribolos/knative-sandbox.yaml

As discussed in [issue](https://github.com/knative/community/issues/211), would you please help to review and merge it! Thanks!

Add kperf to the peribolos sandbox config

---

peribolos/knative-sandbox.yaml
peribolos/knative.yaml

Adding eclipselu (danglu@google.com) to members list.

Add eclipselu to members list

---

working-groups/WORKING-GROUPS.md

Sam stopped working on the project some time in March.

Removing Sam as Doc WG lead

---

peribolos/knative-sandbox.yaml
peribolos/knative.yaml

Ref: #287 
/assign @RichieEscarez @mattmoor

Followup to #287 removing samodell from peribolos

---

peribolos/knative-sandbox.yaml

Signed-off-by: Ansu Varghese avarghese@us.ibm.com

Add aavarghese to knative-sandbox members list

---

peribolos/knative-sandbox.yaml
peribolos/knative.yaml
working-groups/WORKING-GROUPS.md

Hereby I nominate Navid Shaikh as a Technical Working Group Lead for the Knatice Client Working Group
He mets all the [WG lead criteria](https://knative.dev/community/contributing/roles/#working-group-technical-lead) and is also the [top contributor of knative/client](https://github.com/knative/client/graphs/contributors):
* Approver for a relevant part of the codebase for at least 3 months  --> **yes** (14 months)
- Added as approver with https://github.com/knative/client/pull/321
* Member for at least 6 months --> **yes**
* Primary reviewer for 20 substantial PRs. --> **ca. 22 PRs**
- https://github.com/knative/client/pulls?q=is%3Apr+is%3Aclosed+assignee%3Anavidshaikh+label%3Asize%2FXXL+
- https://github.com/knative/client/pulls?q=is%3Apr+is%3Aclosed+assignee%3Anavidshaikh+label%3Asize%2 …

Add Navid as a Client WG Technical Lead

---

working-groups/WORKING-GROUPS.md

[Requirements](https://knative.dev/community/contributing/roles/#requirements-3):
- Been involved in the working group since June, 2018
- Was heavily involved in the inception of the Broker / Trigger APIs
- Helped the WG get through a discussion bottleneck via suggesting a decision making process (e.g [this decision](https://docs.google.com/spreadsheets/d/14uj8A3NzGhHzCbcRbVnLItHhRytct09M9jxRGykrhcw/edit#gid=0))
- Lead the first adoption of the Broker/Trigger APIs [in a GA release](https://kyma-project.io/blog/2020/3/31/release-notes-111/#eventing) 
- Eventing working group improvement initiatives
- [Knative Eventing WG Planning & Execution Analysis](https://docs.google.com/document/d/1XMdVsD6bkU2qd4JV2UUWM8Hmc5DTc4V1Jgt3m_gHb6I/edit#heading=h.67wupjiy2z3y )
- Eventing WG …

Add Ahmed Abdalla as Eventing WG execution lead

---

TRADEMARK-COMMITTEE.md

Add Doug Davis to KTC

---

peribolos/knative.yaml

this is needed in order to complete
this PR: https://github.com/knative-sandbox/eventing-ceph/pull/10

add yuvalif to members

---

peribolos/knative-sandbox.yaml
peribolos/knative.yaml

Signed-off-by: runzexia <root@junwuhui.cn>
I would like to be added to the knative org.
I am contributing to eventing/eventing source

add runzexia to knative/knative-sandbox members

---

mechanics/tools/gdocs-migrate/main.go
mechanics/tools/gdocs-migrate/oauth.go

- Attempt to parse cache file only when read succeeds
- Avoid creating new `err` variables in condition blocks
- Typo in error
- Change code to list files in team Drives
- Update scope to allow team Drive listing

Fix token caching bugs and add clarifying comments

---

peribolos/knative-sandbox.yaml

PR #303 was closed by a wrong operation...   Open a new one to continue the process.
Part of https://github.com/knative/community/issues/296

add kn-diag repo into peribolos/knative-sandbox.yaml

---

peribolos/knative-sandbox.yaml

Related: https://github.com/knative/community/issues/298
/assign @knative/productivity-wg-leads

Create a repository to home the knobots.

---

mechanics/tools/gdocs-migrate/forest.go
mechanics/tools/gdocs-migrate/main.go

* Increase page size for faster operation
* Store all File metadata in a forest
Next step would be to copy them from one drive to the other.

Load all files metadata into a forest

---

peribolos/knative.yaml

create trademark group

---

peribolos/knative.yaml

Ref: https://github.com/knative/community/issues/322

Create the hack repo

---

working-groups/WORKING-GROUPS.md

We moved to weekly to include talk for the knative testing frameworks.

fix the Productivity wg meeting time

---

elections/2020/SC/README.md

Also fixed heading level for schedule and added contact info for the election officers.

Added election officers to 2020 SC voting docs

---

.github/ISSUE_TEMPLATE/new-repo.md

/hold
HOLD until everything else has been confirmed.
Fixes: https://github.com/knative/community/issues/298

Update the new-repo instructions

---

working-groups/WORKING-GROUPS.md

Correct the Docs WG meeting time

---

peribolos/knative-sandbox.yaml

Signed-off-by: Yuval Lifshitz <ylifshit@redhat.com>

add yuvalif to sandbox

---

peribolos/knative.yaml

I'm a Googler working on knative.

Adding myself to the knative members list

---

.github/ISSUE_TEMPLATE/new-repo.md

* added some clarifications to board process
* added link to `knative-sandbox/hack` as the boostrap for projects
* added checklist to remind to add GH ID to OWNERS

some clarifications/improvements as I test new repo checklist while adding new repos to knative-sandbox

---

elections/2020/SC/jacques-chester.md

Per SC election process, here is a PR with my candidacy form.
[Rendered](https://github.com/knative/community/blob/6ab6dcfe6d028efba3bead2d3b2c37ea83a19c6f/elections/2020/SC/jacques-chester.md)

Add Jacques Chester as SC candidate

---

elections/2020/SC/pmorie.md

Want to help continue to grow community!

Add pmorie to steering election 2020

---

elections/2020/SC/arghya-sadhu.md

Here is a PR with my nomination for SC election 2020

Add Arghya Sadhu as SC election 2020 candidate

---

elections/2020/SC/csantanapr.md

Per SC election process, here is a PR with my candidacy form.
[Rendered](https://github.com/csantanapr/knative-community/blob/ksc-nomination-cs/elections/2020/SC/csantanapr.md)

Add Carlos Santana 🎸 as SC election 2020 candidate

---

elections/2020/SC/goasguen.md

goasguen SC candidacy

---

peribolos/knative.yaml

I'm a new member of the Knative Eventing team at Google

Add stuart-xyz to members list

---

elections/2020/SC/vaikas.md

Follow onto #357 that may or may not have more context on the why.

vaikas 2020 SC nomination

---

mechanics/RELEASE-SCHEDULE.md

Add frontmatter so this page is added to the site TOC and is visible in the navigation tree

Add frontmatter so this page shows in the website too

---

peribolos/knative-sandbox.yaml
peribolos/knative.yaml

Apply to join the Knative organization，here is my PRs and issue.
[https://github.com/knative/docs/pull/2999]()
[https://github.com/knative/docs/pull/2998]()
[https://github.com/knative/docs/pull/2996]()
[https://github.com/knative/docs/pull/2997]()
[https://github.com/knative/docs/pull/2988]()
[https://github.com/knative/docs/pull/2964]()
[https://github.com/knative/docs/pull/2948]()
[https://github.com/knative/serving/issues/10040]()

Add zhaojizhuang to the knative members list

---

elections/2020/SC/README.md
elections/2020/SC/voters.md

Add link to ballot replacement form.
Add one voter due to exception request.
This is information required for starting the election tommorrow.
@bsnchan, please merge.
cc @geekygirldawn @macruzbar

Add candidates list, TOC.

---

peribolos/knative-sandbox.yaml

ref: https://github.com/knative/community/issues/324

add actions-kind, drop temp group for actions

---

peribolos/knative.yaml

Hey,
I'm an engineer at vmware, I will be working on knative.

Add youssb to knative contibutors

---

TRADEMARK-COMMITTEE.md

Adds details for trademark committee

---

peribolos/knative-sandbox.yaml

Added contributors from https://github.com/knative-sandbox/kperf and https://github.com/knative-sandbox/kn-plugin-admin. Thanks!

add members from kperf and kn-plugin-admin

---

peribolos/knative-sandbox.yaml
peribolos/knative.yaml
working-groups/WORKING-GROUPS.md

- Stepping down as I'll be mainly working on another project(s).

Removing nachocano from Sources WG leads

---

peribolos/knative-sandbox.yaml
peribolos/knative.yaml

Add myself to the members list

Update knative.yaml & knative-sandbox.yaml: Add myself

---

peribolos/knative-sandbox.yaml

- Add `dsimansk` to knative-sandbox org
FYI @navidshaikh @rhuss

Add myself to knative-sandbox org

---

peribolos/knative-sandbox.yaml

-
-
-
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```

Add Jimmy Lin (zhongduo) to knative-sandbox member

---

peribolos/knative-sandbox.yaml

Add kn-plugin-source-kamelet to peribolos configuration

---

STEERING-COMMITTEE.md

Updates steering committee's email group. We decided to move to the knative.team Google group so we can self manage it :)

Updates steering committee's email group

---

OWNERS_ALIASES
STEERING-COMMITTEE.md
peribolos/knative-sandbox.yaml
peribolos/knative.yaml

Updates steering members based on 2020 elections in peribolos and steering-committee.md.

Updates steering members based on 2020 elections

---

peribolos/knative-sandbox.yaml
peribolos/knative.yaml

Add Ahmed to Eventing WG leads peribolos group.

Add Ahmed to Eventing WG leads

---

working-groups/WORKING-GROUPS.md

Point to the correct drive folder and meeting notes

Update API Core details in WORKING-GROUPS.md

---

peribolos/knative-sandbox.yaml
peribolos/knative.yaml

I'm working on Knative eventing at IBM.
Update knative-sandbox.yaml: Add kthakar1990
Add to the members list
Update knative.yaml: Add kthakar1990
Add to members list

adding kthakar1990 to knative and knative sandbox members

---

BRANDING.MD

As we get more feedback/requests we should update the info here so people don't need to ping us for an answer.
/cc @bsnchan @ronavn 

Be more explicit about not changing the logo

---

working-groups/WORKING-GROUPS.md

Fix link to eventing WG agenda doc

---

peribolos/knative-sandbox.yaml
peribolos/knative.yaml

I'm working on Knative eventing at IBM.
Update knative-sandbox.yaml: Add steven0711dong
Add to the members list
Update knative.yaml: Add steven0711dong
Add to members list

adding steven0711dong to knative and knative sandbox members

---

peribolos/knative.yaml

👋 I'm joining the VMware Knative team
- Add myself as member

add myself to the members list

---

peribolos/knative-sandbox.yaml
peribolos/knative.yaml
working-groups/WORKING-GROUPS.md

Add Security WG
Fixes #347 
/assign @julz @grantr

Add security WG

---

peribolos/knative.yaml

As one of the step for community contacts: https://github.com/knative/eventing/blob/master/support/COMMUNITY_CONTACTS.md

Add zhongduo (Jimmy Lin) to Eventing Triage group 

---

peribolos/knative.yaml

Fixes: https://github.com/knative/community/issues/91

Drop the vestigial TBD group

---

working-groups/WORKING-GROUPS.md

- :broom: Add Security WG to table of contents
- :broom: Move Productivity WG to correct place alphabetically, matching table of contents
/kind cleanup

Fix bullets and re-alphabetise working group list

---

peribolos/knative.yaml
working-groups/WORKING-GROUPS.md

:wastebasket: Remove myself as docs WG lead
/kind removal

Remove abrennan89 as docs WG lead

---

peribolos/knative-sandbox.yaml
peribolos/knative.yaml

-
-
-
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```

Add cathyzhyi into member list

---

peribolos/knative.yaml

As per #101 add @RichieEscarez into the Release Leads so that we can remove the temporary group.

address issue 101

---

peribolos/knative.yaml

Addresses fallout from #425
Details for why this appears to be necessary:
https://github.com/knative/test-infra/issues/2652
And in particular this from prow logs:
```
{"component":"unset","file":"prow/cmd/peribolos/main.go:202","func":"main.main","level":"fatal","msg":"Configuration failed: failed to configure knative members: all team members/maintainers must also be org members: eallred-google","severity":"fatal","time":"2021-02-04T08:38:16Z"}
```
-
-
-
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```

move eallred-google to org member

---

peribolos/knative-sandbox.yaml
peribolos/knative.yaml
working-groups/WORKING-GROUPS.md

- :broom: Remove Harwayne as a Working Group lead.
/kind removal
```release-note
NONE
```

Remove Harwayne as a Working Group lead.

---

peribolos/knative-sandbox.yaml

(+ sort kn-plugin entries alphabetically)

chore: Add kn-plugin event to peribolos

---

peribolos/knative.yaml

Adding myself to be able to triage issues.
Ref. https://github.com/knative/eventing/pull/4850

Add antoineco to 'Eventing Triage'

---

peribolos/knative-sandbox.yaml
peribolos/knative.yaml
working-groups/WORKING-GROUPS.md

Requirements:
Signed-off-by: Francesco Guardiani <francescoguard@gmail.com>

Adding slinkydeveloper as Delivery WG lead

---

peribolos/knative-sandbox.yaml

(and sort the kn-plugins alphabetically)

chore: Add kn-service-log to peribolos configuration

---

working-groups/WORKING-GROUPS.md

Adding Github Teams to Working Group doc

---

TECH-OVERSIGHT-COMMITTEE.md
peribolos/knative-sandbox.yaml
peribolos/knative.yaml

- :broom: Remove tcnghia from TOC doc and corresponding Peribolos
/kind cleanup
Fixes #
```release-note
NONE
```
**Docs**
```docs
NONE
```

Remove tcnghia from TOC doc and corresponding Peribolos

---

peribolos/knative.yaml
working-groups/WORKING-GROUPS.md

* Update @navidshaikh company
* Removed @sixolet
Thanks a lot Naomi for all your work and kicking off the Knative client 🙏 !
@sixolet hope the PR is ok, as you have mentioned that you want to step down.

update client working group leads

---

peribolos/knative-sandbox.yaml
peribolos/knative.yaml
working-groups/WORKING-GROUPS.md

@dprotaso does all of the hard work anyways 😜

Step down as API WG lead

---

peribolos/knative.yaml

Fixes: https://github.com/knative/community/issues/360

Setup knative/release repo

---

peribolos/knative-sandbox.yaml

Signed-off-by: Francesco Guardiani <francescoguard@gmail.com>
Fix #462
- :gift: Add control protocol repo

Add control protocol repo

---

peribolos/knative-sandbox.yaml
peribolos/knative.yaml

I’m working on edge computing at Bytedance and using Knative as our Serverless framework.  I apply to join the Knative organization. Here is my issue and PRs.
https://github.com/knative/serving/issues/10133
https://github.com/knative/serving/issues/10528
https://github.com/knative/docs/issues/3218
https://github.com/knative/docs/issues/3220
https://github.com/knative/docs/issues/3221
https://github.com/knative/docs/issues/3222
https://github.com/knative/docs/issues/3223
https://github.com/knative/docs/issues/3224
https://github.com/knative/docs/issues/3225
https://github.com/knative-sandbox/eventing-natss/issues/93
https://github.com/knative/serving/pull/10101
https://github.com/knative/docs/pull/3219

add yangyunfeng007 to knative members list

---

peribolos/knative-sandbox.yaml
peribolos/knative.yaml

New repo knative/ux
Related to #475

new repo ux

---

STEERING-COMMITTEE.md

Change to the meeting, they are weekly, add a link to the notes
-
-
-
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```

update meeting, add link to notes

---

mechanics/WORKING-GROUP-PROCESSES.md

Closes #470 
Closes #468 
Closes #467

update working-group-process doc links

---

peribolos/knative-sandbox.yaml

/assign @knative/networking-wg-leads 
/hold

Add github teams for each of the net-* repos

---

working-groups/WORKING-GROUPS.md

Add UX WG to WORKING-GROUPS.md
Related to #466

Add UX WG to WORKING-GROUPS.md

---

peribolos/knative-sandbox.yaml

Add a team for kperf approvers

---

mechanics/RELEASE-VERSIONING-PRINCIPLES.md

Add the next two releases .22 and .23 to the calendar. As per https://github.com/knative/eventing/issues/4836 also mark the eventing v1beta1 APIs as removed then.
-
-
-
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```

extend to .23, remove v1beta1 eventing in .23

---

peribolos/knative-sandbox.yaml
peribolos/knative.yaml

Gerardo is a new member from Google.
FYI @gerardo-lc

Add gerardo-lc to knative and knative-sandbox org

---

peribolos/knative-sandbox.yaml

Add control-protocol and discovery approvers teams

---

mechanics/GDRIVE.md

Documents our GSuite setup. Thanks to @bsnchan for writing a lot of this. This is a transcription of https://docs.google.com/document/d/1N1jNn_9ILi85VsvlnmDhfyPjLfAK5VZAPKhSwTzs4-4/edit for easier location and change tracking.
Fixes #86

Add GSuite documentation

---

README.md

- :bug: Fix Broken link to point to https://knative.dev
- Considered pointing to https://github.com/knative/docs/blob/master/docs/_index.md but think knative.dev is more appropriate.
-
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```

point broken link to knative.dev

---

mechanics/SC.md
mechanics/TOC.md

- Somewhere in the conversion from doc -> markdown, we lost the explicit 2 year term for TOC/SC members. Adding it back. Original doc: https://docs.google.com/document/d/1lKAwJsQYyR-KCO_efMF4LK9aw4oHPREB7CctIhsSyEY/edit
-
-
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```

add explicit 2 year term

---

STEERING-COMMITTEE.md
TECH-OVERSIGHT-COMMITTEE.md

- As discussed in the steering meeting on 2021-02-25 it was deemed that having a new column indicating when a member of TOC / SC got their seat would be a good thing. So, add that.
-
-
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```

add term column

---

peribolos/knative-sandbox.yaml

Adding @steven0711dong to the Kafka MT source team

Add Kafka MT source team

---

peribolos/knative-sandbox.yaml
peribolos/knative.yaml

- Add @sbawaska to knative and knative-sandbox orgs.
-
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```

add sbawaska to knative / knative-sandbox orgs

---

peribolos/knative-sandbox.yaml
peribolos/knative.yaml

- I fatfingered bavaska, should be: bawaska
-
-
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```

sigh: bavaska -> bawaska

---

peribolos/knative-sandbox.yaml

- Followup to #506 and #507 since I was unable to add sbawaska to approvers in one fell swoop.
- Add sbawaska to knative-sandbox/eventing-rabbitmq approvers.
-
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```

add sbawaska to knative-sandbox/eventing-rabbitmq approvers

---

peribolos/knative-sandbox.yaml
peribolos/knative.yaml

-
-
-
/kind <kind>
Fixes # https://github.com/knative/community/issues/499
```release-note
```
**Docs**
```docs
```

Specs repo peribolos changes + Conformance WG

---

ROLES.md

Add a section to the Member section that one needs to be added to the peribolos config files.

Add peribolos note

---

peribolos/knative-sandbox.yaml

Updating control-protocol approvers

Updating control-protocol approvers

---

peribolos/knative-sandbox.yaml
peribolos/knative.yaml

We are using Knative as our serverless framework, expected PR can be test directly.
I apply to join the Knative organization. 
Here is my contribution.
https://github.com/knative-sandbox/kn-plugin-source-kafka/pulls?q=is%3Apr+author%3Awzshiming
https://github.com/knative/serving/pulls?q=is%3Apr+author%3Awzshiming

Add wzshiming to the members list

---

TRADEMARK-COMMITTEE.md

Adds details about public trademark committee meeting

Adds details about TM meeting

---

elections/README.md

Fixes: #447 
- :broom: Link to 2020 SC election details instead of a standing TBD.
-
-
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```

link 2020 election instead of TBD

---

ROLES.md

Adds governance details around sandbox repos. Fixes #295.

Adds governance details around sandbox repos

---

peribolos/knative.yaml

-
-
-
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```

Add tayarani as Comformance WG lead

---

OWNERS_ALIASES
TECH-OVERSIGHT-COMMITTEE.md
peribolos/knative-sandbox.yaml
peribolos/knative.yaml

cc @knative/technical-oversight-committee @knative/steering-committee

Drop mattmoor from TOC groups

---

peribolos/knative.yaml

- 🧹  Cleanup a few users who have had multiple declined/timed-out invites
- 🧹  Remove a user who blocked the organization (See also #520 )
/kind cleanup
/assign @chizhg @vaikas

Remove bouncing/blocked users

---

.github/ISSUE_TEMPLATE/new-repo.md
CONTRIBUTING.md
README.md
REPOSITORY-GUIDELINES.md
ROLES.md
STEERING-COMMITTEE.md
docs/README.md
elections/2020/SC/README.md
elections/2020/TOC/README.md
mechanics/CREATING-A-SANDBOX-REPO.md
mechanics/FEATURE-TRACKS.md
mechanics/SC.md
mechanics/TOC.md
working-groups/WORKING-GROUPS.md

As per title, mostly a search&replace.

Drop unnecessary occurrences of master

---

working-groups/WORKING-GROUPS.md

We never updated it after moving to the new drive
/assign @markusthoemmes @evankanderson

Fix the Scaling WG doc

---

working-groups/WORKING-GROUPS.md

- Updated the shared drive link. 
Fixes 
While looking for one of the doc in shared drive, I noticed that this page still has older link in here https://knative.dev/community/contributing/working-groups/working-groups/

Shared drive link updated

---

mechanics/WORKING-GROUP-PROCESSES.md

@csantanapr created https://github.com/knative/community/issues/466 to document the UX WG creation. This might be useful to future WG creators as an example, so I added a link to it from the mechanics doc.

Link to example of working group creation process

---

working-groups/security/vmt.rotation

So that we can start adding people and it's not just @julz and I.
/assign @julz

Check in initial VMT rotation

---

README.md

trademark committee markdown was not linked like the other docs.
-
-
-
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```

add trademark committee doc to "toc"

---

docs/README.md

-
-
-
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```

Fixed a typo

---

SECURITY.md

Implement the simpler "GitHub intake" SECURITY.md recommended in #258.
https://github.com/knative/community/pull/258#issuecomment-780830476

Add minimal SECURITY.md

---

peribolos/knative-sandbox.yaml

-
-
-
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```

Add lberk to the list of eventing-kafka approvers

---

peribolos/knative-sandbox.yaml
peribolos/knative.yaml

- :broom: Update Knative release leads for 0.23
/kind cleanup
```release-note
NONE
```

tcnghia@ vaikas@ -> Knative Release Leads for 0.23

---

mechanics/TOC.md

Clarifies company limitations in the TOC elections process

Adds details to TOC elections about company limitations

---

peribolos/knative-sandbox.yaml
peribolos/knative.yaml
working-groups/WORKING-GROUPS.md

Remove vaikas from eventing-sources WG lead.
- :gift: Remove vaikas as an eventing-sources wg lead.
-
-
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```

remove vaikas from eventing-sources leads

---

working-groups/WORKING-GROUPS.md

Updates the time that the docs working group meetings occurs.

Update time for docs WG meeting

---

mechanics/TOC.md

- Updates the TOC election docs so it's clear that vendor/company limitations don't restrict candidate eligibility.

Specifies that vendor limitations do not restrict candidate eligibility

---

peribolos/knative.yaml

Add pmbanugo as a member of the community, specifically the Doc group
- :gift: Add pmbanugo as a member of the Doc group

Add pmbanugo to the Doc group

---

OWNERS_ALIASES

I'm still working on knobots automation, so regenerate this by hand today.

Regenerate OWNERS_ALIASES

---

peribolos/knative-sandbox.yaml
peribolos/knative.yaml

Going to be working on eventing, might as well get those sweet sweet auto-`ok-to-test`s

Add benmoss to members

---

elections/2021-TOC/candidate-evana.md

- Put in my candidacy for TOC elections

Evan TOC candidacy.

---

elections/2021-TOC/candidate-dprotaso.md

dprotaso's TOC candidacy submission

---

elections/2021-TOC/voters.yaml

@bsnchan, please approve.  Thanks!

Add two voters per approved exception requests.

---

mechanics/SUNSETTING-FEATURES.md

- :bug: fix a typo.
-
-
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```

future->feature

---

peribolos/knative-sandbox.yaml

@vaikas 
add myself to the eventing-natss member list

add myself to approver memberlist

---

peribolos/knative.yaml

Howdy! I'm joining the IBM Knative team

add psschwei to members list

---

peribolos/knative.yaml

Account has been deleted and is causing the job to fail
https://prow.knative.dev/view/gs/knative-prow/logs/post-knative-peribolos/1393204916075368448

Remove jszroberto

---

peribolos/knative-sandbox.yaml
peribolos/knative.yaml

remove peterfeifanchen from knative/knative-sandbox

---

peribolos/knative-sandbox.yaml

Signed-off-by: Francesco Guardiani <francescoguard@gmail.com>

Fix eventing-kafka-broker Eventing Writers access

---

peribolos/knative.yaml

Adding myself as an org member based on my contributions as a Knative elections officer. 
cc: @bsnchan @vaikas

Org membership 

---

peribolos/knative-sandbox.yaml
peribolos/knative.yaml

As per: https://github.com/knative/release#schedule
Update the release leads for the 0.24 release. Please ack the handoff for the next release:
@dprotaso 
@matzew

Update release leads for 0.24 -> dprotaso,matzew

---

peribolos/knative.yaml

Add Rodolfo

---

mechanics/TOC.md

Fixes #621 
As discussed at steering meeting 20/5/21.

Remove company limits for TOC

---

working-groups/security/threat-model.md

Fixes #541 
- 🎁 Adds an initial (incomplete but we have to start somewhere!) threat model.

Add initial threat model document

---

peribolos/knative-sandbox.yaml
peribolos/knative.yaml
working-groups/WORKING-GROUPS.md

- :wastebasket: Remove myself as a WG lead. I am no longer full time @ Knative, and it is hard to contribute to the expectation of the WG lead role.
/kind cleanup
```release-note
NONE
```
**Docs**
```docs
NONE
```

Networking WG Leads -= { tcnghia }

---

peribolos/knative.yaml

-
-
-
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```

Add self as member to knative.yaml

---

peribolos/knative-sandbox.yaml

-
-
-
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```

Add self to knative-sandbox.yaml

---

TECH-OVERSIGHT-COMMITTEE.md

@julz @dprotaso @evankanderson - please make sure all of your info looks good before we merge this. Also, congratulations! 🎉

Updated the TOC page with the final results of the 2021 TOC election

---

working-groups/security/responding.md

Relaxing requirements for PST membership as discussed.

Relax PST membership requirements

---

README.md

- Update community meeting to monthly
- Add agenda link to community meeting
-
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```

correct community meeting freq + add link to agenda

---

peribolos/knative-sandbox.yaml
peribolos/knative.yaml

I am currently working on a serverless workflow service based on knative-eventing and I want be a member of Knative Community. 
List of contributions to the knative:
* [PRs](https://github.com/pulls?q=author%3Axinydev+org%3Aknative-sandbox+org%3Aknative++is%3Apr)
* [Issues](https://github.com/issues?q=author%3Axinydev+org%3Aknative-sandbox+org%3Aknative++is%3Aissue)
-  add xinydev to members list
```release-note
```
**Docs**
```docs
```

Add xinydev to the members list

---

peribolos/knative-sandbox.yaml

- :gift: Add new repo kn-plugin-quickstart under knative-sandbox
part of #603

Add kn-plugin-quickstart repo under knative-sandbox

---

OWNERS_ALIASES
TECH-OVERSIGHT-COMMITTEE.md
knative-sandbox-OWNERS_ALIASES
peribolos/knative-sandbox.yaml
peribolos/knative.yaml

Adding @julz and @dprotaso, congratulations!

Add new TOC members

---

working-groups/security/disclosure.md

This is pretty much a straight (with attribution, obviously) transliteration of Istio's policy (which Im a fan of and seems like a reasonably good fit, at least as a starting point to iterate from).

Add initial disclosure policy based on Istio's

---

REPOSITORY-GUIDELINES.md

- :broom: When removing repos, added a note saying that we should also update documentation so there's no dangling pointers around.
-
-
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```

Add section about updating docs

---

mechanics/FEATURE-TRACKS.md

Fix link to Feature Tracks doc

---

peribolos/knative-sandbox.yaml

@psschwei going to be helping implement the `kn-plugin-quickstart`

add psschwei to knative-sandbox as member org

---

peribolos/knative.yaml

Changing focus in projects. Thanks for all the help and good luck!

Remove nlopezgi from knative owner file

---

peribolos/knative.yaml

Due to my personal switch of focus, I will not be able to actively contribute to the knative project as much as a writer should have. So I am removing myself from the eventing roles.

Remove Jimmy (zhongduo) from knative owner file

---

peribolos/knative.yaml

- Adding myself to the org
Fixes #
```release-note
```
**Docs**
```docs
```

Join knative GH Org

---

peribolos/knative-sandbox.yaml

@dprotaso Filed one in knative too.

Join knative-sandbox organization

---

peribolos/knative-sandbox.yaml

The purpose is to revive aspects of the monitoring bundle - see https://github.com/knative/community/issues/654
cc @upodroid

[repo-request] knative-sandbox/monitoring

---

mechanics/RELEASE-VERSIONING-PRINCIPLES.md

rendered: https://github.com/knative/community/blob/94126f10bafc99e44242986c6495b139ec3d5bdc/mechanics/RELEASE-VERSIONING-PRINCIPLES.md

include 0.24 release in release version table

---

peribolos/knative.yaml

Pre-requisite to #657, as Spencer will need to accept the org invite first.

Add Spencer to Trademark

---

OWNERS_ALIASES
knative-sandbox-OWNERS_ALIASES
mechanics/tools/gen-aliases/main.go

Doing a little cleanup because the banner wasn't clear enough to prevent https://github.com/knative/community/pull/657

Mention source-of-truth location

---

TRADEMARK-COMMITTEE.md

- Updates Spencer to be Google TM committee (follow up from https://github.com/knative/community/pull/657)

Adds Spencer to TM committee

---

peribolos/knative-sandbox.yaml
peribolos/knative.yaml

Signed-off-by: Matthias Wessendorf <mwessend@redhat.com>
- adding me to `knative` and `knative-sandbox`
-
-
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```

Adding myself to the peribolos

---

peribolos/knative-sandbox.yaml
peribolos/knative.yaml

This trips the peribolos updates, see https://prow.knative.dev/view/gs/knative-prow/logs/post-knative-sandbox-peribolos/1412295587008614400

Rename beemarie to bvennam

---

peribolos/knative-sandbox.yaml
peribolos/knative.yaml

Adding `salaboy` to Knative and Knative sandbox members list
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```

Adding salably to members list

---

peribolos/knative-sandbox.yaml

Peribolos test - please ignore

---

peribolos/knative-sandbox.yaml
peribolos/knative.yaml

Add our new contributor & team member to both orgs.
@rhuss can you please confirm that's OK? :)

Add @vyasgun to both orgs

---

OWNERS_ALIASES
knative-sandbox-OWNERS_ALIASES
peribolos/knative-sandbox.yaml

Also rerun ./hack/update-autogen.sh, until Evan gets around to automating it.

Remove test and to-import repo from peribolos

---

peribolos/knative-sandbox.yaml
peribolos/knative.yaml

- adding myself to knative and knative-sandbox
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```

Add Peter Tran to peribolos

---

peribolos/knative-sandbox.yaml

As per title, these have been missed and trip the nightly runs.

Remove stray occurrences of kn-plugin-func

---

peribolos/knative-sandbox.yaml

-
-
-
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```

Add kn-func-plugin to peribolos

---

knative-sandbox-OWNERS_ALIASES

- 🧹  `./hack/update-codegen.sh` (yes, I need to automate this, probably after https://github.com/knative-sandbox/knobots/issues/94)

Regenerate OWNERS_ALIASES for knative-sandbox

---

peribolos/knative-sandbox.yaml
peribolos/knative.yaml
working-groups/WORKING-GROUPS.md

Inspired by #622 and given that I've been doing this for way longer than I had anticipated, I'll make room for other folks to lead the future Eventing efforts by removing myself as an Eventing WG lead.
I also think the timing is great given we're finalizing the 1.0 efforts and it will be a great time for new folks start figuring out what's next after the 1.0.
-
-
-
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```

Remove vaikas as eventing wg lead

---

peribolos/knative-sandbox.yaml

Add kn-plugin-quickstart approve group for peribolos

add kn-plugin-quickstart approvers github team

---

ADOPTERS.MD

Create ADOPTERS.MD file as part of https://github.com/knative/community/issues/648

Creates ADOPTERS.MD file

---

OWNERS_ALIASES
knative-sandbox-OWNERS_ALIASES

Changes:
- 🧹  `./hack/update-codegen.sh`

regen owner_aliases

---

TECH-OVERSIGHT-COMMITTEE.md

As discussed in #626 wanted to put a possible format for TOC for discussion. If this is aok, I'll make these changes elsewhere as well.
-
-
-
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```

Add proposed format for emeritus for TOC

---

STEERING-COMMITTEE.md

Changing @pmorie's organization

Changing @pmorie's organization

---

STEERING-COMMITTEE.md

As per #626 and a format used in #692 (for TOC), create an emeritus for Steering. I tried to reconstruct the history as accurately from the commits, and if I screwed up, my bad, totes unintentional.
- :gift: Give props to previous Steering Committee members in a form of emeritus status.
-
-
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```

add emeritus for SC

---

peribolos/knative.yaml

- Add @psschwei as a serving reviewer
/assign @dprotaso

Add psschwei as a serving reviewer

---

working-groups/WORKING-GROUPS.md

:gift: Add a proposed format for Emeritus WG leads for Eventing and add @grantr and @vaikas to it.
-
-
-
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```

add grantr and vaikas to emeritus WG leads

---

ADOPTERS.MD

Add adopters up to July 23

---

peribolos/knative.yaml

- Removed client-contrib (it has been archived)
- Added client-pkg, following https://github.com/knative/client/issues/1039

Update for client repos

---

peribolos/knative-sandbox.yaml
peribolos/knative.yaml

Make David Simansky a WG lead for the Knative client.
Criteria:
> Recognized as having expertise in the group’s subject matter.
David was the [main contributor to the client repository over the last 6 months](https://docs.google.com/presentation/d/14DkHunyVXuDrM9PLx1XLz5W9z613QWSeZKXRQUcxZw0/edit?usp=sharing).
> Approver for a relevant part of the codebase for at least 3 months.
David is an approver since [March 9th, 2021](https://github.com/knative/client/commit/9fa8d6b96eb035275462e39b51e42762c6acf82b#diff-c393dd2b18a8a597d895940893e574d6895122c4bf3ce6e2a78dbd9ca0cdd66f)
> Member for at least 6 months.
David is a Knative member for over a year.
> Primary reviewer for 20 substantial PRs.
* [is:pr assignee:dsimansk is:closed label:size/M](https://github.com/knative/client/pulls?q=is%3Apr+a …

Make David Simansky a Client WG Lead

---

peribolos/knative.yaml

After removing myself as eventing WG lead, I seem to have lost approver status, which I believe I still should have even if I am not a WG lead.
@lionelvillard @devguyio 
Noticed here: https://github.com/knative/eventing/pull/5601
-
-
-
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```

add vaikas to eventing writers

---

ADOPTERS.MD

Fixes broken link
-
-
-
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```

Fixes broken link in ADOPTERS.MD

---

working-groups/WORKING-GROUPS.md

* Added @sixolet and @cppforlife to the Client WG Emeritus sections
/assign @vaikas

Add emeritus section for the client WG

---

working-groups/WORKING-GROUPS.md

Make dsimansk working group lead in WORKING_GROUPS.md

---

ADOPTERS.MD

- adds adopters up to july 29th

Adds adopters up to jul 29th

---

mechanics/TOC-REVIEW.schedule

:bug: Fix the date format as per #676 comments.
-
-
-
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```

fix date format to what slack wants

---

peribolos/knative-sandbox.yaml

See https://github.com/knative-sandbox/kn-plugin-func/pull/447

Add jrangelramos per kn-plugin-func #447

---

ADOPTERS.MD

:gift: Add KubeSphere and Liquidx
-
-
-
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```

add KubeSphere, Liquidx

---

OWNERS_ALIASES
knative-sandbox-OWNERS_ALIASES

- :bug: Regenerate OWNERS_ALIASES to reflect latest config 
- `./hack/update-codegen.sh`

Regenerate OWNERS_ALIASES to reflect latest config

---

STEERING-COMMITTEE.md

:broom: While working on the SC elections procedure, noticed this dangling link to emeritus committee members.
-
-
-
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```

Fix link to emeritus committee members

---

OWNERS_ALIASES
knative-sandbox-OWNERS_ALIASES
peribolos/knative-sandbox.yaml
peribolos/knative.yaml

- Set @ZhiminXiang and @evankanderson as v0.26 release leads
-
-
Fixes #
```release-note
```
**Docs**
```docs
```

v0.26 release leads 

---

peribolos/knative-sandbox.yaml
peribolos/knative.yaml

Signed-off-by: Ricardo Zanini <zanini@redhat.com>
- Adding myself to knative and knative-sandbox
Fixes #
```release-note
```
**Docs**
```docs
```

Add Ricardo Zanini to peribolos

---

peribolos/knative.yaml

Need to add jberkus as a member as per #734 so that @jberkus can be added as Owner for the SC elections directory.
-
-
-
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```

add jberkus as member

---

working-groups/WORKING-GROUPS.md

Title. For https://github.com/knative/community/issues/709

Add josephburnett as scaling emeritus lead

---

peribolos/knative.yaml

Add `psschwei` as autoscaling reviewer
/assign @markusthoemmes

Add psschwei as autoscaling reviewer

---

peribolos/knative-sandbox.yaml

/assign @vaikas @n3wscott @sbawaska

Add bmo to rabbitmq approvers

---

peribolos/knative-sandbox.yaml

Add eventing-kogito repository to peribolos

---

working-groups/WORKING-GROUPS.md

- Add the Emeritus leads for the operation WG
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```

Add the emeritus leads fo the operation work group

---

peribolos/knative-sandbox.yaml
peribolos/knative.yaml

- Adding myself to the members list of Knative & Knative-sandbox

Adding senthilnathan to members list

---

working-groups/WORKING-GROUPS.md

Added docs (DUX) leads as per https://github.com/knative/community/issues/709

Add docs WG emeritus leads

---

TRADEMARK-COMMITTEE.md

Replacing Brenda w/ Omer
-
-
-
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```

Replacing Brenda w/ Omer on ToC

---

peribolos/knative.yaml

-
-
-
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```

Add nainaz as a member to the knative community

---

peribolos/knative.yaml

Adding @salaboy and myself to Conformance Task Force Leads, adding myself as TM Committee member
-
-
-
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```

Update Conformance, Trademark

---

.github/ISSUE_TEMPLATE/new-repo.md

- :bug: update golang redirect sample PR
-
-
/kind bug
Fixes #
```release-note
```
**Docs**
```docs
```

Fix golang redirect sample PR link

---

STEERING-COMMITTEE.md

Fixes #731 
/hold
Just holding until the discussion in the #731 gets resolved, this is mirroring the plan there so it gets preserved.
-
-
-
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```

Implement 731

---

peribolos/knative-sandbox.yaml

Signed-off-by: Ricardo Zanini <zanini@redhat.com>
We are adding [Kogito Source](https://github.com/knative-sandbox/eventing-kogito) members to peribolos.

Adding Kogito Members to peribolos

---

STEERING-COMMITTEE.md

My last day at VMware was 2021-09-01 so updating my affiliation.
-
-
-
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```

vaikas no longer at VMware

---

STEERING-COMMITTEE.md

Followup to #769 to add @bsnchan to SC Emeritus
-
-
-
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```

Add bsnchan to SC emeritus

---

OWNERS_ALIASES
knative-sandbox-OWNERS_ALIASES

Run the script to update the OWNERS_ALIASES after changes have been made in other PRs.
-
-
-
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```

run the scripts

---

peribolos/knative-sandbox.yaml

Adding `container-fridge` sandbox repo to peribolos

Adding container-freezer repo to peribolos

---

mechanics/RELEASE-VERSIONING-PRINCIPLES.md

Add three more releases to schedule.

---

OWNERS_ALIASES
knative-sandbox-OWNERS_ALIASES
peribolos/knative-sandbox.yaml
peribolos/knative.yaml
working-groups/WORKING-GROUPS.md
working-groups/kafka/CHARTER.md

- Add Eventing Kafka WG charter
- Add Eventing Kafka WG entry in the WORKING-GROUPS.md
Related to: #693

Add Eventing Kafka WG to community section

---

peribolos/knative-sandbox.yaml
peribolos/knative.yaml

Add nealhu @ IBM

---

peribolos/knative.yaml

- Add @nealhu as a serving reviewer

Add nealhu as a serving reviewer

---

elections/2021-SC/README.md

- :bug: Fix Electo link
/kind bug
This is a simple change without typing an issue.

Fix Electo link

---

elections/2021-SC/candidate-csantanapr.md

Add candidate for SC-2021 elections

Add candidate for SC-2021 elections

---

peribolos/knative-sandbox.yaml

Swap in salaboy for eventing-rabbitmq reviewers

---

peribolos/knative-sandbox.yaml

Adding myself as an approver for eventing-kafka-broker
-
-
-
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```

Adding aliok as an approver for eventing-kafka-broker

---

peribolos/knative-sandbox.yaml
peribolos/knative.yaml

Add myself to knative-sandbox & knative members

---

OWNERS_ALIASES
knative-sandbox-OWNERS_ALIASES
peribolos/knative-sandbox.yaml
peribolos/knative.yaml

@nak3 and @matzew get excited 😄

Update release leads for 1.1 release

---

STEERING-COMMITTEE.md

Update affiliations for Ville and Paul

---

peribolos/knative-sandbox.yaml

adding omer and naina as func approvers so we can edit labels

add naina and omer as approvers

---

elections/2021-SC/election.yaml

Also, correct the number of seats open.
/kind bug
/assign @dawn

Fix elections.yaml so that affiliation shows on candidate profiles.

---

elections/2021-SC/election.yaml
elections/2021-SC/voters.yaml

Added @sebgoa to voters.yaml
Fixed date to allow people to file exceptions via Elekto.
@jberkus - if this looks right, can you give it an lgtm?

Voter exceptions

---

elections/2021-SC/candidate-omerbensaadon.md

-------------------------------------------------------------
name: Omer Bensaadon
ID: omerbensaadon
info:
- affiliation: Independent (Github Employee)
-------------------------------------------------------------
* Execution Lead on the GA (1.0) Task Force
* Founded the User Experience Working Group w/ @csantana
* Led merging of Documentation and User Experience Working Groups
* Conducted interviews of ~30 end-users of Knative
* Led revamp of the Knative Website
* Authored the Knative Getting Started Guide
* Active member of the Knative Trademark Committee
* Introduced product practices, refinement, to many Knative processes (Roadmaps, namely)
* Product leadership on Knative Functions
* Helped connect end-users to Knative contributors (feedback, case study participants, ADOPTERS.MD)
* …

Adding omerbensaadon's candidacy

---

elections/2021-SC/candidate-itsmurugappan.md

Filing my nomination for sc seat
At Optum, I have been instrumental in adopting Knative at an early stage and making it into a preferred 
platform for developers to deploy apps. We were able to achieve this by consistently 
engaging with the Knative community, sharing our feedback and raising issues/pull requests. 
Knative has just become GA and has a long way to go. I want to be part of this journey and provide 
an end user perspective to the future road maps and encourage more active participation of end users.

adding murugappan as candidate for sc

---

elections/2021-SC/candidate-xtreme-sameer-vohra.md

-  add myself as a candidate for Steering Election

Add myself as a candidate for Steering Election

---

elections/2021-SC/README.md

fixed several links and corrected a mistake in the voter exception deadline in the text to match what we have in the table.

fixed several links and corrected a mistake in the voter exception deadline

---

peribolos/knative-sandbox.yaml

My reviews: 
- https://github.com/knative-sandbox/eventing-kafka/pulls?q=is%3Apr+is%3Aopen+reviewed-by%3Apierdipi
- https://github.com/knative/eventing-contrib/pulls?q=is%3Apr+is%3Aopen+reviewed-by%3Apierdipi
/cc matzew devguyio aliok travis-minke-sap lionelvillard eric-sap

Add pierDipi to eventing-kafka approvers

---

peribolos/knative.yaml

- add `nader-ziada` as reviewer for serving and scaling

add nader-ziada as reviewer for serving and scaling

---

README.md

- :bug: Fix incorrect pointer to CALENDAR.md => CALENDAR.MD
-
-
-
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```

fix the filename

---

ADOPTERS.MD

Add Control Plane to Adopters
- Add Control Plane to Adopters
Fixes #
```release-note
```
**Docs**
```docs
```

Add Control Plane to Adopters

---

OWNERS_ALIASES
knative-sandbox-OWNERS_ALIASES
peribolos/knative.yaml
working-groups/WORKING-GROUPS.md

Fixup #803, needed rebase and codegen

Add snneji as Docs + UX WG lead

---

elections/2021-SC/voters.yaml

Approved exception requests for @thisisnotapril , @nader-ziada, and @nainaz for voting in the SC election.
@jberkus I added them to the voters.md file, but before we merge this, I wanted to make sure that this is what Elekto expects. 
/assign @jberkus

approved exception requests for SC election voting

---

elections/2021-SC/voters.yaml

This a pull request for my exception based on my work as a Knative election officer. I also now have over 50 contributions in devstats, but I was just under the limit when we ran the numbers before kicking off the election.
This was approved offline by @vaikas and @jberkus, so I'll defer to one of them to merge this.
The deadline for exceptions was Nov 19, so this is the last exception to be merged.

final exception for SC election

---

working-groups/WORKING-GROUPS.md

-
-
-
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```

Update Eventing Sources WG meeting date

---

mechanics/RELEASE-VERSIONING-PRINCIPLES.md

Fixes: https://github.com/knative/community/issues/827

Update our min K8s version principle to exclude releases in maintenance mode

---

ADOPTERS.MD

- :bug: Fix bug
Update the Knative on Alibaba Cloud website
```

Update the Knative on Alibaba Cloud website

---

elections/2021-SC/ballots.csv
elections/2021-SC/results.md

Add election results for 2021 SC

---

mechanics/ROADMAPS.md

Fixes #746
/assign @csantanapr

Document roadmap process

---

OWNERS_ALIASES
STEERING-COMMITTEE.md
knative-sandbox-OWNERS_ALIASES
peribolos/knative-sandbox.yaml
peribolos/knative.yaml

Congratulations @csantanapr and @lance!!!
Also move @mbehrendt to Emeritus Committee Members, thank you for your
service!!!
- Add @csantanapr @lance to Steering Committee as per election results.
- Move @mbehrendt to Emeritus Committee Members
-
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```

Update Steering Committee with the newly elected members

---

peribolos/knative-sandbox.yaml
peribolos/knative.yaml

looking forward to getting more involved :)
cc @pierDipi

Add Shashankft9 to knative and knative-sandbox members

---

OWNERS_ALIASES
peribolos/knative.yaml

Include myself as a productivity reviewer

---

OWNERS_ALIASES
knative-sandbox-OWNERS_ALIASES
peribolos/knative-sandbox.yaml
peribolos/knative.yaml
working-groups/WORKING-GROUPS.md

removing Omer from WG Leads :(

Omer stepping down from DUX 

---

google-summer-of-code/README.md
google-summer-of-code/gsoc-2022.md

Fixes #867
- :gift: Add GSoC information pages. Only information that's necessary at this stage.
- Created `google-summer-of-code` directory
- Created 2 files.
- README.md contains generic information about GSoC independent from the year.
- gsoc-2022.md contains specific information about GSOC 22 at Knative.
/kind <kind>

Add GSoC information pages

---

OWNERS_ALIASES
knative-sandbox-OWNERS_ALIASES
peribolos/knative-sandbox.yaml
peribolos/knative.yaml
working-groups/WORKING-GROUPS.md

Stepping down from Productivity WG.
/kind cleanup
/kind removal

Scott stepping down from Productivity WG

---

elections/2021-SC-EU/enduser.md
elections/2021-SC-EU/nomination-template.md
elections/2021-SC/README.md
elections/2021-SC/enduser.md

Start putting down what the process for End User seat appointment is. Timelines I put placeholders.
@jberkus should we use a different directory for this as to not mess with the existing ones? Thoughts?
-
-
-
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```

End user seat proposal.

---

OWNERS_ALIASES
TECH-OVERSIGHT-COMMITTEE.md
knative-sandbox-OWNERS_ALIASES
peribolos/knative-sandbox.yaml
peribolos/knative.yaml

As announced in https://groups.google.com/g/knative-dev/c/gA3matxzBH4. Thanks for all the trust!

Markus steps down from TOC

---

elections/2021-SC-EU/enduser.md

-
-
-
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```

Fix Contributor seat => End User Seat.

---

ADOPTERS.MD

fix the incorrect project name: Open Functions => OpenFunction
Fixes #
```release-note
```
**Docs**
```docs
https://github.com/knative/community/blob/main/ADOPTERS.MD
```

fix the incorrect project name

---

OWNERS_ALIASES
knative-sandbox-OWNERS_ALIASES
peribolos/knative-sandbox.yaml
peribolos/knative.yaml

As per title.
/cc @dprotaso @psschwei @matzew 
The next release leads are Dave & Paul as per https://github.com/knative/release#schedule

Update release leads for 1.2 release

---

ADOPTERS.MD

- 🎁  Add SAP Event Mesh to adopters list
- 🧹  Fix pre-existing whitespace alignment
Previously commented on Issue #696 but not automated updates occurred - was directed to create a PR ; )
**Docs**

Add SAP Event Mesh to ADOPTERS

---

TECH-OVERSIGHT-COMMITTEE.md

After @markusthoemmes stepped down, we followed the process for replacement for the remainder of the term and @n3wscott graciously offered to step up to the challenge.
-
-
-
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```

Add @n3wscott to TOC.

---

CODE-OF-CONDUCT.md

Fixes #876 
/assign @vaikas @pmorie @lance @thisisnotapril

update coc for SC to be responsible.

---

OWNERS_ALIASES
peribolos/knative.yaml

Add skonto as reviewer for Serving API & Autoscaling

---

elections/2021-SC-EU/candidate-itsmurugappan.md

Adding my nomination for end-user SC seat

Add murugappan nominaton for end user sc seat

---

ADOPTERS.MD

-
-
-
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```

Add Bloomberg L.P. as adopter

---

knative-sandbox-OWNERS_ALIASES
peribolos/knative-sandbox.yaml

cc @benmoss @xtreme-sameer-vohra

Add Iliia Khaprov (VMware) as approver for eventing-rabbitmq

---

elections/2021-SC-EU/README.md

Update the link to ADOPTER.MD in the SC End User Election README
- bug: Update the link pointing to ADOPTERS.MD in the SC End User Rep. election README 

Update the link to ADOPTERS.MD in the SC end user election README

---

peribolos/knative-sandbox.yaml
peribolos/knative.yaml

Add gab-satchi to knative and knative-sandbox

---

knative-sandbox-OWNERS_ALIASES
peribolos/knative-sandbox.yaml
peribolos/knative.yaml

Adding myself as a member and approvers for eventing rabbitmq.
cc @xtreme-sameer-vohra

Add chunyilyu

---

OWNERS_ALIASES
knative-sandbox-OWNERS_ALIASES
peribolos/knative-sandbox.yaml
peribolos/knative.yaml

Per [last week's TOC meeting](https://drive.google.com/file/d/1x7EL8MtCdFpbxUSpYg8DeRrrr3RrvL1a/view?t=9m30s), I've met the requirements to be an approver for the Productivity working group. I'm happy to review and approve PRs, mentor new contributors, and the other responsibilities required of an approver.
/assign @chizhg

Add psschwei to productivity writers

---

OWNERS_ALIASES
knative-sandbox-OWNERS_ALIASES
peribolos/knative-sandbox.yaml
peribolos/knative.yaml

Updates release leads for 1.3
/cc @carlisia @xtreme-sameer-vohra @dprotaso

update release leads for 1.3

---

OWNERS_ALIASES
STEERING-COMMITTEE.md
knative-sandbox-OWNERS_ALIASES
peribolos/knative-sandbox.yaml
peribolos/knative.yaml

Add Murugappan to steering

---

working-groups/WORKING-GROUPS.md

To be able to focus on other Knative-related activities...
/cc @travis-minke-sap @devguyio

Lionel stepping down from Eventing Kafka WG

---

STEERING-COMMITTEE.md

Related #917 
This update covers 2 points from the issue
- Reflects that now we have End User representation by indicating which member holds the seat
- How are elections for End User seat

Update EU seat

---

STEERING-COMMITTEE.md

fix typo steering

---

OWNERS_ALIASES
peribolos/knative.yaml

- Maximilien has reviewed almost every operator PR for the past 10 months. I proposed to add him as the operator writer.
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```

Add Maximilien as the reviewer and writer of operator

---

peribolos/knative.yaml

- :gift: Add `infra` repo
- :wastebasket: Remove the defunt homepage from `test-infra` (https://github.com/knative/test-infra/pull/3098)
- :broom: Disable projects on `test-infra` (project is on the org level)
Part of https://github.com/knative/community/issues/932

Add `infra` repo

---

BRANDING.MD
logo-guidelines.pdf

Scott Nichols noticed at the TOC meeting today that the logo colors on the website were off. We should include the details of the logo in the branding guidelines.

Copy logo PDF guidelines, including font and color guides, into the community branding guidelines.

---

OWNERS_ALIASES
knative-sandbox-OWNERS_ALIASES
peribolos/knative-sandbox.yaml
peribolos/knative.yaml

Remove sources-wg-lead as the sources WG is merged back to the Eventing WG

---

peribolos/knative.yaml

Part of: https://github.com/knative/community/issues/949
Grants Productivity writers `write` access
Grants Admins (TOC,Steering Release Leads) `admin` access

add knative/actions repo

---

OWNERS_ALIASES
knative-sandbox-OWNERS_ALIASES
peribolos/knative-sandbox.yaml
peribolos/knative.yaml

Pablo Mercado (@odacremolbap) has fulfilled the approver criteria and the Eventing WG would love to nominate him. He's done a great job pushing Eventing across the 1.0 finish line, performing very thorough code review for large and complex PRs and participating in community contact rotation and regular WG calls.

Add Pablo Mercado (@odacremolbap) as Eventing approver

---

knative-sandbox-OWNERS_ALIASES
peribolos/knative-sandbox.yaml

Add myself as a member in knative-sandbox and as approver for net-{istio, kourier} to help with new features review for example [encryption work](https://github.com/knative-sandbox/net-kourier/pull/761).
/cc @nak3 @rhuss

Add skonto in sandbox 

---

google-summer-of-code/README.md

- Clean up obsolete info about GSoC
-
-
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```

Clean up obsolete info about GSoC - 2

---

knative-sandbox-OWNERS_ALIASES
peribolos/knative-sandbox.yaml

Add gab-satchi to eventing-rabbitmq approvers

Add gab-satchi to eventing-rabbitmq approvers

---

OWNERS_ALIASES
knative-sandbox-OWNERS_ALIASES
peribolos/knative-sandbox.yaml
peribolos/knative.yaml

c/c 
@nader-ziada
@ikvmw
Please ack handoff and thank you!

Update release leads for v1.4

---

logo-guidelines.pdf

/assign @smoser-ibm @csantanapr

Fix logo guidelines; accidentally committed HTML

---

groups/committee-steering/groups.yaml

Dave was asking questions about these groups files, and they didn't really make sense to me, so I figured I'd do a quick cleanup pass (and I don't have approval for this directory).

Clean up steering GSuite memberships

---

OWNERS_ALIASES
knative-sandbox-OWNERS_ALIASES
peribolos/knative-sandbox.yaml
peribolos/knative.yaml
working-groups/WORKING-GROUPS.md

As discussed during March 31st TOC meeting.
/cc @n3wscott @pierDipi

Add pierdipi as Eventing WG lead

---

STEERING-COMMITTEE.md

Fix the link to ADOPTERS file.
- 🐛  Fix incorrect link to ADOPTERS.md file from SC readme.
- 🗑️ Remove SC transition block as transition has been already done.
-
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```

Remove the transition block, since we have already transitioned to community elected SC.

---

ADOPTERS.MD
STEERING-COMMITTEE.md
elections/2021-SC-EU/README.md

Clarify end user appointment, vacancy and companies

---

OWNERS_ALIASES
knative-sandbox-OWNERS_ALIASES
peribolos/knative-sandbox.yaml
peribolos/knative.yaml

To fix the error in https://github.com/knative-sandbox/knobots/pull/181#issuecomment-1091920766
/cc @dprotaso

Add knative-automation bot account as the admin

---

peribolos/knative-OWNERS_ALIASES
peribolos/knative-sandbox-OWNERS_ALIASES
peribolos/knative-sandbox.yaml
peribolos/knative.yaml

- 🧹 Remove vaikas from eventing-writers
-
-
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```

remove vaikas from eventing-writers

---

groups/OWNERS
groups/groups_test.go
groups/wg-productivity/groups.yaml
peribolos/knative-OWNERS_ALIASES
peribolos/knative-sandbox-OWNERS_ALIASES
peribolos/knative-sandbox.yaml
peribolos/knative.yaml
working-groups/WORKING-GROUPS.md

As discussed during April 7th TOC meeting.
/cc @dprotaso @kvmware

Nominate Krsna as the productivity WG lead

---

label_sync/README.md
label_sync/labels.yaml

Adds the label.yaml config for the label_sync job to community repo.

Add label_sync prow job config

---

peribolos/knative-sandbox.yaml

This repo hasn't been used at all

drop build-spike repo

---

OWNERS

Forgot to remove the filter in https://github.com/knative/community/pull/1008

drop filter since it applies only to labelling

---

peribolos/knative.yaml

See https://knative.slack.com/archives/CCSNR4FCH/p1650581831685649?thread_ts=1649809077.370369&cid=CCSNR4FCH

Add hh to Knative GitHub Org as a Member

---

groups/groups_test.go
groups/wg-productivity/groups.yaml

See: https://knative.slack.com/archives/CCSNR4FCH/p1650580357657709?thread_ts=1649809077.370369&cid=CCSNR4FCH

Add hh@cncf.io to kn-infra-gcp-org-admins

---

groups/groups_test.go
peribolos/knative-sandbox.yaml
peribolos/knative.yaml

See https://knative.slack.com/archives/CCSNR4FCH/p1650581849509699?thread_ts=1649809077.370369&cid=CCSNR4FCH

Add hh to Knative-Sandbox GitHub Org as a member

---

peribolos/knative-sandbox.yaml
peribolos/knative.yaml

Apart of the CNCF Community infrastructure team. Separately also interested in contributing to serving / UX / cli.
Contributions:
- https://github.com/knative-sandbox/net-contour/pull/735
Test-infra:
- https://github.com/knative/test-infra/issues/3134#issuecomment-1110333520
https://knative.slack.com/archives/CCSNR4FCH/p1651010192670879?thread_ts=1651010158.667779&cid=CCSNR4FCH

Add BobyMCbobs to knative and knative-sandbox orgs

---

peribolos/knative-OWNERS_ALIASES
peribolos/knative-sandbox-OWNERS_ALIASES
peribolos/knative-sandbox.yaml
peribolos/knative.yaml

Seems this was missed when I joined the TOC

Adding n3wscott to TOC paribolos files

---

ADOPTERS.MD

- Adds HighCohesion details to Adopters document

Adds HighCohesion details to Adopter doc

---

peribolos/knative-sandbox-OWNERS_ALIASES
peribolos/knative-sandbox.yaml

Signed-off-by: Paul S. Schweigert <paulschw@us.ibm.com>
/assign @maximilien

Add Paul to kperf approvers

---

elections/2022-TOC/candidate-skonto.md

Hello all, I am Stavros Kontopoulos!
I have been working on the Knative project in various areas for two years now.
I spend my time on Knative Serving but also on cross-cutting concerns like observability, networking etc.
I am also interested in making users successful with Knative thus I have contributed in different aspects such as
debugging issues, reviewing PRs, adding documentation and features. 
I would like to see the project becoming even more successful and I am interested a lot in helping
to that direction eg. grow our community. I feel there is space for improvement for the many sub-projects we maintain to make Knative the best solution for Cloud Native application development.
Giving a shot! :)

Adding skonto as 2022 TOC candidate

---

elections/2022-TOC/candidate-zroubalik.md

Hi, I am Zbynek Roubalik (Zbyněk Roubalík if you fancy Czech diacritics). 
My main focus have been around Functions on Knative, ie. some initial not so successful attempts, then Boson project, that later became Knative Sandbox project (`func` kn plugin) and is now on it's way to become a full-fledged Working Group, yay!
The other area of my interest is around KEDA & Knative integration, which initally enabled autoscaling of a few Eventing Sources
and has a great potential to be expanded even more. This really makes even the Knative infrastructure serverless.
I think that I am able to openly to listen to other peoples thoughts/ideas and I'd define myself as result driven - I just love seeing getting things done.
I am also a maintainer of another CNCF project - KEDA, which is fairly smaller …

Add Zbynek as TOC candidate

---

elections/2022-TOC/candidate-msalatino.md

Hi everyone! 
My name is Mauricio Salatino (aka salaboy), I am working for VMware full time on the Knative OSS project. 
I would like to apply for candidacy as I am interested in growing the Knative community and keep driving new initiatives to cover new use cases, such as workflows, streaming and an improved functions experience. 
If you want to support my candidacy please add a comment here in the PR.

Add msalatino (salaboy) as a TOC candidate

---

peribolos/knative-sandbox-OWNERS_ALIASES
peribolos/knative-sandbox.yaml

Now that the async-component is in Beta and may get some more helping hands with the upcoming KnativeCon talk I think adding myself as approver for the async-component makes sense 🎉

add myself as async-component approver

---

elections/2022-TOC/candidate-psschwei.md

Signed-off-by: Paul S. Schweigert <paulschw@us.ibm.com>

Update Paul's candidate profile

---

groups/groups.yaml

allow emails for calendar-maintainers group

---

working-groups/WORKING-GROUPS.md

[Preview](https://github.com/knative/community/blob/878974811916d96bc93b77150f64a7e7cbaee24c/working-groups/WORKING-GROUPS.md)

update serving and networking meeting details

---

elections/2022-TOC/voters.yaml

Approved @aslom as an eligible voter.

adding exception to voters.yaml

---

groups/groups.yaml

I guess this is the way to get access to the Knative calendar to edit/create events.

Add pierdipi to wg-leads

---

peribolos/knative-sandbox-OWNERS_ALIASES
peribolos/knative-sandbox.yaml

- adding `nader-ziada` as an approver for the `knative-sandbox/kperf` repo
- added the scale command to kperf
- working on enhancing the perf testing in serving
/cc @maximilien @dprotaso

add nader ziada as approver for sandbox/kperf

---

peribolos/knative-sandbox-OWNERS_ALIASES
peribolos/knative-sandbox.yaml

Adding myself as approver to  the rest of the `net-*` repos where I'm not.

Add Carlisia as approver

---

label_sync/OWNERS
label_sync/labels.yaml

I need some labels to prioritise some work and few area specific labels for test-infra
/cc @dprotaso @kvmware

Add GH Labels

---

peribolos/knative-OWNERS_ALIASES
peribolos/knative-sandbox-OWNERS_ALIASES
peribolos/knative-sandbox.yaml
peribolos/knative.yaml

Signed-off-by: Paul S. Schweigert <paulschw@us.ibm.com>

Update release leads for v1.6

---

peribolos/knative-OWNERS_ALIASES
peribolos/knative.yaml

Allow Productivity WG leads to manage repos

Add productivity wg leads as repo admins

---

groups/committee-oversight/groups.yaml
peribolos/knative-OWNERS_ALIASES
peribolos/knative-sandbox-OWNERS_ALIASES
peribolos/knative-sandbox.yaml
peribolos/knative.yaml

- adding @dsimansk and @zroubalik to TOC members
- also removing @rhuss  :(

Update TOC members: add dsimansk and zroubalik

---

peribolos/knative-OWNERS_ALIASES
peribolos/knative-sandbox-OWNERS_ALIASES
peribolos/knative-sandbox.yaml
peribolos/knative.yaml
working-groups/WORKING-GROUPS.md

Nominating [Ashleigh Brennan](https://github.com/abrennan89) as Working Group Lead
- Already an approver for Docs
- Review PRs for Docs
- Contributing content for Docs
- Contributing to design and direction for information architecture
- Helping triage and label issues
/hold

Nominate Ashleigh Brennan as DUX Working Group Lead

---

peribolos/knative-OWNERS_ALIASES
peribolos/knative.yaml

Update productivity for knative-admins

---

mechanics/TOC-REVIEW.schedule

DUX WG requesting an extension to present to TOC

shift WG updates by a week by request from DUX WG

---

peribolos/knative-OWNERS_ALIASES
peribolos/knative-sandbox-OWNERS_ALIASES
peribolos/knative-sandbox.yaml
peribolos/knative.yaml

chizhg steps down from Productivity WG lead and leaves Knative

---

peribolos/knative-sandbox.yaml
peribolos/knative.yaml

I'd like to become a member of knative-sandbox and knative.
I am actively contributing on net-kourier and knative serving repo.
Please see:
https://github.com/knative/serving/pull/13061
https://github.com/knative/serving/pull/13077
https://github.com/knative-sandbox/net-kourier/pull/866

Add xxinran to Knative and Knative Sandbox member

---

peribolos/knative-sandbox-OWNERS_ALIASES
peribolos/knative-sandbox.yaml

Add myself as approver for net-istio.
I've been helping to maintain net-istio, including keeping manifests updated https://github.com/knative-sandbox/net-istio/pulls?q=is%3Apr+is%3Aclosed+author%3AAngeloDanducci
As well as reviews
https://github.com/knative-sandbox/net-istio/pull/920
/cc @nak3

add myself to net-istio approvers

---

STEERING-COMMITTEE.md

Fixed a link to Elekto and changed links to previous elections to point to the elections folder to avoid having to change those links every year.
/assign @csantanapr @vaikas

Fixed / updated a few links

---

peribolos/knative-sandbox.yaml
peribolos/knative.yaml

I'd like to become a member of knative-sandbox and knative.
I'm interested in Knative-eventing, the following PR of mine have been merged:
https://github.com/knative/eventing/pull/6433
https://github.com/knative/eventing/pull/6424

add Teresaliu as a member

---

mechanics/TOC-REVIEW.schedule

Push back Serving WG update

---

peribolos/knative-sandbox.yaml
peribolos/knative.yaml

I am beginning contributions to the productivity working group

Please add kellyaa as a member

---

peribolos/knative-sandbox.yaml
peribolos/knative.yaml

This patch applies for adding me(@chzhyang) to knative and knative-sandbox members.
I am actively contributing on kperf repo and has already several commits, please see:
https://github.com/knative-sandbox/kperf/commits?author=chzhyang
https://github.com/knative-sandbox/kperf/issues/250#issue-1288217076
I will continue to contribute to knative community in the future.

please add chzhyang as a member

---

peribolos/knative-sandbox.yaml
peribolos/knative.yaml

Add member to knative.yaml and knative-sandbox.yaml
Contributing to serving via the security WG

Davidhadas add member

---

peribolos/knative-sandbox.yaml
peribolos/knative.yaml

I'd like to become a member of knative-sandbox and knative.
I'm interested in Knative-eventing, the following PR of mine have been merged:
https://github.com/knative/eventing/pull/6433
https://github.com/knative/eventing/pull/6424
In this PR, I've updated my github ID

add liuchangyan as a member

---

peribolos/knative-sandbox.yaml
peribolos/knative.yaml

Problems in our peribolos config found by new tool I wrote.

fixup peribolos *.ymls

---

.github/workflows/peribolos-schema-validate.yaml
peribolos/validate-schema.py

This will catch errors that our current presubmit job doesn't without blowing up when adding a team. Additionally, this is a 10s run process vs the current 3min job.

Add peribolos schema validation workflow

---

STEERING-COMMITTEE.md

Update Carlos' Org in steering

Update Carlos' Org in steering

---

TECH-OVERSIGHT-COMMITTEE.md

- Scott is not affiliated with a company.
```release-note
NONE
```

Update Scotts company affiliation

---

peribolos/knative-OWNERS_ALIASES
peribolos/knative-sandbox-OWNERS_ALIASES
peribolos/knative-sandbox.yaml
peribolos/knative.yaml
working-groups/WORKING-GROUPS.md

I'm stepping down as DUX WG lead and will continue contributions to Knative via steering.
/assign @evankanderson @dprotaso

csantanapr step down as dux wg lead

---

peribolos/knative-sandbox-OWNERS_ALIASES
peribolos/knative-sandbox.yaml

Adding myself as member of kn-plugin-func

Add jrangelramos to kn-plugin-func approvers

---

mechanics/RELEASE-SCHEDULE.md
mechanics/RELEASE-VERSIONING-PRINCIPLES.md

Fixes knative/community#1096
- :broom: Quarterly release cadence

:broom: Quarterly release cadence

---

groups/committee-steering/groups.yaml

-
-
-
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```

Add non knative.team addresses to steering folks.

---

peribolos/knative-sandbox.yaml
peribolos/knative.yaml

Signed-off-by: jwcesign <jiangwei115@huawei.com>
* worked with sandbox project `container-freezer`.
* Solve some issues.
* Some bug fix for knative/serving.

Add jwcesign as a knative/knative sandbox member

---

groups/committee-steering/groups.yaml

🐛 Emails sent to steering are bouncing. This makes the list publicly postable.
@evankanderson 
@csantanapr 
-
-
-
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```

make steering world postable. Fix description.

---

TECH-OVERSIGHT-COMMITTEE.md
peribolos/knative-OWNERS_ALIASES
peribolos/knative-sandbox-OWNERS_ALIASES
peribolos/knative-sandbox.yaml
peribolos/knative.yaml

Scott stepping down from ToC

---

TECH-OVERSIGHT-COMMITTEE.md
groups/committee-oversight/groups.yaml
groups/groups.yaml
groups/wg-productivity/groups.yaml
peribolos/knative-OWNERS_ALIASES
peribolos/knative-sandbox-OWNERS_ALIASES
peribolos/knative-sandbox.yaml
peribolos/knative.yaml

Filling Scott's seat, xref #1167

update TOC members: add psschwei

---

peribolos/knative-OWNERS_ALIASES
peribolos/knative-sandbox-OWNERS_ALIASES
peribolos/knative-sandbox.yaml
peribolos/knative.yaml

Update release leads for 1.8

---

groups/committee-steering/groups.yaml

cc: @csantanapr @vaikas @upodroid @jberkus

added Mahamed Ali to our elections officer email group

---

working-groups/WORKING-GROUPS.md

A few of the WG meeting times were out of date.
FYI
Client: @dsimansk @rhuss 
Security: @evankanderson 
Docs: @abrennan89 @snneji

Update security, docs, client WG times

---

STEERING-COMMITTEE.md
mechanics/SC.md

update SC doc it stated that end-user seat eligibility was in progress, I made updates to clarify

clarify end user in SC mechanic

---

ADOPTERS.MD

-
-
-
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```

Chainguard uses Knative in production.

---

mechanics/RELEASE-SCHEDULE.md

Update release schedule after 1.8 release

---

peribolos/knative-OWNERS_ALIASES
peribolos/knative-sandbox-OWNERS_ALIASES
peribolos/knative-sandbox.yaml
peribolos/knative.yaml
working-groups/WORKING-GROUPS.md

nak3 stepping down from Networking WG

---

peribolos/knative-OWNERS_ALIASES
peribolos/knative-sandbox-OWNERS_ALIASES
peribolos/knative-sandbox.yaml
peribolos/knative.yaml
working-groups/WORKING-GROUPS.md

Lionel stepping down as eventing lead

---

elections/2022-SC/OWNERS
elections/2022-SC/candidate-salaboy.md

I fixed a typo in @salaboy's entry from #1193 
/cc @geekygirldawn @jberkus 
/hold

Fix salaboy's entry

---

peribolos/knative-OWNERS_ALIASES
peribolos/knative-sandbox-OWNERS_ALIASES
peribolos/knative-sandbox.yaml
peribolos/knative.yaml

https://github.com/knative/community/pull/1192 follow-up.
/cc @pierDipi

Add lionel as eventing writer

---

elections/2022-SC/voters.yaml

Adding voters who requested exceptions to the 2022 SC Election
I'll keep adding people whose requests have been accepted. I will merge the PR after the deadline has passed (28th of Nov).
/hold

Voter exceptions for 2022 SC Election

---

elections/2022-SC/voters.yaml

Voter exceptions for 2022 SC Election - II

---

elections/2022-SC/candidate-aslom.md

-
-
-
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```

Add self nomination for 2022 SC election

---

elections/2022-SC/candidate-smoser-ibm.md

-
-
-
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```

SC 2022 self nomination for candidate smoser-ibm.md

---

peribolos/knative-sandbox.yaml
peribolos/knative.yaml

This PR adds the GH user ID 'norman465' (working on IBM Cloud Code Engine) to the knative and knative-sandbox projects member list.

Add member norman465

---

elections/2022-SC/candidate-nainaz.md

-
-
-
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```

Adding Naina Singh candidancy profile for SC elections

---

mechanics/TOC-REVIEW.schedule

Updated the @knative/technical-oversight-committee review schedule to account for the upcoming holidays.

Update TOC Review Schedule

---

peribolos/knative-sandbox-OWNERS_ALIASES
peribolos/knative-sandbox.yaml

Adding `scaling-group` sandbox repo to peribolos
Part of https://github.com/knative/community/issues/1195

Adding scaling-group repo to peribolos

---

elections/2022-SC/voters.yaml

Changing case of @pierDipi's gh handle in voters.yaml to see if that solves the issue with eligibility in Elekto

Fixing pierDipi's eligibility in voters.yaml

---

peribolos/knative-OWNERS_ALIASES
peribolos/knative-sandbox-OWNERS_ALIASES
peribolos/knative-sandbox.yaml
peribolos/knative.yaml

As per https://github.com/knative/release#release-schedule-for-2023
cc @lionelvillard @nak3 @evankanderson

Update release leads for v1.9

---

peribolos/knative-sandbox.yaml
peribolos/knative.yaml

Adding myself as a knative and knative-sandbox member so I don't have to wait for the `ok-to-test` labels.
Contributions so far:
* [knative/docs](https://github.com/knative/docs/issues?q=author%3Acreydr)
* [knative/eventing](https://github.com/knative/eventing/issues?q=author%3Acreydr)

Add creydr as a knative and knative-sandbox member

---

peribolos/knative-sandbox.yaml
peribolos/knative.yaml

Adds myself github user ID 'izabelacg' to the knative and knative-sandbox projects member list.

Add member izabelacg

---

STEERING-COMMITTEE.md
groups/committee-steering/groups.yaml
groups/groups.yaml
peribolos/knative-OWNERS_ALIASES
peribolos/knative-sandbox-OWNERS_ALIASES
peribolos/knative-sandbox.yaml
peribolos/knative.yaml

add new steering members

---

elections/2022-SC-EU/README.md
elections/2022-SC-EU/nomination-template.md

Added 2022-SC-EU folder for End User Seat Election on Steering Committee for 2022
-
-
-
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```

Added 2022-SC-EU folder

---

peribolos/knative-sandbox-OWNERS_ALIASES
peribolos/knative-sandbox.yaml

Adds peribolos entries for the proposed repository knative-sandbox/func-go
See: https://github.com/knative/community/issues/1220
/kind proposal

proposal(func-go): adds knative-sandbox/func-go

---

elections/2022-SC-EU/README.md

-
-
-
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```

Changed SC-EU-Seat annoucment date to Dec 16

---

google-summer-of-code/gsoc-2023.md

Adding gsoc idea for kne observability

---

peribolos/knative-sandbox.yaml
peribolos/knative.yaml

Add myself to the list of community members in `knative.yaml` and `knative-sandbox.yaml`.

Add myself to knative community members

---

peribolos/knative-sandbox.yaml
peribolos/knative.yaml

Addin myself to the Knative community members list

Add myself to the community

---

peribolos/knative-sandbox.yaml

-
-
-
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```

Remove albertomilan from knative groups

---

groups/wg-productivity/groups.yaml

/cc @dprotaso 
This should give you sufficient privileges to troubleshoot.

Add dave to privileged infra group

---

peribolos/knative-sandbox.yaml

Part of https://github.com/knative/community/issues/1239

Add knative-sandbox/eventing-istio

---

google-summer-of-code/gsoc-2023.md

- As CNCF now initiated their GSoC program and created their [ideas page](https://github.com/cncf/mentoring/blob/main/summerofcode/2023.md), we don't have to collect Knative ideas here
- Added GSoC guide for mentors and contributors (copy & paste & update from 2022 doc for now - I might create a separate doc for the guides later)
-
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```

Remove GSoC ideas list, add GSoC guides

---

SLACK-GUIDELINES.md
google-summer-of-code/gsoc-2022.md
google-summer-of-code/gsoc-2023.md
working-groups/WORKING-GROUPS.md

Signed-off-by: Vishal Choudhary <sendtovishalchoudhary@gmail.com>
Adds slack links to the newly created CNCF Knative slack channel

Adds slack links to CNCF Knative slack channel

---

mechanics/TOC-REVIEW.schedule

chore: update WG presentation schedule

---

peribolos/knative-sandbox.yaml
peribolos/knative.yaml

Add myself to the list of community members in knative.yaml and knative-sandbox.yaml.

Working at VMware and will contribute to Knative

---

peribolos/knative-OWNERS_ALIASES
peribolos/knative.yaml

- Add @jrangelramos to func-writer group.

add: jrangelramos to func-writer group

---

peribolos/knative-sandbox.yaml
peribolos/knative.yaml

Adding a new repository per issue https://github.com/knative/community/issues/1258.
Hold for TOC approval. 
/hold

Add knative/.artifacthub repository

---

groups/wg-productivity/groups.yaml

Reverts knative/community#1243
@psschwei This should fix the failing presubmit.

Revert "Add dave to privileged infra group"

---

mechanics/tools/gen-aliases/main.go

- :broom: The output of ./hack/update-codegen.sh prints ```No changes to 'filename'``` if it doesn't update peribolos.
/kind cleanup
Fixes #1238

Fixing output if ./hack/update-codegen.sh doesn't update

---

peribolos/knative-sandbox-OWNERS_ALIASES
peribolos/knative-sandbox.yaml

chzhyang is still working on contributing to kperf.
recent PRs to kperf:
- https://github.com/knative-sandbox/kperf/pull/338
- https://github.com/knative-sandbox/kperf/pull/311
- https://github.com/knative-sandbox/kperf/pull/305
- https://github.com/knative-sandbox/kperf/pull/292
- ...
@psschwei

re-add chzhyang to knative-snadbox/kperf approvers

---

groups/reconcile.go
mechanics/tools/gen-aliases/main.go

- :broom: Change deprecated functions for reading and writing a file
- 🗑️ Remove ```io/ioutil``` import
/kind cleanup
Fixes #1278

Changing deprecated functions in ./hack/update-codegen.sh

---

groups/committee-steering/groups.yaml

- :gift: adding @puerco to mailing list for steering committee
-
-
-
Fixes #1265
```release-note
```
**Docs**
```docs
```

Adding @puerco to streering mailing list

---

groups/groups.yaml

- :gift: adding @puerco to calendar maintainers group
Partially addresses #1265
```release-note
```
**Docs**
```docs
```

Adding @puerco to calendar maintainers

---

groups/OWNERS
groups/wg-productivity/groups.yaml

Allow release leads to submit jobs to prow via kubectl

---

peribolos/knative-sandbox.yaml
peribolos/knative.yaml

Fixes: https://github.com/knative/community/issues/1234
/assign @thisisnotapril

drop google bots

---

.github/ISSUE_TEMPLATE/new-repo.md

- :bug: Correct links in new-repo template
/kind bug
Fixes #
Small change, so there's no issue.

:bug: Correct links in new-repo template

---

peribolos/knative-OWNERS_ALIASES
peribolos/knative-sandbox-OWNERS_ALIASES
peribolos/knative-sandbox.yaml
peribolos/knative.yaml

- Add eventing reviewer group in knative-sandbox
- Add myself as a eventing reviewer in knative & knative-sandbox

Add creydr as eventing reviewer

---

working-groups/WORKING-GROUPS.md

- Vincent will contribute to this community on behalf of another organization.

Change the org for Vincent

---

ADOPTERS.MD

https://github.com/knative/community/issues/696#issuecomment-1406241688
-
-
-
/kind <kind>
Fixes #
```release-note
feat(ADOPTERS.MD) Add KA-NABELL as adopter
```
**Docs**
```docs
feat(ADOPTERS.MD) Add KA-NABELL as adopter
```

feat(ADOPTERS.MD) Add KA-NABELL as adopter

---

.github/workflows/verify.yaml
groups/go.mod
groups/wg-security/groups.yaml

Add davidhadas to security group mailing list

---

working-groups/WORKING-GROUPS.md

Update Eventing WG meeting time

---

groups/groups_test.go
groups/wg-productivity/groups.yaml

/cc @jeefy
This group has all these privileges on the knative.dev org
https://github.com/knative/test-infra/blob/main/infra/gcp/iam.tf

Grant @jeefy GCP admin access

---

peribolos/knative-OWNERS_ALIASES
peribolos/knative-sandbox-OWNERS_ALIASES
peribolos/knative-sandbox.yaml
peribolos/knative.yaml

/assign @dsimansk 
/assign @kvmware 
/assign @pierDipi 
/assign @pradnyavmw

Update 1.10 Release Leads

---

peribolos/knative-OWNERS_ALIASES
peribolos/knative-sandbox-OWNERS_ALIASES
peribolos/knative-sandbox.yaml
peribolos/knative.yaml
working-groups/WORKING-GROUPS.md

Removing myself as WG lead
/kind removal

Ashleigh stepping down as Docs WG lead

---

peribolos/knative-sandbox.yaml
peribolos/knative.yaml

- Adding myself to the list of community members
Recent Work
- [knative/pkg/commits?author=vishal-chdhry](https://github.com/knative/pkg/commits?author=vishal-chdhry)
- [knative/eventing/commits?author=vishal-chdhry](https://github.com/knative/eventing/commits?author=vishal-chdhry)
- [knative/community/commits?author=vishal-chdhry](https://github.com/knative/community/commits?author=vishal-chdhry)
- [knative-sandbox/eventing-kafka-broker/commits?author=vishal-chdhry](https://github.com/knative-sandbox/eventing-kafka-broker/commits?author=vishal-chdhry)
/cc @pierDipi

adding vishal-chdhry-to-members

---

groups/wg-security/groups.yaml
peribolos/knative-OWNERS_ALIASES
peribolos/knative-sandbox-OWNERS_ALIASES
peribolos/knative-sandbox.yaml
peribolos/knative.yaml
working-groups/WORKING-GROUPS.md

Adds David Hadas as a security WG lead.
/kind <kind>
Fixes #

Propose David Hadas as a security WG lead

---

peribolos/knative-OWNERS_ALIASES
peribolos/knative-sandbox-OWNERS_ALIASES
peribolos/knative-sandbox.yaml
peribolos/knative.yaml

- Adds Stavros Kontopoulos as Serving approver. cc @dprotaso

Add Stavros as Serving approver

---

elections/2023-TOC/README.md

Fix 2 broken links in 2023 TOC Election README

Fix broken links in 2023 TOC Election README

---

peribolos/knative.yaml

Request to join as Member for Knative
-
-
-
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```

Add @pymhq as Member for Knative

---

ADOPTERS.MD

- Adding Gojek to the list of adopters. We, in the Data Science Platform team, use Knative Serving extensively.
/kind
Fixes #
```release-note
```
**Docs**
```docs
```

Add Gojek to list of Adopters

---

peribolos/knative-sandbox.yaml
peribolos/knative.yaml

- Adding myself to the list of community members.
Will be working on the VPA integration to Knative (ref: https://github.com/knative/serving/issues/8366#issuecomment-1503435193)

Add myself to community members

---

elections/2023-TOC/candidate-kvmware.md

Thanks for taking a look! :eyes:

Add myself as TOC candidate

---

peribolos/knative-OWNERS_ALIASES
peribolos/knative-sandbox-OWNERS_ALIASES
peribolos/knative-sandbox.yaml
peribolos/knative.yaml

Just adjusting reviewers from VMware 
- folks moving to different teams and people coming back from parental leave

update serving reviewers

---

peribolos/knative-sandbox.yaml
peribolos/knative.yaml

I'm adding myself as a knative and knative-sandbox member so I don't need to wait for the `ok-to-test` labels.
My contributions so far have been:
- [eventing PR](https://github.com/knative/eventing/pull/6977)
- [eventing-kafka-broker PR](https://github.com/knative-sandbox/eventing-kafka-broker/pull/3111)

Add Cali0707 to knative and knative-sandbox

---

groups/committee-oversight/groups.yaml
groups/groups.yaml
groups/wg-productivity/groups.yaml

part of https://github.com/knative/community/issues/1369

Add Krsna as owner to groups

---

.github/ISSUE_TEMPLATE/new-repo.md
REPOSITORY-GUIDELINES.md
mechanics/CREATING-A-SANDBOX-REPO.md

- :gift: Update some docs and Github issue template with CLOMonitor instructions
Context:
- I recently added Knative missing _core_ repos to the project [dashboard](https://clomonitor.io/projects/cncf/knative) and [CLOTributor](https://clotributor.dev/search?project=knative&page=1)
- I added the sandbox repos to CLOTributor only (in progress: https://github.com/cncf/clomonitor/pull/1076)
- I thought I should write how to do these in the docs
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```

Update repo guidelines with CLOMonitor instructions

---

peribolos/knative-OWNERS_ALIASES
peribolos/knative-sandbox-OWNERS_ALIASES
peribolos/knative-sandbox.yaml
peribolos/knative.yaml

- Updates leads As described in https://github.com/knative/release/blob/main/PROCEDURES.md#permissions-for-release-leads

Update leads for 1.11

---

ADOPTERS.MD

Fixes: https://github.com/knative/community/issues/1384

chore: add Sonavi Labs to ADOPTERS.MD

---

peribolos/knative-OWNERS_ALIASES
peribolos/knative-sandbox-OWNERS_ALIASES
peribolos/knative-sandbox.yaml
peribolos/knative.yaml
working-groups/WORKING-GROUPS.md

Given my current time commitments and activity levels, I'm no longer able to fulfill the duties of a working group lead for Serving. So, I'm stepping down from the position.
/assign @dprotaso 
-
-
-
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```

Paul stepping down as Serving WG Lead

---

groups/groups_test.go
groups/wg-productivity/groups.yaml
working-groups/WORKING-GROUPS.md

Update my Company affiliation

---

peribolos/knative-OWNERS_ALIASES
peribolos/knative.yaml

going to be working on functions -> add me as a func reviewer to assign myself to issues

gauron99 func reviewer

---

peribolos/knative-extensions.yaml

- knative-sandbox has been renamed now. This PR updates the description and the name that we see.
-
-
Fixes #169 
```release-note
```
**Docs**
```docs
```

Update name and description on knative-extensions

---

peribolos/knative.yaml

- update the repo description, for better reflection of updated Eventing tagline
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```

Update Eventing description

---

label_sync/labels.yaml

- :broom: Update or clean up current behavior
remove cncf-infra
Fixes: https://github.com/knative/test-infra/issues/3718

remove cncf-infra label

---

TECH-OVERSIGHT-COMMITTEE.md
groups/committee-oversight/groups.yaml
peribolos/knative-OWNERS_ALIASES
peribolos/knative-extensions-OWNERS_ALIASES
peribolos/knative-extensions.yaml
peribolos/knative.yaml

- Add David Hadas to TOC charter to fill vacant seat after Zbynek Roubalik 
@davidhadas on behalf of Knative community, let me welcome you to the Technical Oversight Committee. I hope you will like it and bring new & fresh ideas. :)
/cc @knative/steering-committee

Add David Hadas to TOC charter

---

peribolos/knative-extensions.yaml
peribolos/knative.yaml

- @yuzisun, also known as Dan Sun, is the technical lead of Bloomberg Cloud native inference team. He opened the issue of proposing the progressive rollout of serving revision. He will help to drive the implementation of this feature as an extension.
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```

Add @yuzisun into the Knative community

---

peribolos/knative-extensions.yaml
peribolos/knative.yaml

- @sukumargaonkar, also known as Sukumar Gaonkar, is a senior software engineer, working with the Bloomberg Cloud native inference team. He will help to drive the implementation of this feature as an extension.
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```

Add @sukumargaonkar into Knative community

---

peribolos/knative-OWNERS_ALIASES
peribolos/knative-extensions-OWNERS_ALIASES
peribolos/knative-extensions.yaml
peribolos/knative.yaml

I'm not really active in these groups anymore, so removing myself as an approver/writer.
Also syncing the docs writers members between core / extensions.
-
-
-
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```

Remove paul as approver from docs, productivity

---

peribolos/knative-OWNERS_ALIASES
peribolos/knative-extensions-OWNERS_ALIASES
peribolos/knative-extensions.yaml
peribolos/knative.yaml

- Adjust release leads to the schedule for the upcoming 1.12 release (https://github.com/knative/release/blob/main/README.md#release-schedule)
/assign @skonto

Adjust release leads to the schedule for the upcoming 1.12 release 

---

peribolos/knative-OWNERS_ALIASES
peribolos/knative-extensions-OWNERS_ALIASES
peribolos/knative-extensions.yaml
peribolos/knative.yaml

Add @Leo6Leo  as eventing reviewer
Add @Leo6Leo as eventing kafka broker reviewer

Added Leo6Leo as eventing reviewer

---

elections/2023-SC/candidate-aliok.md

Ali Ok running for Knative SC election

Ali Ok running for Knative SC election

---

label_sync/labels.yaml

- Add `kind/ui` label to docs and UX repos
- Add `kind/ux` label to docs and UX repos
- Add `kind/accessibility` label to docs and UX repos

Add ui, ux, and accessibility labels for UX and docs repos

---

peribolos/knative-extensions-OWNERS_ALIASES
peribolos/knative-extensions.yaml

- Add backstage-plugins repository
Part of https://github.com/knative/community/issues/1450

New repo: Add backstage-plugins repository

---

elections/2023-SC/results.md

- As suggested in https://github.com/knative/community/tree/main/elections#process, publishing 2023 SC election results, so that it shows up in Elekto properly.
/assign @geekygirldawn

2023 SC election results

---

peribolos/knative-OWNERS_ALIASES
peribolos/knative-extensions-OWNERS_ALIASES
peribolos/knative-extensions.yaml
peribolos/knative.yaml

- Add @Cali0707 as an eventing approver (follow up on the TOC meeting presentation by @pierDipi )

Add cali0707 as eventing approver

---

peribolos/knative-extensions.yaml
peribolos/knative.yaml

- @alexagriffith, is a Senior Software Engineer of Bloomberg Cloud native inference team. She is one of the maintainers in kserve project, podcast producer and tech book enthusiast & writer.  She will help to review the implementation of this feature as an extension.
/kind <kind>
```release-note
```
**Docs**
```docs
```

Add @alexagriffith into the Knative community

---

README.md

- Add CLOTributor link to the README
Part of #1403

Add CLOTributor link to README

---

peribolos/knative-OWNERS_ALIASES
peribolos/knative-extensions-OWNERS_ALIASES
peribolos/knative-extensions.yaml
peribolos/knative.yaml

- See discussion [here](https://cloud-native.slack.com/archives/C04LY4Y3EHF/p1704466731952259?thread_ts=1704451381.388299&cid=C04LY4Y3EHF).

Add Leo Li as release lead for 1.13

---

elections/2023-SC-EU/README.md
elections/2023-SC-EU/nomination-template.md

-
-
-
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```

Create folder and files for 2023-2024 end user seat

---

elections/2023-SC-EU/README.md

-
-
-
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```

Update README.md- make the end date floating

---

groups/groups.yaml

Adding myself as a member of the wg-leads group so that I can update calendar invites for the UX WG.

add cmurray as wg lead to working group leads list

---

peribolos/knative-OWNERS_ALIASES
peribolos/knative-extensions-OWNERS_ALIASES
peribolos/knative-extensions.yaml
peribolos/knative.yaml

drop juan from serving reviewers

---

CODE-OF-CONDUCT.md

-
-
-
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```

minor typo

---

peribolos/knative-OWNERS_ALIASES
peribolos/knative-extensions-OWNERS_ALIASES
peribolos/knative-extensions.yaml
peribolos/knative.yaml

As per title, I am moving new org and I don't have much time to contribute to the project.

Drop myself from members

---

elections/2023-SC-EU/candidate-nrrso.md

Adding my nomination for the 2024 end-user SC seat.

Add SVA/nrrso nomination for the EU seat

---

peribolos/knative-OWNERS_ALIASES
peribolos/knative-extensions-OWNERS_ALIASES
peribolos/knative-extensions.yaml
peribolos/knative.yaml

Hi, my name is Izabela, from VMware / Broadcom. 👋🏽  I'm planning to contribute to the development of Knative Serving and requesting to be added as a member to facilitate this collaboration in the near future.
- add izabelacg as a serving reviewer in both knative.yaml and knative-extensions.yaml files
- add izabelacg to the team that can triage serving issues in both knative.yaml and knative-extensions.yaml files

add izabelacg to the team that can triage issues and as a serving reviewer

---

peribolos/knative-extensions.yaml
peribolos/knative.yaml

I'm adding myself as a knative and knative-sandbox member so I don't need to wait for the ok-to-test labels.
My contributions so far have been:
[eventing](https://github.com/knative/eventing/commits?author=converge)
[eventing-kafka-broker](https://github.com/knative-extensions/eventing-kafka-broker/commits?author=converge)
cc @Cali0707 @pierDipi @davidhadas

docs: add john vanzuita to org

---

peribolos/knative-OWNERS_ALIASES
peribolos/knative-extensions-OWNERS_ALIASES
peribolos/knative-extensions.yaml
peribolos/knative.yaml

Dropping some Broadcom folks from being tagged on Serving PRs for reviews

Drop inactive Broadcom Serving reviewers

---

ADOPTERS.MD

- Add SVA to adopters list
- Fix table borders (separate commit)
-
/kind <kind>
Fixes #1500
```release-note
```
**Docs**
```docs
```

Add SVA to adopters list

---

working-groups/WORKING-GROUPS.md

Include knative.dev/pkg in the list of serving repos

---

peribolos/knative.yaml

Add @sadath-12 as a member to the community since he has been working on fixing issues and raising pr's https://github.com/pulls?q=is%3Apr+author%3Asadath-12+archived%3Afalse+knative%2Feventing+ and is active in the community . 
He wants to continue this journey with knative 
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```

membership: add sadath-12

---

STEERING-COMMITTEE.md
groups/committee-steering/groups.yaml
groups/groups.yaml
peribolos/knative-OWNERS_ALIASES
peribolos/knative-extensions-OWNERS_ALIASES
peribolos/knative-extensions.yaml
peribolos/knative.yaml

- Add nrrso to SC
-
-
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```

Add nrrso to SC

---

peribolos/knative-extensions-OWNERS_ALIASES
peribolos/knative-extensions.yaml

```release-note
Add Michal Kuratczyk and Aitor Pérez Cedres from RabbitMQ Team to Evenitng RabbitMQ
```

Add Michal Kuratczyk and Aitor Pérez Cedres from RabbitMQ Team to Evenitng RabbitMQ

---

peribolos/knative-extensions-OWNERS_ALIASES
peribolos/knative-extensions.yaml

Removing inactive members eric-sap and travis-minke-sap

Request from Ali Ok to remove eric-sap and travis-minke-sap

---

peribolos/knative-extensions-OWNERS_ALIASES
peribolos/knative-extensions.yaml

Part of https://github.com/knative/eventing/issues/7670
Thanks to these emeritus maintainers for all their work!
cc @tcnghia @gabo1208 
/assign @Zerpet @mkuratczyk @ikavgo

Drop some rabbitmq integration maintainers

---

peribolos/knative-extensions-OWNERS_ALIASES
peribolos/knative-extensions.yaml

- Replaces https://github.com/knative/community/pull/1542
-
-
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```

Remove vaibhavjainwiz and spolti as the approvers for Eventing Kogito

---

peribolos/knative-OWNERS_ALIASES
peribolos/knative-extensions-OWNERS_ALIASES
peribolos/knative-extensions.yaml
peribolos/knative.yaml

- add izabelacg to list of release leads for 1.14

update release leads for 1.14

---

peribolos/knative-OWNERS_ALIASES
peribolos/knative-extensions-OWNERS_ALIASES
peribolos/knative-extensions.yaml
peribolos/knative.yaml
working-groups/WORKING-GROUPS.md

I haven't been actively contributing to client for a while now, removing myself as approver for client and extensions. 
/assign @aliok

Step down as client approver

---

peribolos/knative.yaml

See request here: https://cloud-native.slack.com/archives/C04LQCW0C03/p1712913249691589

Promote cardil to admin temporarily to transfer issues

---

peribolos/knative.yaml

Reverts knative/community#1556
I've done the transferring, so I can hand over the superpowers
/cc @evankanderson

Revert "Promote cardil to admin temporarily to transfer issues"

---

peribolos/knative-OWNERS_ALIASES
peribolos/knative-extensions-OWNERS_ALIASES
peribolos/knative-extensions.yaml
peribolos/knative.yaml

- Add myself as serving approver
/assign @dprotaso

Add ReToCode as serving approver

---

peribolos/knative-extensions-OWNERS_ALIASES
peribolos/knative-extensions.yaml

- Adding matzew for Knative Function
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```

Adding matzew for Knative Function

---

peribolos/knative-extensions.yaml

Part of https://github.com/knative/serving/issues/14640
/assign @ReToCode @skonto

archive net-http01

---

TECH-OVERSIGHT-COMMITTEE.md
groups/committee-oversight/groups.yaml
groups/groups.yaml
groups/groups_test.go
groups/wg-productivity/groups.yaml
peribolos/knative-OWNERS_ALIASES
peribolos/knative-extensions-OWNERS_ALIASES
peribolos/knative-extensions.yaml
peribolos/knative.yaml

Was a pleasure working with all of you!

Krsna step down

---

peribolos/knative-OWNERS_ALIASES
peribolos/knative-extensions-OWNERS_ALIASES
peribolos/knative-extensions.yaml
peribolos/knative.yaml

- As discussed in [SC meeting](https://docs.google.com/document/d/16Rpd2nhmLWrkFJUfpJ31Ox2PpultJ-bYIhqaiWQff_I/edit#bookmark=id.pnorzm9igs1f), we're asking people to remove themselves from the roles, if they had no [activity for a year](https://github.com/aliok/knative-contrib-report/blob/main/350-build-manager-activity-list/managers-without-contributions.json)
- Inactivity in this context means:
- No issue creation, PR creation, commit or PR review (I didn't check issue comments) in the last 12 months.
- Tried to reach out to @odacremolbap on [CNCF Slack in a DM](https://cloud-native.slack.com/archives/C06R58T239C/p1711448972794649)
Thanks @odacremolbap for all the contributions!
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```

Remove odacremolbap from eventing writers

---

peribolos/knative-OWNERS_ALIASES
peribolos/knative.yaml

- As discussed in [SC meeting](https://docs.google.com/document/d/16Rpd2nhmLWrkFJUfpJ31Ox2PpultJ-bYIhqaiWQff_I/edit#bookmark=id.pnorzm9igs1f), we're asking people to remove themselves from the roles, if they had no [activity for a year](https://github.com/aliok/knative-contrib-report/blob/main/350-build-manager-activity-list/managers-without-contributions.json)
- Inactivity in this context means:
- No issue creation, PR creation, commit or PR review (I didn't check issue comments) in the last 12 months.
Thanks @snneji and @pmbanugo for all the contributions!
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```

Remove pmbanugo and snneji from docs-reviewers group

---

peribolos/knative.yaml

Adding myself as a knative member so I don't have to wait for the ok-to-test labels.
Contributions so far:
- [knative-eventing](https://github.com/knative/eventing/pulls/rahulii)

Add rahulii as knative member

---

peribolos/knative-OWNERS_ALIASES
peribolos/knative-extensions-OWNERS_ALIASES
peribolos/knative-extensions.yaml
peribolos/knative.yaml

Part of knative/release PR: https://github.com/knative/release/pull/315
/cc @ReToCode @skonto @Cali0707 @Leo6Leo 

Add release leads rotation for Knative v1.15

---

peribolos/knative-extensions-OWNERS_ALIASES
peribolos/knative-extensions.yaml

- Archive plugin repositories without releases and current maintenainers
- knative-extensions/kn-plugin-diag
- knative-extensions/kn-plugin-migration
For quiet some time there was no other changes then version bumps from our automation. It's time to archive the repos until there's new interest in those areas.
/cc @rhuss 

Archive plugin repositories without releases and current maintenainers

---

peribolos/knative-extensions.yaml
peribolos/knative.yaml

Adding myself as a community member since I'm a mentee for the LFX project.
I have opened the following PR:
https://github.com/knative/docs/pull/6032
https://github.com/knative/docs/pull/6029
https://github.com/knative/docs/pull/5988
https://github.com/knative/docs/pull/5964

adding ShravaniAK as community member

---

mechanics/RELEASE-SCHEDULE.md

This updates the min supported k8s versions based on [our policy](https://github.com/knative/community/blob/main/mechanics/RELEASE-VERSIONING-PRINCIPLES.md#k8s-minimum-version-principle)

Update the min supported K8s versions

---

groups/groups.yaml
groups/wg-ux/groups.yaml
working-groups/WORKING-GROUPS.md

As my work term at Red Hat is wrapping up this week, I'm switching my affiliation and email.

Change email/affiliation for @Cali0707

---

groups/groups_test.go
groups/wg-productivity/groups.yaml

swap out krsna for dave in productivity google group

---

peribolos/knative-OWNERS_ALIASES
peribolos/knative-extensions-OWNERS_ALIASES
peribolos/knative-extensions.yaml
peribolos/knative.yaml

Similar to https://github.com/knative/community/pull/1576
Thanks @maximilien , @zhaojizhuang and @zhanggbj for all the contributions!
Note: I've verified that they're inactive based on this: https://github.com/aliok/knative-contrib-report/blob/main/350-build-manager-activity-list/manager-activities.json
-
-
-
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```

Remove some inactive folks from Peribolos

---

peribolos/knative-extensions.yaml

This reverts commit f12ee573602b735464936623b0902bfb25576ae8.
- Make sure that this change is not breaking Peribolos run
I hope you don't mind. I promise we add it back once CI is fixed :)
/cc @matzew

Revert ":robot: Adding entries for eventing-integrations (#1612)"

---

peribolos/knative-OWNERS_ALIASES
peribolos/knative-extensions-OWNERS_ALIASES
peribolos/knative-extensions.yaml
peribolos/knative.yaml

- Revoke Release Leads role after 1.16 release
/cc @knative/steering-committee 
/cc @ReToCode @skonto

Revoke Release Leads role after 1.16 release

---

STEERING-COMMITTEE.md

Fix devstats link

---

STEERING-COMMITTEE.md

Adjusting to https://github.com/knative/community/blob/main/mechanics/SC.md#voter-eligibility

Fix SC voter eligibility

---

ADOPTERS.MD

Fixes: https://github.com/knative/community/issues/1627

Add Alauda as an adopter

---

ADOPTERS.MD

Drop/update ADOPTERS who's links don't work

---

elections/2024-SC/candidate-matzew.md

- adding `matzew` nomination
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```

SC Election: Adding nomination

---

elections/2024-SC/README.md
elections/2024-SC/election.yaml

- Extend nominations deadline
PTAL take a look if we want to move the whole schedule accordingly. Or we can vote on that in a follow-up as well. 
/cc @knative/steering-committee

Extend nominations deadline for SC election

---

ADOPTERS.MD

Fixes: https://github.com/knative/community/issues/1354

add telekom deutschland as an adopter

---

elections/2024-SC/results.md

As the [announcement](https://groups.google.com/g/knative-users/c/kMiMsJCabRk) was sent, adding the results here too

Add 2024 SC Member Election Results

---

mechanics/RELEASE-SCHEDULE.md

Fix EOL date for 1.16

---

peribolos/knative-OWNERS_ALIASES
peribolos/knative-extensions-OWNERS_ALIASES
peribolos/knative-extensions.yaml
peribolos/knative.yaml

- As I'll take on new responsibilities I will no longer be able to fulfil my roles here, so updating accordingly.

Remove myself from reviewer/approver roles

---

peribolos/knative-OWNERS_ALIASES
peribolos/knative-extensions-OWNERS_ALIASES
peribolos/knative-extensions.yaml
peribolos/knative.yaml

- Similar to https://github.com/knative/community/pull/1620.

Update release leads for Knative 1.17

---

peribolos/knative-OWNERS_ALIASES
peribolos/knative-extensions-OWNERS_ALIASES
peribolos/knative-extensions.yaml
peribolos/knative.yaml

Not active as a reviewer anymore
/cc @knative/steering-committee

drop izabela as a reviewer

---

groups/groups.yaml

Fix the post submit jobs: https://github.com/knative/community/pull/1661#issuecomment-2618133381

Fix calendar group

---

peribolos/knative-extensions-OWNERS_ALIASES
peribolos/knative-extensions.yaml

I'm no longer able to fulfill the duties and responsibilities of serving as a maintainer, so I am voluntarily stepping down as an approver for the quickstart plugin and security guard. 
/assign @knative/steering-committee

paul stepping down as extensions approver

---

peribolos/knative-OWNERS_ALIASES
peribolos/knative-extensions-OWNERS_ALIASES
peribolos/knative-extensions.yaml
peribolos/knative.yaml

- Add dsimansk to Serving approvers
I've chatted about it with @skonto as I've started to pick up more maintenance tasks on Serving's side of the house. 
@dprotaso PTAL if that's OK with you as well.    
/cc @dprotaso

Add dsimansk to Serving approvers

---

elections/2025-SC-EU/candidate-kahirokunn.md

Adding my nomination for the 2025 end-user EU seat.

Add KA-NABELL/kahirokunn nomination for the EU seat

---

working-groups/WORKING-GROUPS.md

Adding me in the Working Group overview as https://github.com/knative/community/pull/1675 merged

Add creydr to Eventing Working Group

---

peribolos/knative-extensions-OWNERS_ALIASES
peribolos/knative-extensions.yaml

Reverting #1665 
I am going to resume maintaining the quickstart plugin :partying_face: 
Slack thread with WG approvals: https://cloud-native.slack.com/archives/C04LY4SKBQR/p1744203708115369

paul returning as quickstart approver

---

peribolos/knative-extensions.yaml

- Add gauron99 as a regular member of knative-extensions
This should fix the issue with recurring new invites. You wasn't added to extensions org config as a member.
/cc @gauron99

Add gauron99 as a regular member of knative-extensions

---

peribolos/knative.yaml

This PR adds @Fedosin as a knative member

Add Fedosin to the list of members

---

STEERING-COMMITTEE.md

- adding Andrew as End User seat candidate
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```

Updating the SC members to reflect current status

---

groups/groups.yaml
groups/wg-ux/groups.yaml

I recently rejoined Red Hat and would like to change my email for use in Knative to my Red Hat email
- Switches from my personal email to my Red Hat email

Updating email used for community

---

peribolos/knative-extensions.yaml
peribolos/knative.yaml

I think we're hitting spam limits since he rejected the invite

[peribolos] drop coryc from list of members

---

peribolos/knative-extensions.yaml
peribolos/knative.yaml

Adding myself as a knative and knative-sandbox member so I don't have to wait for the ok-to-test labels.
Contributions so far:
- [knative/docs](https://github.com/knative/docs/issues?q=author:twoGiants)
- [knative/eventing](https://github.com/knative/eventing/issues?q=author:twoGiants)
- [knative-extensions/eventing-kafka-broker](https://github.com/knative-extensions/eventing-kafka-broker/issues?q=author:twoGiants)

Add twoGiants as a knative & knative-extension member

---

peribolos/knative.yaml

- Add new member
```release-note
```
**Docs**
```docs
```

Add user as a member
