knative/community

WORKING-GROUPS.md
Going over the requirements from [here](https://github.com/knative/community/blob/master/ROLES.md#lead)
> Recognized as having expertise in the group’s subject matter.
Dan has been deeply involved in the API Working Group for some time now.
Dan was a key voice in the "v1beta1 task force", as well as a number of the
discussions leading up to its formation.  Dan has been driving our
conformance efforts in serving around both the control plane and runtime
contract.
> Approver for some part of the codebase for at least 3 months.
Dan was added as an approver on 2/14.  I can wait until tomorrow to remove the hold. 😈 
> Member for at least 1 year or 50% of project lifetime, whichever is shorter.
Dan joined in September (9 months ago), which is 50% of the project lifetime.
> Primary reviewer for …
=> Add Dan as a lead for the Serving API Working Group

WORKING-GROUPS.md
I propose to add Markus Thömmes (Red Hat) as an additional Scaling Working Group Lead.
Requirements: ([link](https://github.com/knative/community/blob/6fe7db2a5f984bf8a9c7855f12073cb3ef3df6e9/ROLES.md#lead)):
> Working group leads, or just ‘leads’, are approvers of an entire area that have demonstrated good judgement and responsibility. Leads accept design proposals and approve design decisions for their area of ownership.
> 
> Getting to be a lead of an existing working group:
> - Recognized as having expertise in the group’s subject matter.
> - Approver for some part of the codebase for at least 3 months.
> - Member for at least 1 year or 50% of project lifetime, whichever is shorter.
> - Primary reviewer for 20 substantial PRs.
> - Reviewed or merged at least 50 PRs.
> - Sponsored by …
=> Add markusthoemmes as Scaling Working Group Lead.

STEERING-COMMITTEE.md
As many know, I'm switching teams at Google and will be handing off Knative-related responsibilities shortly. Donna Malayeri is the replacement for the vacant steering committee seat. Welcome, Donna!
=> Add Donna Malayeri to fill Google's open steering committee seat.

ROLES.md
table states that 2 members are needed for sponsorship so clarifying what this requirement means
/assign @rgregg
=> clarify requirement

WORKING-GROUPS.md
I propose to replace me (josephburnett) with Victor (vagababov) as Scaling Working Group lead.  He has been very active as a contributor and leader in the scaling space.
[Requirements](https://github.com/knative/community/blob/e63f566120fe45ffdec92caf061ecf66a3c933aa/ROLES.md#lead):
[X] Recognized as having expertise in the group’s subject matter.
- Design and Implementation of the Revision based activation
- Design and implementation of the burst capacity handling
- Numerous stability and reliability improvements across the autoscaling stack, etc...
[X] Approver for some part of the codebase for at least 3 months (approver for part of the codebase since Mar 19 (4mo+)
[X] Member for at least 1 year or 50% of project lifetime, whichever is shorter (joined in late November, 2018 - 8mo+. …
=> Add vagababov as scaling working group lead

CONTRIBUTING.md, DOCS-CONTRIBUTING.md
Because contributions are tracked by the email address used to sign CLAs, add statement making it clear that your GitHub account will send commits using `noreply` as the email address if you set you account to private.
=> Make clear that you cannot commit from `noreply`

mechanics/FEATURE-TRACKS.md
I was reading the feature tracks document and thought that we'd accidentally left in a bunch of links, rather than that we were trying to do footnotes. Per [stackoverflow suggestion](https://stackoverflow.com/questions/25579868/how-to-add-footnotes-to-github-flavoured-markdown), I did a bit of HTML formatting to make the footnotes look more footnote-y.
=> Format footnotes to be more obviously footnotes.

TECH-OVERSIGHT-COMMITTEE.md
Why?
1 - now there's only one spot to update when things change
2 - don't need a PR each time the VC info changes
3 - I keep clicking on the wrong link (the one here instead of the notes)
If people are ok with this I can do the same change for the WG doc too.
=> Point to the meeting minutes for the VC link

OWNERS_ALIASES, README.md, docs/DOCS-CONTRIBUTING.md, docs/OWNERS, docs/OWNERS_ALIASES, docs/README.md, docs/_index.md, docs/new-page-template.md
This moves the information about contributing to the docs to its own separate folder, allowing us to place a template page that had been living in the Docs repo here instead.
From what I understand, having a docs folder should also make it possible for us to be given permissions to approve changes within only the docs folder of the Community repo, so that we can update and maintain that information without needing someone from the Community approvers list to review.
Docs PR: https://github.com/knative/docs/pull/2106
=> Create docs folder

CODE-OF-CONDUCT.md, CONTRIBUTING.md, README.md, REPOSITORY-GUIDELINES.md, REVIEWING.md, ROLES.md, SLACK-GUIDELINES.md, STEERING-COMMITTEE.md, TEAM-VALUES.md, TECH-OVERSIGHT-COMMITTEE.md, VALUES.md, WORKING-GROUPS.md, docs/DOCS-CONTRIBUTING.md, docs/README.md, docs/new-page-template.md, mechanics/FEATURE-TRACKS.md, mechanics/README.md, mechanics/WORKING-GROUP-PROCESSES.md, mechanics/_index.md
Use fully qualified URLs to the knative/docs repo that new script (https://github.com/knative/website/pull/119) can target and convert those links into relative link during the knative.dev site build. 
(*Make links to knative/docs within the source files work in GitHub and also in knative.dev.*)
I also:
- fixed some broken links or links that cause errors in the github precheck link checker
- add missing frontmatter (to add that content so that its visible in the left nav)
Related: 
- https://github.com/knative/docs/pull/2086 (fully qualify all knative/community link/URLs) 
- https://github.com/knative/website/pull/119 (fixes https://github.com/knative/website/issues/50)
- https://github.com/knative/docs/issues/1874
Fixes #3 
cc/ @rgregg @evankanderson 
**[View/test …
=> Fix links, titles, frontmatter, and use fully qualified knative/docs URLs

working-groups/WORKING-GROUPS.md
Since these URLs change every now and then, this will avoid the need for a PR each time it does
=> remove links to VCs, point to notes

working-groups/WORKING-GROUPS.md
Add Grant Rodgers as Eventing WG technical lead.
[Requirements](https://knative.dev/contributing/roles/#working-group-technical-lead):
- Key contributor to [initial Eventing API design](https://docs.google.com/document/d/1JZtFkz_C3orG9IfDxxGkAmuuGxUQ434ji-rdl3oKObE)
- Led design and implementation of [Broker and Trigger](https://docs.google.com/document/d/1cRk8dko2zN3CthYwCuC1esZPoW_5roCDHw0K8cd2yVo)
- Created and currently lead [Eventing Performance Task Force](https://docs.google.com/document/d/1UgblGknPcIMcOfUc_UImUAyjTGTfZNWXZV1_iPsDntY)
- Designed and implemented (never merged) [Advanced filtering for triggers](https://docs.google.com/presentation/d/1v1XgRJVDL8eMPiWEIdRAWxFOolSxhI5JC3epHnrnwsk)
- Many other features and improvements
- Approver for eventing since [August …
=> Add grantr as Eventing WG lead

working-groups/WORKING-GROUPS.md
Kenny and Vincent have been doing most of the heavy lifting of leading the Operations Working Group for a while now. While I'm still very invested in Knative itself, I do not have the necessary time to devote to this role. I've spoken to them offline about this, but just making it official.
cc @k4leung4 @houshengbo
=> Step down as an Operations WG lead

working-groups/WORKING-GROUPS.md
[Requirements](https://knative.dev/contributing/roles/#working-group-technical-lead):
- Led the implementation of Conversion Webhook support for knative/serving.
- Participated in the v1beta1/v1 API task force.
- Many other features and improvements
- Approver for serving API since [June 2019](https://github.com/knative/serving/pull/4426)
- One of the earliest Knative (FKA Elafros) contributors!
- [47 L, XL, XXL in knative/serving](https://github.com/knative/serving/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Amerged+-author%3Adprotaso+reviewed-by%3Adprotaso+-label%3Asize%2FS+-label%3Asize%2FXS+-label%3Asize%2FM+)
- [4 L, XL, XXL in knative/pkg](https://github.com/knative/pkg/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Amerged+-author%3Adprotaso+reviewed-by%3Adprotaso+-label%3Asize%2FS+-label%3Asize%2FXS+-l …
=> Add Dave Protasowski as Serving API Core WG technical lead.

working-groups/WORKING-GROUPS.md
The client working group decided to move to an alternating schedule
for the WG calls, so that people from APAC region can join, too.
For reasoning and the community poll, please see https://github.com/knative/client/issues/740
(and also the client WG call protocols).
So ecery odd-numbered week (like this week, which is calendar week 13),
the current timeslot is active, on every other week we want to try
out 3:30pm Central European time (CET or CEST)
Beside this PR, would it be possible to adapt the Knative calendar, too ?
Although we settled on an European timezone for the second timeslot,
as a good approximation we can also use 6:30am Pacific Time.
=> Update meeting schedule for client WG

CONTRIBUTING.md
it seems that the file got moved to the `docs/` folder but the link was not updated.
=> Fix the link to `DOCS-CONTRIBUTING.md`

CONTRIBUTING.md, README.md, SLACK-GUIDELINES.md, STEERING-COMMITTEE.md, WORKING-GROUPS.md, docs/DOCS-CONTRIBUTING.md, docs/README.md, mechanics/WORKING-GROUP-PROCESSES.md
Fixes up all the links to be relative to the new location for `working-groups/WORKING-GROUPS.md`, and deletes the old link, which results in a duplicate side-heading at https://knative.dev/community/contributing/working-groups/ and https://knative.dev/community/contributing/working-groups/working-groups/
/assign @rgregg
=> Remove WORKING-GROUPS.md link to remove duplicate headings from website.

STEERING-COMMITTEE.md
Per nomination from Google and a unanimous vote of the steering committee, @thisisnotapril is appointed to the Knative Steering Committee.
=> Add April Kyle Nassi to Steering

working-groups/WORKING-GROUPS.md
Signed-off-by: Matthias Wessendorf <mwessend@redhat.com>
After the WG has been renamed, let's change the slack channel too
=> Add hopefully soon renamed channel name

STEERING-COMMITTEE.md
My last day at Google is Friday, May 8th. 
Since my steering committee seat is assigned to Google, I am resigning my seat on the committee.
It's been wonderful working with the Knative community for the last two years to make Knative into what it is today, and I have a lot of excitement about where Knative is going in the future.
Thank you to everyone who has help made Knative fantastic. Best wishes!
=> Ryan Gregg resignation from Steering

peribolos/knative-sandbox.yaml
I cleared out all the "org" members who hadn't accepted earlier invites, on the theory that:
1. They were probably not that interested in the repo.
1. They could re-add to the org easily with a PR if they did want access later.
1. GitHub is so spammy they probably would keep missing the invite.
Unfortunately, Adam hadn't accepted the invite, and team members must be org members, so we need to re-add him (or remove him from the WG lists).
=> Re-add Harwayne (WG lead) who was removed in the great absent user scrub of 2020

peribolos/knative-sandbox.yaml, peribolos/knative.yaml
Add `knative-prow-robot` as an org admin for `knative` and `knative-sandbox`, so it has enough permissions to run `peribolos` jobs.
Please note this permission will have to be manually set for the first time.
=> Add knative-prow-robot as an org admin

peribolos/knative.yaml
With this PR, the diff for the `knative` org is clean except for some team title / wiki cleanups.
=> Add two users who were added manually after #135

mechanics/RELEASE-VERSIONING-PRINCIPLES.md
- 0.14 min K8s is 1.15
- 0.15 min K8s is 1.16
- 0.16 min K8s will remain 1.16
- 0.17 min K8s will hopefully be 1.17
Delay is due to availability of stable newer version from providers
I didn't bother predicting 0.18 and beyond
=> Change min K8s version to reflect reality

peribolos/knative.yaml
I missed these earlier due to peribolos noise, but caught them when reviewing the GitHub audit log.
=> Add two milestone maintainers which were added after #135

peribolos/knative-sandbox.yaml, peribolos/knative.yaml
Cris is a new summer intern in Google, and will be working on Knative during these three months.
And by the way fix one syntax error in the `knative-sandbox.yaml` file as the key is duplicated.
=> Add Cris Zong to the Knative org

peribolos/knative-sandbox.yaml
The error log for the peribolos Prow job is https://prow.knative.dev/view/gcs/knative-prow/logs/ci-knative-sandbox-peribolos/1282359710120415233#1:build-log.txt%3A2, the error is `error converting YAML to JSON: yaml: line 230: mapping values are not allowed in this context`.
=> Fix the peribolos configuration file for knative-sandbox

peribolos/knative-sandbox.yaml, peribolos/knative.yaml, working-groups/WORKING-GROUPS.md
As discussed in the 9 July 2020 TOC meeting.
Ashleigh has been leading the docs WG de facto for a while while @samodell was on leave, and @carieshmarie said that Sam was talking about recommending her for WG lead before she left.
/assign @mattmoor @markusthoemmes @grantr @tcnghia
=> Add Ashleigh as Docs WG lead

peribolos/knative-sandbox.yaml
For unknown reason, the peribolos Prow job is failing when it processes `urasoko` as a member, and removing this person will resolve this error.
See https://prow.knative.dev/view/gcs/knative-prow/logs/ci-knative-sandbox-peribolos/1283169654633664513 and https://prow.knative.dev/view/gcs/knative-prow/logs/ci-knative-sandbox-peribolos-test/1283171920660926465.
/cc @mattmoor
=> Remove urasoko from peribolos config file to get rid of the job error

peribolos/knative.yaml
It's the same issue as https://github.com/knative/community/issues/186.
They also fail the peribolos Prow job for Knative org.
/assign @mattmoor
=> Remove urasoko from the configuration file to fix the Knative peribolos Prow job

.github/ISSUE_TEMPLATE/new-repo.md, .github/ISSUE_TEMPLATE/process.md, .github/ISSUE_TEMPLATE/question.md, mechanics/CREATING-A-SANDBOX-REPO.md, peribolos/knative-sandbox.yaml, peribolos/knative.yaml
Fixes #152 , #76 
Since I've had to do it twice, I bothered writing up some instructions.
/assign @mattmoor
=> Add docs on creating sandbox repos

mechanics/SUNSETTING-FEATURES.md
Fixes  #199.
This is roughly the process that we've followed in the Autoscaling WG to sunset the custom-metrics API.
=> Document the process to sunset a feature from Knative.

STEERING-COMMITTEE.md
I noticed in #214 that it was pointing to the docs repo, rather than the community repo.
/assign @thisisnotapril @bsnchan
=> Fix location of steering committee issues

peribolos/knative-sandbox.yaml
This is to start defining common metadata across the organization.
Related: https://github.com/knative/community/issues/218
/assign @grantr @evankanderson @tcnghia @markusthoemmes 
cc @chaodaiG @chizhg @coryrc @n3wscott 
/hold
I'd like a couple pairs of eyeballs on this to sanity check me 😇
=> Add a .github repo to sandbox

README.md
Fix https://github.com/knative/serving/issues/8005 .
Now that we have user support rotations, I'd like to advertise them in doc.
=> Advertise @serving-help and @eventing-help Slack user group.

mechanics/RELEASE-SCHEDULE.md
Because it can be a pain to look this up, and because we are talking about moving the December release by 1-2 weeks.
Fixes #216
=> Document release schedule for the next 9 months

peribolos/knative-sandbox.yaml
Fixes #239
https://github.com/knative-sandbox/wg-repository
Includes README, OWNERS files, COC, and test skeleton ready for first PR.
=> Add wg-repository template for new repos

peribolos/knative-sandbox.yaml
adding a repo to create a custom github action for knative to test downstream repos upgradability from upstream repos.
=> Git Hub Action - downstream-test-go

peribolos/knative-sandbox.yaml
Sandbox is intended to be a little less structured that core Knative. In working with github actions, I need to be able to make releases, but I am not a member of productivity. Making a new group to have admin over the `.github` and `github actions` related repos in `knative-sandbox`.
=> Make it so the folks doing github actions exploring in sandbox can make releases

.github/ISSUE_TEMPLATE/new-repo.md
With this change, the only steps that actually require the involvement of admins
is the initial PR approval for the Peribolos config, and the final step of
enabling branch protections.  Beyond those, the contributor seeking a repository
(in conjunction with a WG lead) can bootstrap the entire process.
Fixes: https://github.com/knative/community/issues/241
=> This revises the new-repo template to be more self-service.

OWNERS_ALIASES
This PR removes past steering members from the owners file. #191 addresses adding the new steering members (pending them accepting their github invitation).
=> Removes past steering members from owners file

mechanics/RELEASE-VERSIONING-PRINCIPLES.md
- knative 0.17 minimum kubernetes version is 1.16.
- future minimum version may be 1.17, but we're not sure yet. It definitely won't be 1.19 by knative 0.18, though. For now it seems better to say "(undetermined)" than for this to be actively wrong.
/assign @mattmoor @vaikas
=> Make projected minimum kubernetes versions more true

peribolos/knative-sandbox.yaml
For 
- https://github.com/knative/community/issues/223
- https://github.com/knative/community/issues/224
- https://github.com/knative/community/issues/232
- https://github.com/knative/community/issues/233
- https://github.com/knative/community/issues/234
- https://github.com/knative/community/issues/235
- https://github.com/knative/community/issues/236
- https://github.com/knative/community/issues/237
@grantr as discussed.
=> Add eventing-XXX to repo config for sandbox

.github/ISSUE_TEMPLATE/new-repo.md
In the new repo creation template, we tell people to add the new issue to the TOC backlog project. But they probably can't use the Projects quick menu in this repo due to lack of write access, so we should tell them to use the project board interface instead.
Fixes #260
=> Note that the Projects menu may not work

peribolos/knative.yaml
Add Harwayne to 'Eventing Triage', following the instructions in https://github.com/knative/eventing/blob/master/support/COMMUNITY_CONTACTS.md as the weekly contact for Sep 21-27.
=> Add Harwayne to Eventing Triage

peribolos/knative.yaml
The error is `Configuration failed: failed to configure knative members: all team members/maintainers must also be org members: jessiezcc`, see https://prow.knative.dev/view/gs/knative-prow/logs/ci-knative-peribolos/1309538632675102723#1:build-log.txt%3A8
/cc @mattmoor
=> Fix peribolos config file for Knative by removing jessiezcc

peribolos/knative-sandbox.yaml
Issue: https://github.com/knative/community/issues/282
=> added kn-plugin-source-pkg to knative-sandbox

peribolos/knative-sandbox.yaml
Was blocked on releasing Autoscaler-Keda during the 0.18 release, this corrects that.
=> add eventing-autoscaler-keda to eventing writers

peribolos/knative-sandbox.yaml, peribolos/knative.yaml, working-groups/WORKING-GROUPS.md
Haven't been able to focusing on driving knative productivity for a few months now, and probably won't be able to make much time for it in the near future either. Will still be around and can help, just will not be as engaged.
/cc @chizhg
=> chaodaiG step down as productivity WG lead

peribolos/knative-sandbox.yaml, peribolos/knative.yaml, working-groups/WORKING-GROUPS.md
Considering the mission of `Productivity`: 
```
Project health, test framework, continuous integration & deployment, release, performance/scale/load testing infrastructure
```
I feel I have proven myself as someone who continually pushes on frameworks for both testing, release and development. 
Some highlights:
- (Development) The reconciler-gen code Knative and Tekton use to make reconciling a consistent developer experience.
- (Testing) PoC of [Rigging](https://github.com/n3wscott/rigging) for e2e testing replacements, which is moving to [reconciler-test](https://github.com/knative-sandbox/reconciler-test) and merging into something that will be leveraged by all of Knative. 
- (Testing) Cucumber based runners for table tests for reconciler testing, …
=> Add Scott to Productivity Leads

mechanics/RELEASE-SCHEDULE.md
This patch fixes "2020" in the release schedule.
Without this patch, we cannot break 2020 loop.
/cc @evankanderson @tcnghia
=> Fix release schedule's year

peribolos/knative.yaml
quentin-cha is a new member in the Knative Eventing team at Google
=> Add quentin-cha to knative member list

mechanics/RELEASE-SCHEDULE.md
As per https://github.com/knative/pkg/pull/1803, v0.2.0 is moved by 3
weeks for end of year holidays so this PR sync with the schedules.
/cc @evankanderson @n3wscott @tcnghia @slinkydeveloper
=> Push one more 1 week for end of year holidays

peribolos/knative-sandbox.yaml, peribolos/knative.yaml
As per title, adding @knative-automation to knative and knative-sandbox community.
Currently we need to add `/ok-to-test` every auto PR like https://github.com/knative/serving/pull/9943.
=> Add knative-automation to knative and knative-sandbox

peribolos/knative-sandbox.yaml
In order to new a repo `kn-plugin-source-kafka` under knative sandbox, I create this PR, including:
- Add the repository and a description.
- Grant Knative Admin the admin privilege.
- Grant the sponsoring WG the write privilege.
Refer to https://github.com/knative/community/issues/330
=> Add kn-plugin-source-kafka to the peribolos sandbox config

peribolos/knative.yaml
Mohamed Elhawaty is a new member in the Knative Eventing team at Google
=> Add mohamedelhawaty to knative member list

peribolos/knative.yaml
Add `chizhg` to Knative Milestone Maintainers to be able to trigger Prow jobs from UI
=> Add chizhg to Knative Milestone Maintainers

peribolos/knative-sandbox.yaml, peribolos/knative.yaml
Following the [Release Leads process](https://github.com/knative/pkg/blob/master/RELEASE-LEADS.md): the release is now cut, passing on the torch to @nak3 and @slinkydeveloper!.
/assign @n3wscott @mattmoor
=> Update Release Leads for 0.20

mechanics/RELEASE-SCHEDULE.md, mechanics/RELEASE-VERSIONING-PRINCIPLES.md
Related: https://github.com/knative/community/issues/245
Fixes 
- https://github.com/knative/docs/issues/2796 
- https://github.com/knative/docs/issues/2797
See the [rendered](https://github.com/knative/community/blob/c627bdfdb506a4e12f13db52cc006ec88b1ec242/mechanics/RELEASE-VERSIONING-PRINCIPLES.md) preview. I dropped older releases.
Based on the current principles we're going to make v1.17 our min K8s for the Knative release 0.20.x - but it will EOL 2-3 weeks later.
=> Add the upcoming releases & k8s min versions

peribolos/knative-sandbox.yaml
I'm a Google engineer working on knative - I've added myself to knative but not knative-sandbox and it's been causing issues in the net-istio repo.
=> Add self to knative-sandbox team members

.github/ISSUE_TEMPLATE/new-repo.md
- link the test-infra prow setup guide
- separate step for configuring hack repo and update new URL
=> Update new repo template to link the prow guide

.github/OWNERS
Allow and assign `.github` reviews to TOC, rather than to Steering. Since OWNERS is hierarchical, Steering will still have ability to approve PRs, but they won't be blocked.
/kind cleanup
See discussion in #390 
/assign @bsnchan
=> Allow TOC to manage .github directory

peribolos/knative-sandbox.yaml, peribolos/knative.yaml
I'm working on Knative eventing at Google.
* Update knative-sandbox.yaml: Add Haolicopter
Add to the members list
* Update knative.yaml: Add Haolicopter
Add to members list
=> Add Haolicopter to knative and knative sandbox members

mechanics/GOLANG-POLICY.md
Fixes #355 
As promised in the TOC meeting, here's my stab at a Golang "policy". I hope it captures what was discussed in the meeting.
TOC is kept out of any approval paths except for "emergency" updates shortly before a release. We've never had such a case yet, but it felt right to have a handle at that specific edge-case. I wanted to put "should be widely discussed and agreed upon", which kinda felt equal to "bring it to the TOC meeting".
/assign @evankanderson @mattmoor @tcnghia @grantr
=> Add a Golang policy

working-groups/WORKING-GROUPS.md
Updating the Eventing WG links to use the new doc and folder that @tcnghia set up.
/cc @tcnghia
=> Update Eventing WG to new Knative Drive links

peribolos/knative-sandbox.yaml
As per title, this patch adds net-ingressv2 to peribolos configuration.
Please also refer to https://github.com/knative/community/issues/389
```release-note
NONE
```
/cc @tcnghia @ZhiminXiang
=> Add net-ingressv2 to peribolos configuration

peribolos/knative-sandbox.yaml, peribolos/knative.yaml
2d0783b7a1d9b1f4bdd141db70023d9f5dbefdb2 added vaikas as an admin. It
causes peribolos configuration [error](https://prow.knative.dev/view/gcs/knative-prow/logs/post-knative-sandbox-peribolos/1339745466102845440):
```
{"component":"unset","file":"prow/cmd/peribolos/main.go:202","func":"main.main","level":"fatal","msg":"Configuration failed: failed to configure knative-sandbox members: users in both roles: vaikas","severity":"fatal","time":"2020-12-18T01:33:12Z"}
```
To fix it, this patch removes vaikas from member list but keeps vaikas in admin list.
/kind bug
```release-note
NONE
```
/cc @evankanderson @bsnchan @vaikas
=> Remove duplicatd user in admin and member role

CONTRIBUTING.md, TECH-OVERSIGHT-COMMITTEE.md, mechanics/FEATURE-TRACKS.md, mechanics/WORKING-GROUP-PROCESSES.md, working-groups/WORKING-GROUPS.md
- :broom: Update docs in `knative/community` to link to the new `knative.team` domain.
Related: #86 
/kind cleanup
/assign @tcnghia @mattmoor
=> Update links for knative.team docs and calendar

elections/2020/SC/voters.md
I've renamed my github username from Abd4llA to devguyio . This is a proof https://github.com/cncf/gitdm/pull/398
=> Remove my old github username from the voters file

peribolos/knative.yaml
To allow me to kick off knative-gcp release job
- add nlopezgi to Knative Milestone Maintainers
Allow nlopezgi to manually kick off release prow job for knative-gcp repo
=> add nlopezgi to Knative Milestone Maintainers

peribolos/knative-sandbox.yaml
and sorting the kn plugins in alphabetical order.
=> chore: Add kn-plugin-migration to peribolos configuration

icons/broker.svg, icons/channel.svg, icons/kn-broker-name.svg, icons/kn-broker.svg, icons/kn-channel-name.svg, icons/kn-channel.svg, icons/kn-revision-name.svg, icons/kn-revision.svg, icons/kn-service-name.svg, icons/kn-service.svg, icons/kn-source-name.svg, icons/kn-source.svg, icons/kn-subscription-name.svg, icons/kn-subscription.svg, icons/kn-trigger-name.svg, icons/kn-trigger.svg, icons/revision.svg, icons/service.svg, icons/source-generic.svg, icons/subscription.svg, icons/trigger.svg
- :gift: Add icons for Serving and Eventing
Fixes lack of icons in the project. 
Currently there are no icons available.
Docs and presentations have no standard in diagrams. Icons would help convey concepts and ideas across platforms. 
This [doc](https://docs.google.com/document/d/18iLbEPXSil4XsjKs5WcC_9uK9WYnV2CSXYu4uj8OIVo/edit) describes the icons in detail. 
```release-note
New set of icons have been included for use across documentation, presentations, and IDEs.
```
**Docs**
```docs
[icons now available for diagrams in docs, this PR does not update docs directly]
```
=> Add icons for Serving and Eventing

peribolos/knative-sandbox.yaml
Teams haven't been created yet.
Some teams are empty since currently all members are WG leads. Hopefully this is not causing problems, otherwise I'll add at least a member to the list.
=> Add teams for eventing-* approvers

working-groups/WORKING-GROUPS.md
Add roadmap link for UX WG
- :gift: Add roadmap link for UX WG
Related to #490
=> add roadmap link for UX working group table

peribolos/knative-sandbox.yaml
Fix typo and actually populate groups.
/kind cleanup
=> Fix `repo` typo

peribolos/knative-sandbox.yaml, peribolos/knative.yaml
/cc @evankanderson @markusthoemmes 
/assign @evankanderson @markusthoemmes 
/hold
Both have superpowers through TOC already, but I want both to ACK that they are on point for 0.22 per: https://github.com/knative/pkg/blob/master/RELEASE-LEADS.md#schedule
cc @lionelvillard (losing superpowers)
=> Switch to the 0.22 release leads

peribolos/knative-sandbox.yaml
This technical user is used to prevent notifications to
members of fallback-teams (like the TOC or the release leads)
=> Add fallback-notification-blocker to peribolos config

peribolos/knative.yaml
See #532 -- it turns out that Ron was being removed from the org and then re-invited because he wasn't in the members list, but was on a team.
=> Add Ron as an actual org member

working-groups/WORKING-GROUPS.md, working-groups/client/CHARTER.md, working-groups/delivery/CHARTER.md, working-groups/docs/CHARTER.md, working-groups/operations/CHARTER.md, working-groups/productivity/CHARTER.md, working-groups/security/CHARTER.md, working-groups/sources/CHARTER.md
Fixes #410.
For all WGs except Event Delivery, I did the following:
1. Search in team drive for the team's charter doc. Other terms include: "proposal" and "mission"
2. Use the ["Docs to Markdown"](https://workspace.google.com/marketplace/app/docs_to_markdown/700168918607) plugin to convert to markdown.
3. Run `prettier --write CHARTER.md` on the output from 2
4. Clean up the header and check sections quickly.
I did a little more cleanup on Event Delivery, but it's still largely the "channels wg" charter.
=> Add charters for all WGs that have them.

OWNERS_ALIASES, peribolos/knative.yaml
(PRs incoming shortly for each repo to use the groups defined here.)
Note that I did not preserve _all_ groups that existing in each OWNERS_ALIASES file. I also needed to create several groups, and split up `Serving Writers` into Working Group based groups.
My criteria for creating groups in peribolos was:
1. Associated with an existing WG (e.g. "$FOO Reviewers" for those working to approver for a WG)
2. **Multiple** directories which should have consistent ownership. There were a number of cases where a group was defined in OWNER_ALIASES and then used in only a single OWNERS file, which seems to simply make extra work. I inlined these groups in the per-repo PRs.
Note that I did _not_ try to rationalize much of the existing files, simply to migrate them to OWNERS_ALIASES
Another change …
=> Add groups based on observed usage in knative repos

elections/2021-TOC/election.yaml, elections/2021-TOC/election_desc.md, elections/2021-TOC/template-for-candidates.md, elections/2021-TOC/voters.yaml
This is MOST of the requirements for this election to work with Elekto.io.
The voters.yaml is currently empty, and will need to be populated however we're doing that (devstats or cauldron).
We will also need a webhook in this GH repo to notify elekto of changes (like new candidate profiles).
Yes, election_desc is a duplicate of what's in the README.  I'd like to keep it like that for now, because we haven't tried displaying such a long election brief in Elekto before, and it might turn out that I need to shorten it and redirect to the readme.
=> Add Elekto requirements for 2021 TOC election.

mechanics/TOC-REVIEW.schedule
Rather than keeping the schedule at the top of the Google doc, check it in so we can do automation (starting with https://knative.party/)
=> Check in initial TOC review schedule

peribolos/knative.yaml
I think this is the right place in peribolos to add myself as API WG approver 🤞. 
from [Requirements](https://github.com/knative/community/blob/main/ROLES.md#requirements-1):
- Reviewer of the codebase for at least 3 months: Reviewing in serving api since [May 2020](https://github.com/knative/serving/pull/7866)
- Primary reviewer for at least 10 substantial PRs to the codebase: 
- [**34 reviews tagged size/L**](https://github.com/knative/serving/pulls?page=2&q=is%3Apr+reviewed-by%3Ajulz+label%3Aarea%2Fapi+-author%3Ajulz+is%3Aclosed+label%3Asize%2FL)
-  picking 10 out: https://github.com/knative/serving/pull/11176, https://github.com/knative/serving/pull/10467, https://github.com/knative/serving/pull/11038, https://github.com/knative/serving/pull/9810, …
=> Add julz to API Approvers

mechanics/TOC.md
This PR amends the TOC charter to represent the current voting system.
For the 2021 TOC election, the voting system has been changed from CIVS to Elekto.
This change was [represented in the 2021 election documentation](https://github.com/knative/community/tree/main/elections/2021-TOC#voting-process), but the TOC charter had not been updated.
/kind bug
=> Update TOC to reflect changes in election system

peribolos/knative-sandbox.yaml
Signed-off-by: Matthias Wessendorf <mwessend@redhat.com>
Adding Ahmed here, for `eventing-kafka` repo. This PR is a suggestion based on comments of this original PR:
https://github.com/knative-sandbox/eventing-kafka/pull/527
=> adding Ahmed to eventing-kafka

OWNERS_ALIASES, peribolos/knative.yaml
mdemirhan@ is no longer in the Knative org; removing him from teams to avoid OWNERS failures.
=> Remove emeritus members from teams

peribolos/knative-sandbox.yaml, peribolos/knative.yaml
This is required to get https://prow.knative.dev/?job=ci-knative-prow-jobs-syncer and https://prow.knative.dev/?job=ci-knative-prow-auto-bumper-for-auto-deploy pass.
=> Add kntaive-prow-updater-robot to knative and knative-sandbox org

elections/2021-TOC/results.md
Adds a Results page for the 2021 TOC election.
@bsnchan @geekygirldawn  please approve.
=> Add results of 2021 TOC election to Elekto App.

peribolos/knative-sandbox.yaml
I would like to add `eric-sap` as an eventing-kafka approver.  @matzew has also indicated his agreement with this ; )
I'm not up-to-speed as to whether this is the correct config and whether anything else might be required - please advise if so - thanks!
=> Adding eric-sap as eventing-kafka approver

peribolos/knative-sandbox.yaml, peribolos/knative.yaml
We are using Knative as our serverless framework
I would like to get more involved with the Knative community :) 
I apply to join the Knative organization.
PRs: 
- knative/serving#11419
- knative/docs#3579
- knative/pkg#2098
-  knative/docs#3682 
Issues responded to
- knative/docs#3598
- knative/serving#11019
=> Add novahe to the members list

OWNERS_ALIASES, knative-sandbox-OWNERS_ALIASES
Updates release-leads and removes peterfeifanchen (ex-org member)
=> Regenerate OWNERS_ALIASES

mechanics/TOC.md
The current situation is silly :). Because, in the event of a TOC member resigning or leaving, the next in line from the previous election is used, folks are encouraged to run in elections for seats that - due to vendor limits - aren’t available to them, just for purposes of vacancies that may arise during the year. This year that has become even, frankly, sillier since an extra resignation has meant two such elections will be held in quick succession.
The current mechanic likely made sense when there were more independent vendors in the project, since in that case the situation was substantially less likely to arise. Now it seems like we'll quite commonly (possibly every election, unless the balance of contributions substantially changes, given the make-up of upcoming vacancies means all …
=> Revisit rules around what happens when a TOC member resigns

elections/2021-TOC/results.md
Updated Elekto results page with the final TOC election results, since we are not having a runoff.
@jberkus Can you have a quick look to make sure that this looks good to you and doesn't break anything in Elekto before we have someone from steering approve it?
/hold
=> Updated Elekto results page with the final TOC election results

peribolos/knative-sandbox.yaml, peribolos/knative.yaml
Add `bbtong` to the Knative members list, as part of VMware CNR Connectivity to eventually submit to Knative feature work.
I signed the VMware<>Google internal CCLA, as was advised to do that, but (VMware someone?) let me know if I still have to sign Google's CLA beyond it.
=> Add bbtong to the members list

mechanics/README.md
Add link to Consensus doc as its not linked from any of the pages that appear on the website.
- :gift: Add new feature
Related to [Knative GA/Licensable Requirement](https://docs.google.com/document/d/1mC_nDpLIycqiBn5Om1tvbcY3yyAR3WUNXcHiyloEzhg/edit#heading=h.lz2n48vymqzb)
=> Update README.md - Reference Consensus

peribolos/knative-sandbox.yaml
- :gift: Add kn-plugin-func entries for peribolos
Related: https://github.com/knative/community/issues/613
```release-note
Adds the kn-plugin-func repository for the `kn` CLI client, providing an opinionated and simple function development user experience for Knative.
```
**Docs**
It is unclear to me what needs to be done with docs for this change.
```docs
```
=> Add kn-plugin-func entries for peribolos

peribolos/knative.yaml
As per title. This tripped the nightly peribolos run.
Also sorted all names again.
=> Fix for @dolfolife's Github name update

peribolos/knative.yaml
This PR is to promote @snneji to approver for docs repo
@snneji  as far as I'm concerned it meets the [approver requirements](https://knative.dev/community/contributing/roles/#requirements-1)
Examples of contributions:
- Discussions on Slack
- Discussions and attendance on working group weekly meetings
- Review PRs
- Opening issues and initiate roadmap for docs changes
- Content contributions [PRs](https://github.com/knative/docs/pulls?q=is%3Apr+author%3Asnneji+)
/assign @omerbensaadon 
/assign @julz
=> add @snneji as approver/docs-writters

OWNERS_ALIASES, peribolos/knative.yaml
This PR is to promote @RichardJJG  to the approver for docs repo
@RichardJJG as far as I'm concerned it meets the [approver requirements](https://knative.dev/community/contributing/roles/#requirements-1)
Examples of contributions:
- Discussions on Slack
- Discussions and attendance on working group weekly meetings
- Review PRs
- Opening issues and start initiative of content templates
- Content contributions [PRs](https://github.com/knative/docs/pulls?q=is%3Apr+author%3ARichardJJG+)
/assign @omerbensaadon 
/assign @julz
=> Add RichardJJG as approver/docs-writter

peribolos/knative-sandbox.yaml
As per title. This currently fails the peribolos jobs. See https://prow.knative.dev/view/gs/knative-prow/logs/post-knative-sandbox-peribolos/1420676713062338560
=> Drop last occurrence of peribolos test repo

peribolos/knative-sandbox.yaml
- 🎁   Added travis-minke-sap and eric-sap as approvers to the control-protocol sandbox project.
/kind cleanup
Now that Francesco has left the Knative project, Eric and I are probably the primary consumers of the control-protocol and it would be good for us to be able to help maintain it, etc...
=> Add Travis and Eric from SAP to control-protocol approvers.

working-groups/WORKING-GROUPS.md
After changing teams and furthermore after 2.5 months of parental leave,
I just don't feel like I can contribute at the level this position
requires.
It's been a please and an honor serving in this position.
I will be still be around, still review code, and what not, but it's
120% project, than a full time job for me now.
Sorry, Markus, than I am increasing your workload, though probably temporarily :-)
Thanks, yours truly.
=> Remove @vagababov as Scaling WG lead

peribolos/knative-sandbox.yaml, peribolos/knative.yaml
We have an internal tool at Google called G3N to enable sending notifications to Googlers when issues and pull requests need  their attention, and it's based on GitHub webhooks. 
One feature it supports is also sending notifications to people in GitHub teams, but since the GitHub teams for Knative are only visible to Knative members, we need to create a bot account, add it to the Knative org, and use its token to query the GitHub APIs.
`g3n-github-robot` is the bot account we created, and we will only use its token to query the team members with the GitHub APIs.
=> Add g3n-github-robot account to the knative and knative-sandbox org

STEERING-COMMITTEE.md
Going on leave :'( - It's been a blast!
I suspect SC will leave the seat empty until the next steering elections in early October so the seat will remain empty for the timebeing.
=> Removes bsnchan from steering

elections/2021-SC/candidate-lance.md
I am throwing my hat in the ring for a seat on the Steering Committee. 
In my role as technical architect of the Boson Project - a project that brings a function-focused developer experience to Knative - I have been involved on the periphery of Knative since 2019. In the fall of 2021, the core of Boson Project's work was donated to Knative and now exists as a part of Knative Sandbox. I am the Function Task Force lead for this project, and guide the technical efforts towards achieving Functions as a first class citizen of Knative. To Knative core, I have over 200+ contributions primarily in documentation, samples and infrastructure. Outside of the Knative ecosystem, I have been active in the open source community for over a decade as a regular contributor to Node.js core and other widely …
=> add lance as candidate for the 2021 SC elections

mechanics/RELEASE-SCHEDULE.md
Update to 0.27 being 1.0, and add some more subsequent releases with the help of Googling "six weeks from ...".
K8s 1.20 will go into maintenance mode on on 2021-12-28 so looks like 1.2 will drop support for it.
=> Update release schedule

elections/2021-SC/README.md, elections/2021-SC/election.yaml, elections/2021-SC/election_desc.md
Add notes about the seperate process for the End User seat.
As discussed, while three seats will change in this election, only the two Contributing Seats will be elected via Elekto.  The remaining seat will be selected by the newly seated SC.  This clarifies both the README and the description.
/assign @geekygirldawn, @vaikas
=> Change the number of elected seats in this election properly to two.

OWNERS_ALIASES, TRADEMARK-COMMITTEE.md, peribolos/knative.yaml
/assign @omerbensaadon
/assign @pmorie
=> Replace Omer Bensaadon with Evan Anderson as VMware Trademark representative

.github/workflows/verify.yaml
Do it manually because the only thing knobots supports is a denylist, and it's too annoying to bother excluding every action except this single one.
If https://github.com/knative-sandbox/knobots/pull/99 was complete/merged this would be a lot easier, but unfortunately that's a dramatic refactoring that is now out of sync.
=> Add verify-codegen workflow

elections/2021-SC/README.md
0000 UTC is actually 4pm PST, not 5pm.  This was wrong in the README.
/assign @geekygirldawn
=> Fix the TZ conversion to PST.

OWNERS_ALIASES, knative-sandbox-OWNERS_ALIASES, peribolos/knative-sandbox.yaml, peribolos/knative.yaml, working-groups/WORKING-GROUPS.md
As per https://groups.google.com/g/knative-dev/c/gA3matxzBH4/m/zxQKWqkXAgAJ I'm stepping down from being Autoscaling WG lead. @julz is taking over in the interim.
I've included some other cleanups of my RBAC and only keep the TOC relevant bits. I'll hash out when to send the TOC updates together with the TOC.
/kind cleanup
/kind removal
/assign @evankanderson @dprotaso @rhuss @julz
=> Markus steps down as Autoscaling WG lead

peribolos/knative-sandbox.yaml
As @snneji is not in the member list in knative-sandbox, all community file updates PRs are failing with the error `snneji
User is not a member of the org. User is not a collaborator. Satisfy at least one of these conditions to make the user trusted.`.
e.g.
https://github.com/knative-sandbox/net-kourier/pull/733
https://github.com/knative-sandbox/net-istio/pull/834
/cc @csantanapr @snneji @evankanderson
=> Add @snneji to knative-sandbox members

peribolos/knative.yaml
https://prow.knative.dev/view/gs/knative-prow/logs/ci-knative-peribolos/1470075994139267072#1:build-log.txt%3A28 is the current failing run.
Issue is tracked in https://github.com/knative/community/issues/186.
cc @kimsterv
=> Remove kimsterv to fix peribolos CI runs

OWNERS_ALIASES, knative-sandbox-OWNERS_ALIASES, peribolos/knative-sandbox.yaml, peribolos/knative.yaml
We understand that @psschwei is a great candidate to be an approver for [docs git repository](https://github.com/knative/docs).  
The DUX Working Group would like to nominate @psschwei to be an approver and understand that it meets all the [requirements](https://github.com/knative/community/blob/main/ROLES.md#requirements-1) stated in our governance documentation for [ROLES](https://github.com/knative/community/blob/main/ROLES.md). 
@psschwei submitted the following PRs in the last 3 months (12):
1. knative/docs#4285
1. knative/docs#4260 
1. knative/docs#4299
1. knative/docs#4298
1. knative/docs#4333
1. knative/docs#4409
1. knative/docs#4412
1. knative/docs#4413
1. knative/docs#4431
1. knative/docs#4391
1. knative/docs#4442
1. knative/docs#4416
@psschwei have reviewed the following PRs in …
=> Add Paul Schweigert as docs approver (docs-writer)

CONTRIBUTING.md
- Change the link to docs contribution guide to [README in docs repo](https://github.com/knative/docs/blob/main/contribute-to-docs/README.md)
/kind <kind>
Fixes #881 
```release-note
NONE
```
**Docs**
```docs
NONE
```
=> Fix broken link to DOCS-CONTRIBUTING.md

mechanics/TOC.md
Per discussion with SC.  Specifically:
- replace "most votes" with "most preferred" to reflect the actual election mechanism
- make it clear that any replacement candidate serves the replaced members' term, regardless of how they were selected
please review: @geekygirldawn @vaikas
=> Clean up language around TOC vacancies

OWNERS_ALIASES, knative-sandbox-OWNERS_ALIASES, peribolos/knative-sandbox.yaml, peribolos/knative.yaml
Chris has contributed to Knative productivity since 2019, and he had made a lot of great achievements on improving Knative testing, specifically upgrade testing, conformance testing and the general testing infrastructure.
I believe he has met all the requirements from a long while ago, so nominating cardil@ as a productivity writer.
Also removing two Googlers that have left Knative.
/cc @vaikas @csantanapr 
FYI @cardil
=> Add cardil@ as productivity writer

knative-sandbox-OWNERS_ALIASES, peribolos/knative-sandbox.yaml
I'm not participating in eventing-rabbitmq anymore so just to avoid getting mentions from the team alias
=> remove myself from rabbitmq

mechanics/WORKING-GROUP-PROCESSES.md, working-groups/docs/CHARTER.md
As per the latest changes:
- [PROCESS CHANGE: Overhaul and standardize Knative roadmap processes · Issue #746 · knative/community](https://github.com/knative/community/issues/746)
- [community/ROADMAPS.md at main · knative/community](https://github.com/knative/community/blob/main/mechanics/ROADMAPS.md), 
Roadmaps should exist in a GitHub project board, and not in a Google drive. This PR updates places in this repo that were still referring to locations other than a project board.
<!--
In addition, categorize the changes you're making using the "/kind" Prow command, example:
Supported kinds are: api-change, bug, cleanup, deprecation, removal, documentation, enhancement, performance
=> 🧹Update roadmap links as per process change

OWNERS_ALIASES, peribolos/knative-sandbox.yaml, peribolos/knative.yaml
- Adding [mgencur](https://github.com/mgencur) to productivity reviewers.
- Adding missing Red Hat QE team members to Knative orgs
Martin has a long history of Knative contributions. He should be in productivity reviewers a long time ago.
=> Adding mgencur to productivity reviewers

google-summer-of-code/gsoc-2022.md
Described the idea for GSOC 22 following the template
https://github.com/knative/community/blob/main/google-summer-of-code/gsoc-2022.md#ideas
=> GSOC 22 Idea: Improve Knative Eventing Observability

OWNERS_ALIASES, knative-sandbox-OWNERS_ALIASES, peribolos/knative-sandbox.yaml, peribolos/knative.yaml
Both Krsna and Mahamed have been very active contributors for Knative productivity for the last 3 months, I propose adding them as productivity writers.
Also updating the config for `knative-sandbox` to keep it in sync with `knative`.
cc @kvmware @upodroid 
/cc @vaikas @csantanapr
=> Add Krsna and Mahamed as productivity writers

OWNERS_ALIASES, knative-sandbox-OWNERS_ALIASES, peribolos/knative-sandbox.yaml, peribolos/knative.yaml, working-groups/WORKING-GROUPS.md
As already announced [here](https://groups.google.com/g/knative-dev/c/IqlSNL7jvdo) , it's time to for me to return back to the observer seat. 
/kind cleanup
/kind removal
I also suggest that we shutdown the Eventing Kafka WG. Right now it has no leads and I'm not sure if @pierDipi or @matzew would be willing to keep it up. But I feel that's a followup after this PR.
/assign @evankanderson @dprotaso @rhuss @n3wscott
=> Ahmed stepping down from eventing and eventing-kafka wg leads and approvers

peribolos/knative-sandbox.yaml, peribolos/knative.yaml
Fixes #954
I'm also removing `julz` from the admin memberships, and switching him to a normal member.
Note that I'm _not_ adding them to any teams right now (including the "admin" teams), because I think they may need to accept the org invite before being eligible to be added to teams, and Peribolos will complain if I try to do both steps at once.
I'm also not removing the `google` bots yet, but I expect that will probably happen one of these days.
=> Add caniszczyk and thelinuxfoundation as org OWNERS

OWNERS_ALIASES, peribolos/knative.yaml
This is causing presubmit test failures in https://github.com/knative/infra/pull/2
/cc @dprotaso @kvmware
=> remove efiturri who's not working on Knative anymore

groups/README.md, groups/committee-code-of-conduct/groups.yaml, groups/committee-oversight/groups.yaml, groups/committee-trademark/groups.yaml, groups/config.yaml, groups/wg-productivity/groups.yaml
Follow up from #905
The prowjob is broken intentionally, but I'll fix it once the PR is merged. After that point, GSuite must be managed through this repo.
﻿
- Reconciled the current group membership, trademark committee added some new members.
- https://prow.knative.dev/?repo=knative%2Fcommunity
=> Reconcile GSuite Groups

groups/committee-oversight/groups.yaml, groups/committee-trademark/groups.yaml, groups/wg-productivity/groups.yaml
Looking at the declared GSuite groups, they seem to include a number of former members. Remove them (and add more current TOC members to the wg-productivity list).
/assign @dprotaso 
since he noticed it
=> Clean up GSuite groups

groups/wg-productivity/OWNERS, groups/wg-productivity/groups.yaml
Many of the `wg-productivity` members listed are not currently working on Knative. Sub in new TOC members to the list instead (though we might consider removing them until they need the access -- it's unclear what the emergency fix scenario might be without them having this access).
Add TOC as permitted to manage wg-productivity memberships.
=> Update productivity group membership

TECH-OVERSIGHT-COMMITTEE.md, mechanics/TOC.md
According to the Steering Committee Decision from [2021-01-13](https://docs.google.com/document/d/16Rpd2nhmLWrkFJUfpJ31Ox2PpultJ-bYIhqaiWQff_I/edit#bookmark=id.xjuz3b7bsrv1), Matt replaces Julz as TOC member until the end of the Term 2022.
Also, clarified in the TOC election rules, that a TOC replacement's within the last 3 months to an election lasts only until this election.
=> Add Matt as TOC Member, clarified TOC election rules

peribolos/knative-sandbox.yaml
We have re-usable workflows in https://github.com/knative/actions
related: https://github.com/knative/community/issues/324
=> drop the unused actions-kind repo

peribolos/knative.yaml
The GitHub user updated their username and caused peribolos to fail, see the context in https://github.com/knative/test-infra/issues/3247.
For now removing them to unblock peribolos.
/cc @dprotaso @evankanderson
=> Remove aryann from the knative peribolos config

peribolos/knative-sandbox.yaml
This patch adds @RamyChaabane to knative-sandbox members.
@RamyChaabane is actively contributing on net-kourier repo and has already several commits.
Please see: https://github.com/knative-sandbox/net-kourier/commits?author=RamyChaabane
His contribution has already meet the [member requirements](https://github.com/knative/community/blob/main/ROLES.md#requirements).
Note, I have already gotten the consent from @RamyChaabane on Slack about adding him to the members.
=> Add @RamyChaabane to sandbox members

mechanics/SC.md, mechanics/TOC.md
Changes include:
* Updated the devstats link for voter eligibility now that we are under the main CNCF devstats instance
* updated the format of the election directories to match the format used by Elekto
* added a note that the steering committee may delegate election officer duties for the TOC since that is what we have been doing for the past 2 elections.
=> Several updates with minor changes to the TOC election process

elections/README.md
This doc was WAY out of date, so I mostly re-wrote the entire election doc to reflect how we are actually conducting elections, including:
* Updating to cover both TOC and SC elections
* Removing mentions of CIVS and replacing with the current Elekto process
* Added responsibilities for election officers
=> Updating main election README to reflect how we are actually conducting elections

peribolos/knative-sandbox.yaml, peribolos/knative.yaml
This bot will be part of the CNCF Community Infrastructure team tooling. No changes will be introduced to the project via this bot, only strategic observations and suggestions.
=> Add @cncf-ci to Knative Community

elections/2022-TOC/README.md, elections/2022-TOC/election_desc.md
I didn't realize that we'd moved the knative instance of Elekto to https://elections.knative.dev/ from the test instance, so I've fixed all of the links in the README and election_desc used within Elekto.
=> Fixed links to Elekto

elections/2022-TOC/election.yaml, elections/2022-TOC/nomination-template.md
... per discussion with Steering on Slack.
This elections configuration update does two things:
1. Configures "affiliations" and "owners" fields as the visible fields on candidate profiles
2. Adds an "owners" field to the candidate profile
Reason: being named as an Approver in one or more Owners files is a requirement to run for TOC.  Since there is no master index of Owners files for Knative, EOs and voters need this info to validate candidate eligibility.
=> Add OWNERS file field to candidates template

peribolos/knative.yaml
Adds @lkingland @matejvasek and @zroubalik to knative org
=> chore: add original boson contributors to knative

elections/2022-TOC/candidate-dsimansk.md
Hello everyone!
I'm David. Currently I'm one of Client WG leads.
I've started my Knative journey as an active contributor since the beginning of 2020, focusing mainly on the CLI and its plugins.
Over time I was able to rank up through approver role to WG lead. From other areas I occasionally get involved in productivity/CI
related issues, I kind of enjoy searching for a needle in the haystack.   
The Knative client is the first point of contact for users and is at the heart of the Knative user experience. Also, it's a perfect starting point for new Knative contributors as it constantly offers some entry-level challenges.
With the candidacy to TOC, I'd like to expand my reach in the community. There're two objectives I'd like to focus on. First to bring in the client-side perspective to …
=> Add dsimansk as 2022 TOC candidate

elections/2022-TOC/canidate-n3wscott.md
Hello! I am Scott.
I have been contributing to Knative since initial public launch. In that time I
held the role of Sources Working Group Lead, as well leading the Productivity
Working Group during a time of uncertainty. I was a core contributor to Eventing
and was also a key member reconciler framework and generator code. I am a
maintainer on the CloudEvents Go SDK, a foundational component of Eventing. I
have most recently been serving on the Knative TOC, and helped in the planning
committee with our very first KnCon Day Zero event (!!!HYPE!!!).
I care deeply about the direction and future of Knative as a project. It is
vitally important to continue the work we are doing in Knative to level the
playing field for all of the Cloud Native landscape to make Cloud Computing more
accessible …
=> Adding Scott as 2022 TOC candidate

elections/2022-TOC/candidate-psschwei.md
Hi, I'm Paul. I've been involved in a number of areas in the Knative project since I joined the
community. I'm most active in Autoscaling, where I built the Container Freezer functionality and
am more generally working on various ways to reduce cold start latencies. I'm a frequent
contributor to the Serving and Docs/User Experience areas; have done more focused work on client plugins,
productivity, and security; and am an approver and/or reviewer for multiple areas. I was also a
release lead for the 1.3 release.
What I love about Knative is how much easier it makes it for developers to run their applications on
Kubernetes. I'm running for the TOC for two main reasons: (1) to help carry that message out to the broader
community and to help grow the project (both in terms of features and …
=> Add Paul as TOC candidate

elections/2022-TOC/candidate-dprotaso.md
Hey everyone. I'm a current TOC member and Serving Lead. I've been contributing 
to the project (in many of it's areas) since 2017 - before it was called Knative. 
With the CNCF donation we're at an exciting step in the project's journey. I'm seeing
more engagement from end-users and new contributors. This year I hope to support 
existing WG leads and to help new contributors onboard onto the project.
=> Add dprotaso as 2022 TOC Candidate 

peribolos/knative-OWNERS_ALIASES, peribolos/knative-sandbox-OWNERS_ALIASES, peribolos/knative-sandbox.yaml, peribolos/knative.yaml
- 🧹 Remove `antoineco` from groups and owner aliases
I haven't been quite as active as I used to be lately and, because I will soon be pursuing new challenges where Knative is unfortunately not in the picture, now is my time to say good bye to all of you 👋
Working with Knative has always been a great pleasure for me. In fact, one of the main reasons for me to join TriggerMesh two years ago was to remain active in the project!
I wish you all a lot of success with Knative, it is certainly in very capable hands.
/kind cleanup
/kind deprecation (🥲)
=> Remove antoineco

peribolos/knative-sandbox.yaml
This patch adds @norbjd to knative-sandbox members.
@norbjd is actively contributing on net-kourier repo and has already several commits.
Please see: 
- https://github.com/knative-sandbox/net-kourier/commits?author=norbjd
(also in eventing-natss)
- https://github.com/knative-sandbox/eventing-natss/issues/created_by/norbjd
- https://github.com/knative-sandbox/eventing-natss/pulls/norbjd
His contribution has already meet the [member requirements](https://github.com/knative/community/blob/main/ROLES.md#requirements).
Note, I have already gotten the consent from @norbjd on Slack about adding him to the members.
=> Add @norbjd to sandbox members

mechanics/SC.md, mechanics/TOC.md
This PR adding that SC, TOC, and Trademark Committee members are eligible to vote regardless of the number of contributions for TOC and SC elections. Every year, we have several committee members who make significant contributions, but who don't hit the 50 devstats contributions. Rather than making them file exception requests for every election, I think we should just make them eligible by default.
This change requires SC approval. 
/hold
=> Proposing that SC, TOC, and Trademark Committee members should be eligible to vote.

groups/reconcile_test.go, groups/service_test.go
There is a breaking change in go 1.18 that needs to be fixed.
Details: https://github.com/golang/go/issues/47641
Errors: #1090 
/cc @dprotaso 
/kind cleanup
=> Fix Error Wrapping Verb for go 1.18

peribolos/knative-OWNERS_ALIASES, peribolos/knative-sandbox-OWNERS_ALIASES, peribolos/knative-sandbox.yaml, peribolos/knative.yaml, working-groups/WORKING-GROUPS.md
Mahamed has been essential to managing the infrastructure and a key person in Productivity in general. He already is an approver for productivity and has previously been nominated by Chi as well.
=> Nominate Mahamed Ali as Productivity WG Lead

working-groups/WORKING-GROUPS.md, working-groups/functions/CHARTER.md
Adds Functions as a distinct working group outside of the Client. It does not remove existing peribolos settings for kn-plugin-func.
=> Create a Functions WG

groups/groups.yaml, groups/groups_test.go, groups/restrictions.yaml
I'm looking to verify our GitHub organization as per https://docs.github.com/en/enterprise-cloud@latest/organizations/managing-organization-settings/verifying-or-approving-a-domain-for-your-organization.
As part of that, we can't have [knative-admins@googlegroups.com](mailto:knative-admins@googlegroups.com) address at https://github.com/knative as we don't own googlegroups.com. I made a new group and added steering and toc to it.
Also, mail delivery is now enabled on knative.dev so we can receive emails on that domain 🎉 
/cc @csantanapr
=> Add new `admins@knative.dev` google group

peribolos/knative-OWNERS_ALIASES, peribolos/knative.yaml
Seems to be required for: https://github.com/knative/community/pull/1032
=> Add functions working group teams to peribolos

CONTRIBUTING.md
Simple update to the contributing doc, pointing to the EasyCLA page now.
/kind chore
=> chore: change Google CLA to EasyCLA in contributing guide

groups/groups_test.go, groups/restrictions.yaml, groups/wg-productivity/groups.yaml
Part of https://github.com/knative/test-infra/pull/3409
We recently added knative.dev and I want to use this domain for GCP RBAC groups that never needed emails before. Looks better than .team domain.
I also added Nader's email so he can get access to the clusters.
/hold I will need to rename groups in the console before merging as I don't want new groups being made. FYI, when a google group email is changed, the IAM bindings will still be there but the new address will be shown in the IAM policy.
/cc @kvmware
=> Add new GKE RBAC group for a new cluster

README.md
Signed-off-by: Daniel Krook <krook@us.ibm.com>
- Fixed link to the moved samples folder
- Fixed link to contribution guidelines
No issue opened as the pull request only includes two link fixes.
=> Fixed links to samples and contribution guidelines.

TRADEMARK-COMMITTEE.md, peribolos/knative.yaml
/assign @thisisnotapril
(For Mark; Simon's assignment was already done in the `knative/peribolos.yaml` file for ACLs, but not at the top-level charter doc.)
=> Update Trademark composition

peribolos/knative-sandbox.yaml, peribolos/knative.yaml
Signed-off-by: Dirk Haubenreisser <haubenr@de.ibm.com>
This PR adds the GH user ID 'haubenr' to the knative and knative-sandbox projects member list.
'haubenr' (myself) is the current knative maintainer for the IBM zSystems (aka s390x) platform.
=> Added member haubenr

peribolos/knative-OWNERS_ALIASES, peribolos/knative-sandbox-OWNERS_ALIASES, peribolos/knative-sandbox.yaml, peribolos/knative.yaml
The previous add caused issues because of a name collision and was reverted. This re-adds without the collision.
=> Re-add productivity wg leads to admin.

peribolos/knative-sandbox-OWNERS_ALIASES, peribolos/knative-sandbox.yaml
- Adding chzhyang as an approver for the knative-sandbox/kperf repo
My contributions to Kperf could be found here: https://github.com/knative-sandbox/kperf/pulls?q=is%3Apr+is%3Aclosed+author%3Achzhyang, including:
- Added the load command to kperf
- Added config file support to kperf
- Bug fixes
- PRs review
I will continue to enhance kperf in the future.
/cc @maximilien @psschwei
=> Add chzhyang to kperf approvers

.github/ISSUE_TEMPLATE/new-repo.md
Signed-off-by: Paul S. Schweigert <paulschw@us.ibm.com>
From [discussion in slack](https://knative.slack.com/archives/CCSNR4FCH/p1659977234489749), turns out we need to request that each new repo get added to EasyCLA. This PR adds that step to the new repo checklist.
/assign @lance
=> Add EasyCLA step to new repo checklist

peribolos/knative-OWNERS_ALIASES, peribolos/knative-sandbox-OWNERS_ALIASES, peribolos/knative-sandbox.yaml, peribolos/knative.yaml, working-groups/WORKING-GROUPS.md
Adding myself as a working group lead for serving.
Evidence of having met requirements:
Noted as on track for lead in the [July 28 WG update](https://docs.google.com/presentation/d/1IUa4Jn4d-PkdFbHLBt_aZ5EOrxMTSVQx3j6FNgf8ay4/edit#slide=id.g3fc1c3445b_0_31) by @dprotaso (current WG lead)
Approver since [May 11, 2022](https://github.com/knative/community/pull/1045)
Member since [May 14, 2021](https://github.com/knative/community/pull/606)
Serving PRs: https://github.com/knative/serving/pulls?q=is%3Apr+author%3Apsschwei+
Serving Reviews: https://github.com/knative/serving/pulls?q=is%3Apr+reviewed-by%3Apsschwei+
Am a [reviewer](https://github.com/knative/serving/blob/5bba016c00941c1266b9e7bd50f3c5f90154417b/OWNERS_ALIASES#L177) …
=> Add psschwei as serving WG lead

peribolos/knative-sandbox.yaml, peribolos/knative.yaml
added myself as sandbox member:
- I'm active in [user group](https://groups.google.com/g/knative-users/)  (Andrey Stelmashenko, astelmashenko@viax.io, using corporate account there)
- requested subscription in [dev group](https://groups.google.com/g/knative-dev?pli=1)
- made a PR regarding [tracing propagation](https://github.com/knative-sandbox/eventing-natss/pull/342) and going to do more, because k8s native technologies are interesting to me (I promoted knative in a company where I work)
=> added astelmashenko as Knative Sandbox member

peribolos/knative-sandbox-OWNERS_ALIASES, peribolos/knative-sandbox.yaml
We have not found bandwidth to move the repo yet, and the fact that the
teams/groups are out of sync with reality needs to be addressed in the
meantime. This commit shifts ownership from the client to the functions
working group in knative-sandbox and introduces working group leads for
the two function repositories (kn-plugin-func and func-tastic). And incidentally
removes Omer from the committers list.
=> chore: remove func from knative org in peribolos

peribolos/knative-sandbox-OWNERS_ALIASES, peribolos/knative-sandbox.yaml
Like the other kn plugins, bringing quickstart over to the client WG
xref: https://github.com/knative-sandbox/knobots/pull/233
/assign @dsimansk 
FYI @rhuss @navidshaikh
=> Add cli leads to quickstart approvers

working-groups/WORKING-GROUPS.md
Updates the time of the alternate Serving WG meeting to 5pm PT (corresponding update has already been made to the calendar)
=> Update time for alternate serving meeting

STEERING-COMMITTEE.md
Since the end user seat is appointed, I created a separate section to move the end user seat info out of the election section of the SC document and into a separate end user seat section to make it more clear that the EU seat is not part of the election. This is the reduce the confusion from last year about the end user seat. There is additional discussion about this issue as part of PR #1171 
/hold
This PR requires approval from the @knative/steering-committee 
cc: @jberkus @upodroid @vaikas
=> Moved EU Seat info out of the elections section

peribolos/knative-OWNERS_ALIASES, peribolos/knative-sandbox-OWNERS_ALIASES, peribolos/knative-sandbox.yaml, peribolos/knative.yaml
This commit moves knative-sandbox/kn-plugin-func and the team members over to knative/func.
See: https://github.com/knative/community/issues/1169
=> chore: add entries for knative/func

STEERING-COMMITTEE.md
Removed the hard deadline of Dec 1 for new SC members to take office, since that will always be difficult due to the US Thanksgiving holiday timing. Changed it to be less specific, but still in December, and tied to the date of the election announcement to give us a little more flexibility.
This change requires approval from @knative/steering-committee 
cc: @jberkus 
/hold
=> Changed deadline for new SC members to take office

working-groups/WORKING-GROUPS.md
Corrected links to Slack, GitHub repository, and roadmap.
/kind chore
=> chore: update functions working group info

peribolos/knative-OWNERS_ALIASES, peribolos/knative-sandbox.yaml, peribolos/knative.yaml
As discussed in [Slack](https://knative.slack.com/archives/CCSNR4FCH/p1666360097149169), there's an inactive member who never accepted the invite to the org, which is causing problems with the owners files in the func repo. As the person has had no github activity in over a year (and also no knative activity), this PR drops that person from the org list.
cc @lance @upodroid
=> Removes inactive member to fix func owners issue

peribolos/knative-OWNERS_ALIASES, peribolos/knative.yaml
Mark was added to TM in PR #1105, this adds that change to peribolos.
This also fixes a blocker for functions: https://github.com/knative/func/pull/1342#issuecomment-1296432869 
cc @mchmarny
=> Updating peribolos with TM committee changes

peribolos/knative-OWNERS_ALIASES, peribolos/knative-sandbox-OWNERS_ALIASES, peribolos/knative-sandbox.yaml, peribolos/knative.yaml, working-groups/WORKING-GROUPS.md
Makes a couple of updates to the emeritus sections of a couple of working groups:
* moves @julz to emeritus section for security (also removes him from peribolos)
* adds the dates for @lionelvillard 's time as lead of eventing sources
=> Updates to security / eventing sources emeritus tables

peribolos/knative.yaml
id like to join the community because i make contributions to Knative Functions
(such as https://github.com/knative/func/pull/1118
https://github.com/knative/func/pull/1415 )
and work with the one and only, great @zroubalik
=> please let me in

elections/2022-SC/candidate-smoser-ibm.md
fix typo in format for Elekto - name field in the yaml file should be lowercase
=> Fixing smoser-ibm candidate profile format

working-groups/WORKING-GROUPS.md
With nak3 stepping down there's currently no networking lead. Merging the two working groups addresses this gap.
/hold for @knative/technical-oversight-committee discussion
=> Merge serving and networking working groups

elections/2022-SC/voters.yaml
changed the case for AngeloDanducci's voters.yaml gh id as a workaround to the Elekto case bug to allow voter eligibility in Elekto
=> voters.yaml update for AngeloDanducci

elections/2022-SC/voters.yaml
Fixed the remainder of the eligible voters that didn't match the case of their GH login with the voters.yaml file to get around the bug in Elekto.
=> Fixed GH login case for several users in voters.yaml

peribolos/knative-sandbox.yaml, peribolos/knative.yaml
This PR adds a new member to knative and knative-sandbox projects: Dilip Bhagavan (dilipgb)
Dilip will be my successor as the primary maintainer for the IBM zSystems (aka s390x) platform. I will phase out of this role shortly (once that happens, another PR removing my ID from the member lists will follow).
=> Added new IBM zSystems maintainer for knative projects

google-summer-of-code/README.md, google-summer-of-code/gsoc-2023.md
- Add initial content for GSoC 23
- As we're participating GSoC part of CNCF, added information to clarify
- The ideas page is merely for collection of ideas from the community until CNCF launches their GSoC efforts. Later on, the same ideas will be moved to CNCF repository https://github.com/cncf/mentoring/tree/main/summerofcode. I prefer not to wait until then though.
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```
=> Add initial content for GSoC 23

peribolos/knative-sandbox.yaml, peribolos/knative.yaml
Doing this as a precaution
/assign @evankanderson 
Email from GitHub
> Hi dprotaso,
> 
> We’re writing to let you know that we observed suspicious activity that suggests a threat actor accessed your GitHub organization through a compromised organization member or outside collaborator account and downloaded private repository metadata.
> 
> We are in the process of notifying all identified affected users and organizations and revoking associated credentials.
> 
> * What happened *
> 
> We do not believe the attacker obtained these tokens via a compromise of GitHub or its systems, because the tokens in question are not stored by GitHub in their original, usable formats. At this time, evidence suggests that the threat actor(s) used compromised organization member and/or outside collaborator …
=> drop alexellis due to compromised tokens

peribolos/knative-sandbox.yaml
This repo isn't used and superseded by client-pkg repo
/assign @dsimansk
=> dropping unused repo - kn-plugin-source-pkg

peribolos/knative-sandbox-OWNERS_ALIASES, peribolos/knative-sandbox.yaml
As per title, this patch adds @nak3 to net-kourier approver.
[Requirements]( https://github.com/knative/community/blob/main/ROLES.md#approver) are met as:
- https://github.com/knative-sandbox/net-kourier/pulls?q=is%3Apr+assignee%3Anak3+is%3Aclosed (more than 3 months.)
- https://github.com/knative-sandbox/net-kourier/commits?author=nak3
- https://github.com/knative/community/blob/main/peribolos/knative-OWNERS_ALIASES#L97
- https://github.com/knative-sandbox/net-kourier/pull/949#issuecomment-1397414620
=> Add myself to net-kourier approver

elections/2022-SC-EU/candidate-puerco.md
Adding Adolfo García Veytia's profile from Chainguard as a candidate for the EU elections.
Signed-off-by: Adolfo Garcia Veytia (puerco) <puerco@chainguard.dev>
=> Add Chainguard/puerco nomination for the EU seat

peribolos/knative.yaml
@psschwei PTAL. I've just noticed that `admins` should definitely `admin` the repo.
=> Fix permissions for .artifacthub repo

groups/OWNERS, groups/groups_test.go, groups/wg-productivity/groups.yaml
Removing some inactive users from the productivity groups.
/assign @kvmware
=> remove inactive members from prod group

peribolos/knative-OWNERS_ALIASES, peribolos/knative-sandbox-OWNERS_ALIASES, peribolos/knative-sandbox.yaml, peribolos/knative.yaml
- add @pradnyavmw as a serving reviewer
- add @KauzClay @ReToCode @skonto to a new triage team so they can triage issues as part of the community rotation (https://github.com/knative/serving/pull/13703)
- sort member lists so it's alphabetical
/assign @evankanderson (since paul's out)
=> update serving teams

.github/ISSUE_TEMPLATE/new-repo.md
Let's point to CNFC Slack channel in our `new-repo` template.
- :bug: Update Slack link in new repo template
=> Update Slack link in new repo template

label_sync/labels.yaml
We should be using 'good first issue' instead. As that's what the prow `HELP` plugin uses
See prow commands
https://prow.knative.dev/command-help
=> drop kind/good-first-issue label

STEERING-COMMITTEE.md
Also moves @itsmurugappan to emeritus
/lkind documentation
Related: https://github.com/knative/community/issues/1265
=> docs: update STEERING-COMMITTEE.md with @puerco

peribolos/knative-sandbox.yaml, peribolos/knative.yaml
-
-
-
/kind <kind>
Fixes #
```release-note
Add @kahirokunn to members
```
**Docs**
```docs
Add @kahirokunn to members
```
=> Add @kahirokunn to members

peribolos/knative.yaml
- :gift: Creation of `knative/toolbox` repo
Fixes https://github.com/knative/community/issues/1291
=> :gift: New Repo: `knative/toolbox`

groups/wg-security/groups.yaml
Follow up to #1312, dropping myself from the security mailing list in favor of David. Also dropping julz, as he's no longer active here.
=> Drop paul, julz from security mailing list group

STEERING-COMMITTEE.md, peribolos/knative-OWNERS_ALIASES, peribolos/knative.yaml
:broom: Fix @puerco affiliation in `STEERING-COMMITTEE.md`
:broom: Offboard @itsmurugappan from SC group and move their entry to members list (thank you!)
:broom: Add @puerco to SC and org admins list 
Part of https://github.com/knative/community/issues/1265
Supersedes #1267
/cc @salaboy @csantanapr 
Signed-off-by: Adolfo García Veytia (Puerco) <puerco@chainguard.dev>
=> Fix @puerco affiliation and add to peribolos group configs

peribolos/knative-sandbox.yaml, peribolos/knative.yaml
- Add `dsimansk` and `zroubalik` to admin group
Per Slack thread: https://cloud-native.slack.com/archives/C04LY4M2G49/p1680518153699939
/hold
Adding hold for TOC or Steering members to check.
/cc @knative/steering-committee @knative/technical-oversight-committee 
/cc @zroubalik
=> Add `dsimansk` and `zroubalik` to admin group

working-groups/WORKING-GROUPS.md
As discussed in yesterdays eventing [WG call](https://docs.google.com/document/d/1Xha-FeunojN49OJN7W0WBnPMcRtp1ycYpbkiir6XsE0/edit#heading=h.971zl4s8d35p), we would merge the eventing-kafka WG back into the eventing WG. This has the following reasons:
* no WG lead for eventing-kafka ATM
* no activities in this WG over the last months
/assign @knative/technical-oversight-committee
/assign @knative/eventing-wg-leads
=> Merge eventing-kafka and eventing working groups

elections/README.md, mechanics/SC.md
Removed references to CIVS, since we're no longer using it for any elections. This is just some minor cleanup while we prepare for the TOC election.
=> Removed references to CIVS

peribolos/knative-sandbox.yaml
Request to join as Member for Knative Sandbox
Request to join as Member for Knative Sandbox
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```
=> Add @pymhq as Member for Knative Sandbox

ROLES.md
Fix two broken links in ROLES.md
- Expect correct links
- https://github.com/knative/community/blob/main/peribolos/knative.yaml 
- https://github.com/knative/community/blob/main/peribolos/knative-sandbox.yaml 
- Current links, which route to empty page instead of right one
- https://github.com/knative/community/blob/peribolos/knative.yaml
- https://github.com/knative/community/blob/peribolos/knative-sandbox.yaml
/documentation <kind>
Fixes #
```release-note
```
**Docs**
```docs
```
=> Fix two broken links in ROLES.md

peribolos/knative-sandbox-OWNERS_ALIASES, peribolos/knative-sandbox.yaml
Fixes: https://github.com/knative/community/issues/1349 
Fixes: https://github.com/knative/community/issues/1348
=> drop archived repos and associated teams

peribolos/knative-sandbox.yaml, peribolos/knative.yaml
I'm adding myself as a Knative and Knative-sandbox member so I don't need to use `ok-to-test` labels to run the tests.
My contributions so far have been:
- https://github.com/knative/eventing/pull/6978
- https://github.com/knative-sandbox/eventing-kafka-broker/pull/3114
=> add Leo6Leo as member

peribolos/knative-sandbox.yaml, peribolos/knative.yaml
Add my GitHub username to members in `knative.yaml` and `knative-sandbox.yaml`
=> Add myself to members in `knative.yaml` and `knative-sandbox.yaml`

elections/2023-TOC/results.md
As suggested in https://github.com/knative/community/tree/main/elections#process, publishing 2023 TOC election results, so that it shows up in Elekto properly.
Text copied from the SC announment.
=> 2023 TOC election results

TECH-OVERSIGHT-COMMITTEE.md
Adds @kvmware to the TOC doc and moves @evankanderson to emeritus status.
=> chore: update TOC member status

groups/wg-productivity/groups.yaml
/cc @kvmware @dprotaso @evankanderson @psschwei
I configured @knative-prow-updater-robot's email to be automation+prow-updater-robot@knative.team but the group wasn't receiving public emails. This change should fix it.
=> Allow anyone to send emails to `automation@knative.team`

ADOPTERS.MD
At Y Meadows we use KNative internally for our workflow automation application. Each step in our workflow is a call to a KNative Service using KNative Serving. This way we can use any Docker container to build a step and it works when needed and scales to zero when not in use.
- Adding Y Meadows to the adopters list. We use KNative Serving for our workflow automation platform. Each step is actually a call to a KNative Service.
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```
=> Add Y Meadows to ADOPTERS.MD

.github/ISSUE_TEMPLATE/ADOPTERS.yaml
Adds an issue template as a form which prompts for the information required to add an entry to ADOPTERS.md
Here is how it will look when you click the "New Issue" button.
And if you choose "Let us know you are using Knative" you see this form.
Live link: https://github.com/lance/community/issues/new/choose
Fixes: https://github.com/knative/community/issues/1358
/cc @knative/steering-committee
=> Add issue form for ADOPTERS.yaml

ROLES.md
This is a first pass at rewriting the ROLES.md document to more accurately reflect the reality of the roles and responsibilities in the knative and knative-sandbox GitHub organizations. I have based these changes, in part, on the CNCF Ladder template found here:
https://github.com/cncf/project-template/blob/main/CONTRIBUTOR_LADDER.md
Major changes include the addition of a Contributor role, which grants no explicit privileges, combination of the Technical and Execution lead roles for Working Groups into a single Working Group Lead role, and the removal of the Scribe role, which appears to be more aspirational than anything else.
I have removed the Requirements, Privileges, and Scope sections from the summary table so that it reflects simply the Responsiblities of each role, with details …
=> update ROLES.md to more accurately reflect reality

TRADEMARK-COMMITTEE.md, groups/committee-trademark/groups.yaml, peribolos/knative-OWNERS_ALIASES, peribolos/knative.yaml
Since Trademark seats are based on company affiliation, hand off the VMware seat to Sameer now that I've left VMware.
=> Hand off VMware trademark seat to Sameer

peribolos/knative-OWNERS_ALIASES, peribolos/knative.yaml
- Adding @nak3 , @skonto and @ReToCode as reviewers + writers to knative/docs
Docs is without a working group lead and current approvers are not really active anymore, so PRs pile up or take a long time to be merged. We would like to help out.
/assign @dprotaso, @psschwei
=> adding skonto, nak3 and retocode as docs reviewers+writers

peribolos/knative-sandbox.yaml
- Adding myself, @dan-j, as a member of the knative-sandbox org.
I have contributed NATS JetStream support to the eventing-natss repo, and would like to continue maintenance in the long term.
=> adding dan-j as knative-sandbox member

peribolos/knative-extensions-OWNERS_ALIASES, peribolos/knative-extensions.yaml
Add Eventing team at VMware to the RabbitMQ Eventing project
=> Update eventing-rabbitmq maintainers

peribolos/knative-OWNERS_ALIASES, peribolos/knative-extensions-OWNERS_ALIASES, peribolos/knative-extensions.yaml, peribolos/knative.yaml
Adding myself as an eventing approver.
From [ROLES.md](https://github.com/knative/community/blob/main/ROLES.md#approver):
**Requirements**
* Reviewer of other people's contributions for about 3 months :heavy_check_mark: 
* Should have reviewed or contributed to non-trivial PRs: https://github.com/knative/eventing/pulls?q=is%3Apr+author%3Acreydr+-label%3Asize%2FS+-label%3Asize%2FXS+-label%3Asize%2FM+is%3Aclosed+
* Nominated by a Working Group Lead with no objections from other leads: CC @pierDipi as eventing WG lead
/cc @pierDipi
=> Add creydr as eventing approver

TECH-OVERSIGHT-COMMITTEE.md, peribolos/knative-OWNERS_ALIASES, peribolos/knative-extensions-OWNERS_ALIASES, peribolos/knative-extensions.yaml, peribolos/knative.yaml
=> Zbynek stepping down from TOC

peribolos/knative-OWNERS_ALIASES, peribolos/knative.yaml, working-groups/WORKING-GROUPS.md, working-groups/functions/CHARTER.md
This commit updates the working group lead information for Knative Functions, naming @lkingland as the lead in place of @lance who will be stepping down from the lead role.
Also corrects the project link in the Functions working group charter document.
=> Update function working group lead

groups/wg-productivity/groups.yaml
/cc @kvmware @ReToCode 
This change should allow you access to the perf namespace in the shared GKE cluster in the knative-community gcp project.
=> give retocode access to perf tests

mechanics/GOLANG-POLICY.md
The version in the go.mod file is the min go version required to
build the repository. We should always be using the new version
of the tool chain
Dropping this clause is a reflection of what we are doing today
=> Drop the go policy consistency clause

groups/groups.yaml
Updates WG Lead and calendar maintainer emails list to include @lkingland (see also #1413)
=> Add lkingland to WG leads and calendar maintainers

peribolos/knative-extensions.yaml
Per my previous PR adding David to TOC charter. I've noticed admin groups for our organization don't match.
/cc @knative/technical-oversight-committee 
/cc @knative/productivity-leads
=> Align org admins of knative and knative-extensions

peribolos/knative-extensions-OWNERS_ALIASES, peribolos/knative-extensions.yaml
- This PR proposed to create a new repo called serving-progressive-rollout to implement an extension rolling out the serving revision progressively.
/kind <kind>
Fixes #1434
```release-note
```
**Docs**
```docs
```
=> Propose to create the new repo serving-progressive-rollout

.github/ISSUE_TEMPLATE/new-repo.md
- No need to configure EasyCLA per repo
- Knobots shouldn't be optional - this updates the community files
=> Update new repo template

.github/workflows/verify.yaml, elections/2023-SC/election.yaml, elections/2023-SC/election_desc.md
- Set voter contributions to 25 according to https://github.com/knative/community/pull/1448#issuecomment-1764630282
- Update table to bullet-points because elekto cannot render markdown tables (see https://cloud-native.slack.com/archives/C04LQCW0C03/p1697490246353319?thread_ts=1697095199.179759&cid=C04LQCW0C03)
- Bump golang to 1.21 to make CI work again
/kind cleanup
/assign @knative/steering-committee
=> Minor fixes for SC election 2023

mechanics/MATURITY-LEVELS.md
Look like we forgot to update one place in the docs when we changed the release cadence to quarterly.
Original PR: https://github.com/knative/community/pull/1155
This implies we support sunset features in older releases until they EOL.
Note: Our support contract is currently 2 releases now - this PR isn't changing that. That was decided in https://github.com/knative/community/issues/1096
=> Update support window mentioned in the MATURITY-LEVELS.md

STEERING-COMMITTEE.md, groups/committee-steering/groups.yaml, groups/groups.yaml, peribolos/knative-OWNERS_ALIASES, peribolos/knative-extensions-OWNERS_ALIASES, peribolos/knative-extensions.yaml, peribolos/knative.yaml
The SC election results were [announced today](https://groups.google.com/g/knative-dev/c/oO8Xtw3i-Q4), this PR updates the relevant configurations.
- Add @aliok and @evankanderson as new members
- Remove @lance and @csantanapr
Partially #1468
=> Update SC members and SC permissions

groups/committee-oversight/groups.yaml, groups/groups.yaml
Noticed some of these files were a bit out of date, so took a best guess at who should be dropped. 
Wasn't sure if the admins for automation@knative.team are the TOC, so didn't update that one.
cc @knative/technical-oversight-committee @knative/productivity-leads
=> Drop emeritus leads from various group

peribolos/knative-extensions-OWNERS_ALIASES, peribolos/knative-extensions.yaml
As a results of some restructuring due to the VMware/Broadcom acquisition we're unable to maintain this integration.
I've chatted with Chainguard and they use this integration in production so I'm transitioning approver responsibilities to them.
If anyone else would also like approver status I'd imagine the help would be welcome.
=> Chainguard taking ownership of eventing-rabbitmq

mechanics/RELEASE-SCHEDULE.md
This flushes out the min K8s versions for the releases happening this year 
- 1.27 goes into maintenance mode 04-28
- 1.28 goes into maintenance mode 08-28
source: https://kubernetes.io/releases/patch-releases/
This follows the principal defined here - https://github.com/knative/community/blob/99eba74e558b1818cf079231c755ec5549f77775/mechanics/RELEASE-VERSIONING-PRINCIPLES.md#k8s-minimum-version-principle
=> Update min K8s versions in our release schedule

peribolos/knative-extensions.yaml, peribolos/knative.yaml
I'm adding myself as a knative and knative-sandbox member so I don't need to wait for  the `ok-to-test` labels.
My contributions so far have been:
[eventing](https://github.com/knative/eventing/commits?author=xiangpingjiang)
[client](https://github.com/knative/client/commits?author=xiangpingjiang)
[docs](https://github.com/knative/docs/commits?author=xiangpingjiang)
[serving](https://github.com/knative/serving/commits?author=xiangpingjiang)
cc @Cali0707  @creydr @dsimansk
<!--
In addition, categorize the changes you're making using the "/kind" Prow command, example:
=> add xiangpingjiang to knative and knative-extensions

peribolos/knative-OWNERS_ALIASES, peribolos/knative.yaml
- adding `matzew` as member of `func-writers`
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```
=> Adding myself as member of func-writers

mechanics/TOC-REVIEW.schedule
tldr: Updates TOC review notifications to use Slack ID rather than Handle.
We have a bot that sends slack notifications to WG leads for the TOC review presentations: https://github.com/knative/community/blob/main/.github/workflows/toc-review-reminder.yaml
However, in order for individuals to get notified via Slack, we need to use their Slack ID rather than their handle (as described in [this comment](https://github.com/rtCamp/action-slack-notify/issues/93#issuecomment-854547992)). So this PR makes that update.
=> Use slack ids rather than handles for toc review notifications

groups/restrictions.yaml, groups/wg-ux/OWNERS, groups/wg-ux/groups.yaml
- I want to create a new mail alias for the UX WG leads. They're gonna sign up to some systems (Figma, etc) and they want to share their username and password for consolidation.
- So, obviously, this group needs to be private.
=> New private Google group for UX WG leads

mechanics/MATURITY-LEVELS.md
Fixes #144 
Adds definitions of alpha / beta / GA for components / features / extensions to the maturity levels doc.
Definitions are taken from: https://github.com/knative/docs/blob/main/docs/serving/configuration/feature-flags.md#lifecycle
cc @knative/technical-oversight-committee
=> Add definitions of alpha/beta/GA to maturity levels

peribolos/knative-extensions-OWNERS_ALIASES, peribolos/knative-extensions.yaml, peribolos/knative.yaml
```release-note
Iliia Khaprov @ RabbitMQ added back as Knative Eventing RabbitMQ maintainer
```
cc @dprotaso
=> Add Iliia Khaprov @ RabbitMQ as Eventing RabbitMQ maintainer

peribolos/knative-extensions.yaml, peribolos/knative.yaml
/kind enchancement
```release-note
Add Michal Kuratczyk and Aitor Pérez Cedres from RabbitMQ Team
```
cc @dprotaso @mkuratczyk
=> Add folks from RabbitMQ Team

peribolos/knative-OWNERS_ALIASES, peribolos/knative-extensions-OWNERS_ALIASES, peribolos/knative-extensions.yaml, peribolos/knative.yaml
- Remove emeritus WGs from Peribolos
-
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```
=> Remove emeritus WGs from Peribolos

peribolos/knative-extensions.yaml
- Adds peribolos entries for the proposed repository 
see https://github.com/knative/community/issues/1558
Fixes #
```release-note
```
**Docs**
```docs
```
=> func-python: adds knative-extensions/func-python

peribolos/knative-extensions-OWNERS_ALIASES, peribolos/knative-extensions.yaml
- Archive knative-extensions/net-certmanager repository
Partially https://github.com/knative/community/issues/1563
=> Archive knative-extensions/net-certmanager repository

peribolos/knative-extensions-OWNERS_ALIASES, peribolos/knative-extensions.yaml
- This PR proposes to create a new repo called `autoscaler-keda`.
- See https://github.com/knative/community/issues/1527 for more.
- Similar to https://github.com/knative/community/pull/1435.
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```
=> Propose to create the new repo autoscaler-keda

peribolos/knative-OWNERS_ALIASES, peribolos/knative-extensions-OWNERS_ALIASES, peribolos/knative-extensions.yaml, peribolos/knative.yaml
- Revoke release leads permissions since 1.14 is out
=> Revoke release leads permissions since 1.14 is out

peribolos/knative-extensions.yaml, peribolos/knative.yaml
Hi Knative team,
I am Firat Bezir, a mentee for the LFX Mentorship program working on the Knative Eventing Onboarding Improvement project. As part of my mentorship, I need to create and manage a project under the Knative organization.
Please add me as a member of the Knative organization to facilitate this process. By becoming a member, I will no longer need to use the ok-to-test labels to run tests, which will streamline my contributions and help me be more efficient in my work.
Changes:
- Add @firatbezir  as a member of the Knative organization and Knative-sandbox.
```release-note
N/A
=> Add firatbezir as Knative eventing writer

groups/groups.yaml
-
-
-
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```
=> Update WG leads group

peribolos/knative-OWNERS_ALIASES, peribolos/knative-extensions-OWNERS_ALIASES, peribolos/knative-extensions.yaml, peribolos/knative.yaml
Per final item on release checklist, revoke permissions.  
Changes 
- Revoke Release Leads role for completed release
/cc @knative/knative-release-leads 
=> Revoke Release Leads role for completed release

peribolos/knative-extensions.yaml, peribolos/knative.yaml
- The user profile doesn't exist anymore: https://github.com/shinigambit
It seems like an instance of old Prow issue: https://github.com/kubernetes/test-infra/issues/17671
There's a OK run for main org and failed for extensions, but...
https://prow.knative.dev/?job=ci-knative-peribolos
https://prow.knative.dev/?job=ci-knative-extensions-peribolos
/cc @upodroid @cardil
=> Remove 'shinigambit' user from peribolos configs

peribolos/knative-extensions.yaml
- One more instance of previously described issue with #1615 
That's probably even more strange because @thisisnotapril profile definitely exists, and we got her in Knative org. There might a problem that other invite was never accepted.
/cc @upodroid @cardil
=> Remove 'thisisnotapril' user from knative-extensions config

peribolos/knative-extensions.yaml
Reverts knative/community#1614
/cc @matzew it should work now, sorry for bumpy road. :)
/cc @upodroid
=> :robot: Adding entries for eventing-integrations

.github/workflows/peribolos-schema-validate.yaml, peribolos/knative-OWNERS_ALIASES, peribolos/knative-extensions-OWNERS_ALIASES, peribolos/knative-extensions.yaml, peribolos/knative.yaml
Related to: https://github.com/knative/release/pull/330
/cc @skonto @ReToCode 
=> Update release leads for Knative 1.16

peribolos/knative-extensions-OWNERS_ALIASES, peribolos/knative-extensions.yaml
Per https://github.com/knative-extensions/eventing-kogito/pull/419
Note: I haven't removed Eventing write access as fallback option.
/cc @ricardozanini @pierDipi 
/cc @knative/productivity-leads
=> Archive eventing-kogito repository

peribolos/knative-extensions.yaml
THE UX Working Group is developing an educational game to teach Knative concepts, starting with Eventing. We would like a new repo for this to live in, so that the main `UX` repo isn't filled with game artefacts and code
- Add eventing-game repo to the repo list
- Give Knative Admin admin permissions
- Give UX Writers write permissions
=> New Repo: adding `educational-game` repo to knative extensions

.github/workflows/peribolos-schema-validate.yaml
Related to https://github.com/knative/infra/issues/530
/cc @skonto @ReToCode @upodroid
=> Use python 3.11 for peribolos check

.github/workflows/peribolos-schema-validate.yaml, peribolos/knative-extensions-OWNERS_ALIASES, peribolos/knative-extensions.yaml, peribolos/knative.yaml
- 🗑️ Remove me from the project
/kind removal
Unfortunately, I have to withdraw from the project and focus in other project.
=> Remove me from rabbitmq-eventing maintainers

peribolos/knative-OWNERS_ALIASES, peribolos/knative-extensions-OWNERS_ALIASES, peribolos/knative-extensions.yaml, peribolos/knative.yaml
- Add KSC members to peribolos toc alias temporarily
Addressing an issue with majority of repositories not referencing steering alias in `OWNERS` file. Gradually, WGs should be able to update `OWNERS` to include `steering-commitee` and then we can sunset the other alias. 
/cc @dprotaso
=> Add KSC members to peribolos toc alias temporarily

elections/2024-SC/election.yaml
Copy & past issue.
Owners field is not needed in election config, as it does not exist in candidate template
/cc @jberkus
=> Remove owners field in 2024 SC election config

groups/groups.yaml, groups/wg-productivity/groups.yaml, groups/wg-security/groups.yaml, peribolos/knative-OWNERS_ALIASES, peribolos/knative-extensions-OWNERS_ALIASES, peribolos/knative-extensions.yaml, peribolos/knative.yaml
1. update steering teams and try to fix post update job - drop jkjell & jr from memberlist (there are warnings about those)
error message in peribolos the post submit job
`
{"client":"github","component":"peribolos","level":"info","msg":"UpdateOrgMembership(knative, jkjell, false)","severity":"info","time":"2025-01-22T20:41:01Z"}
{"component":"peribolos","error":"status code 422 not one of [200], body: {\"message\":\"The request could not be processed.\",\"documentation_url\":\"https://docs.github.com/rest/orgs/members#set-organization-membership-for-a-user\",\"status\":\"422\"}","level":"warning","msg":"UpdateOrgMembership(knative, jkjell, false) failed","severity":"warning","time":"2025-01-22T20:41:01Z"}
{"component":"peribolos","level":"info","msg":"Waiting for jrbancel to accept …
=> fix peribolos and google groups config

groups/groups.yaml, peribolos/knative-extensions.yaml, peribolos/knative.yaml
Post submit jobs failed for https://github.com/knative/community/pull/1659
groups - https://prow.knative.dev/view/gs/knative-prow/logs/post-knativeteam-groups/1883895909339631616 
peribolos - https://prow.knative.dev/view/gs/knative-prow/logs/post-knative-peribolos/1883895909410934784
Fixes:
- add the right user account 'thelinuxfoundation'
- can't make a group ('steering') an owner of a group ('wg-leads')
=> adjust memberships

elections/2025-SC-EU/README.md, elections/2025-SC-EU/nomination-template.md
-
-
-
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```
=> 2025 SC EU seat elections

elections/2025-SC-EU/candidate-nyarly.md
Adding @nyarly as End User candidate, 2025
=> Add Judson Lester (nyarly) as 2025 End User candidate

groups/groups_test.go, groups/wg-productivity/groups.yaml
- :broom: Adding Chris Suszynski to Productivity GCP admins
/kind cleanup
As [discussed on Productivity WG on Mar 12, 2025](https://docs.google.com/document/d/1aPRwYGD4XscRIqlBzbNsSB886PJ0G-vZYUAAUjoydko/edit?tab=t.0), I'm adding myself to the GCP admins group, to be able to operate terraform code, and troubleshoot issues on GCP.
=> Adding Chris Suszynski to Productivity GCP admins

peribolos/knative-OWNERS_ALIASES, peribolos/knative-extensions-OWNERS_ALIASES, peribolos/knative-extensions.yaml, peribolos/knative.yaml
Christoph has been Eventing approver for almost 2 years
(since Aug 7, 2023), he is leading the Eventing Security story,
has been the main Eventing release lead for the last year
releases, advocate for Eventing Discovery [3], and a co-mentor
for the GSoC mentorship program [4].
Christoph has over 110 mid-sized+ reviews [1], and over 130 merged
PRs [2] just in core Eventing.
[1] https://github.com/knative/eventing/pulls?q=is%3Apr+is%3Amerged+reviewed-by%3Acreydr+-label%3Asize%2FS+-label%3Asize%2FXS+-author%3Acreydr+is%3Aclosed+-mentions%3Aknative-automation+
[2] https://github.com/knative/eventing/pulls?q=is%3Apr+is%3Amerged+author%3Acreydr+is%3Aclosed
[3] https://youtu.be/z-SuVsvxvm4?si=6iw9trKW6bGus6zi
[4] https://gist.github.com/debasishbsws/5b32514a96c3c516d12e40b26ae019ea …
=> Add Christoph (@creydr) as Eventing WG lead

GOVERNANCE.md, MAINTAINERS.md, ROLES.md
- :broom: Re-add `GOVERNANCE.md`, deleted in #1587
- :broom: Add a `MAINTAINERS.md` simply to point to `ROLES.md` and explain that we recognize multiple tiers of contribution.
- :broom: Update `ROLES.md` to clarify that WG leads get CNCF maintainer status (and calendar scheduling permissions)
- :broom: :broom: Ran `prettier` on `ROLES.md` because my setup automatically does that.  Sorry for the reformatting!
=> Re-add GOVERNANCE.md removed in #1587, and add MAINTAINERS.md

peribolos/knative-extensions.yaml
- Give the Eventing Writers group write permissions for the EKB repo
=> fix: eventing writers have write permissions for ekb

PROJECTS.md, README.md
=> Include a page that gives an overview of the user facing projects of Knative
